import { db, withTransaction } from '@/lib/db/client';
import { isArangoUniqueConstraintError, toArangoDoc, withArangoKey } from '@/lib/db/base';
import { conversationMessageBaseSchema, conversationMessageSchema, conversationSchema, type Conversation, type ConversationMessage } from './schemas';
import type { AppSearchRetrieval } from '@/lib/app-search/service';
import { EMBEDDING_DIMENSIONS, currentEmbeddingSchema, embeddingMetadata } from '@/lib/embeddings';
import { CONVERSATION_ATTACHMENT_ARTIFACTS_COLLECTION } from './attachment-artifacts';
import { STORAGE_DELETION_JOBS_COLLECTION } from '@/lib/db/storage-deletion-jobs.node';

export const CONVERSATIONS_COLLECTION = 'conversations';
export const CONVERSATION_MESSAGES_COLLECTION = 'conversationMessages';
export const CONVERSATION_SEMANTIC_MINIMUM_COSINE_SIMILARITY = 0.25;
type Database = Pick<typeof db, 'query'>;
type TransactionRunner = <T>(operation: (database: Database) => Promise<T>) => Promise<T>;
type Owner = { teamKey: string; scopeKey: string; userKey: string };
const parseRows = <T>(rows: unknown[], schema: { parse(value: unknown): T }) => rows.map((row) => schema.parse(withArangoKey(row as Record<string, unknown>)));
const ATTACHMENT_CLAIM_CONFLICT = new Error('Conversation attachment claim conflict.');

export interface ConversationRepository {
  create(value: Conversation): Promise<Conversation>;
  read(owner: Owner, key: string): Promise<Conversation | null>;
  list(owner: Owner, input: { query?: string; cursor?: { favorite: boolean; updatedAt: string; key: string }; limit: number; favoriteOnly: boolean }): Promise<Conversation[]>;
  update(owner: Owner, key: string, patch: { name?: string; isFavorite?: boolean; updatedAt: string }): Promise<Conversation | null>;
  delete(owner: Owner, key: string): Promise<boolean>;
  deleteMessageTurn(owner: Owner, conversationKey: string, messageKey: string, updatedAt: string): Promise<string[] | null>;
  beginTurn(owner: Owner, conversationKey: string, user: ConversationMessage, assistant: ConversationMessage, actorKey?: string): Promise<{ state: 'created'; user: ConversationMessage; assistant: ConversationMessage; first: boolean } | { state: 'replay'; user: ConversationMessage; assistant: ConversationMessage; first: boolean } | { state: 'busy' } | { state: 'idempotency-conflict' } | { state: 'attachment-conflict' } | null>;
  beginImageTurn(owner: Owner, conversationKey: string, user: ConversationMessage, assistant: ConversationMessage): Promise<{ state: 'created' | 'replay'; user: ConversationMessage; assistant: ConversationMessage } | { state: 'idempotency-conflict' } | null>;
  completeTurn(owner: Owner, conversationKey: string, assistantKey: string, content: string, embedding: number[] | undefined, retrievals: AppSearchRetrieval[], completedAt: string, generatedName?: string): Promise<{ message: ConversationMessage; nameApplied: boolean } | null>;
  setImageStatusText(owner: Owner, conversationKey: string, assistantKey: string, statusText: string): Promise<ConversationMessage | null>;
  completeImageTurn(owner: Owner, conversationKey: string, assistantKey: string, imageKey: string, summaryText: string, completedAt: string): Promise<ConversationMessage | null>;
  setMessageEmbedding(owner: Owner, conversationKey: string, messageKey: string, embedding: number[]): Promise<boolean>;
  failTurn(owner: Owner, conversationKey: string, assistantKey: string, completedAt: string, fundingRequiredCode?: 'INSUFFICIENT_BALANCE' | 'OUTSTANDING_DEBT'): Promise<boolean>;
  listMessages(owner: Owner, conversationKey: string, cursor: { createdAt: string; key: string } | undefined, limit: number): Promise<ConversationMessage[] | null>;
  latestCompletedMessages(owner: Owner, conversationKey: string, before: string, limit: number): Promise<ConversationMessage[] | null>;
  semanticMessages(owner: Owner, embedding: number[], input: { before: string; excludedKeys: string[]; limit: number }): Promise<Array<{ message: ConversationMessage; similarity: number }>>;
  listPendingImageTurns(): Promise<Array<{ message: ConversationMessage; actorKey: string }>>;
}

export function createConversationRepository(database: Database = db, transact: TransactionRunner = database === db ? (operation) => withTransaction([CONVERSATIONS_COLLECTION, CONVERSATION_MESSAGES_COLLECTION, CONVERSATION_ATTACHMENT_ARTIFACTS_COLLECTION, STORAGE_DELETION_JOBS_COLLECTION], (transaction) => operation(transaction)) : (operation) => operation(database)): ConversationRepository {
  const owned = 'conversation.teamKey == @teamKey && conversation.scopeKey == @scopeKey && conversation.userKey == @userKey';
  const replayTurn = async (owner: Owner, conversationKey: string, turnKey: string, requestHash: string) => {
    const cursor = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET existingUser = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "USER" LIMIT 1 RETURN message) LET existingAssistant = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "ASSISTANT" LIMIT 1 RETURN message) FILTER existingUser != null && existingAssistant != null RETURN { existingUser, existingAssistant, first: LENGTH(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.role == "ASSISTANT" && message.status == "COMPLETED" && message.createdAt < existingAssistant.createdAt LIMIT 1 RETURN 1) == 0 }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, turnKey });
    const row = await cursor.next() as { existingUser: Record<string, unknown>; existingAssistant: Record<string, unknown>; first: boolean } | undefined;
    if (!row) return null;
    const user = conversationMessageSchema.parse(withArangoKey(row.existingUser)); const assistant = conversationMessageSchema.parse(withArangoKey(row.existingAssistant));
    return user.requestHash === requestHash && assistant.requestHash === requestHash ? { state: 'replay' as const, user, assistant, first: row.first } : { state: 'idempotency-conflict' as const };
  };
  return {
    async create(value) { const parsed = conversationSchema.parse(value); const cursor = await database.query('INSERT @value INTO @@collection RETURN NEW', { '@collection': CONVERSATIONS_COLLECTION, value: toArangoDoc(parsed) }); return conversationSchema.parse(withArangoKey(await cursor.next() as Record<string, unknown>)); },
    async read(owner, key) { const cursor = await database.query(`FOR conversation IN @@collection FILTER conversation._key == @key && ${owned} LIMIT 1 RETURN conversation`, { '@collection': CONVERSATIONS_COLLECTION, ...owner, key }); const row = await cursor.next(); return row ? conversationSchema.parse(withArangoKey(row as Record<string, unknown>)) : null; },
    async list(owner, input) {
      const cursor = await database.query(`FOR conversation IN @@collection FILTER ${owned} FILTER !@favoriteOnly || conversation.isFavorite == true FILTER @query == null || CONTAINS(LOWER(conversation.name), @query) FILTER @cursor == null || conversation.isFavorite < @cursor.favorite || (conversation.isFavorite == @cursor.favorite && (conversation.updatedAt < @cursor.updatedAt || (conversation.updatedAt == @cursor.updatedAt && conversation._key > @cursor.key))) SORT conversation.isFavorite DESC, conversation.updatedAt DESC, conversation._key ASC LIMIT @limit RETURN conversation`, { '@collection': CONVERSATIONS_COLLECTION, ...owner, favoriteOnly: input.favoriteOnly, query: input.query?.toLocaleLowerCase() ?? null, cursor: input.cursor ?? null, limit: input.limit });
      return parseRows(await cursor.all(), conversationSchema);
    },
    async update(owner, key, patch) { const cursor = await database.query(`FOR conversation IN @@collection FILTER conversation._key == @key && ${owned} UPDATE conversation WITH @patch IN @@collection RETURN NEW`, { '@collection': CONVERSATIONS_COLLECTION, ...owner, key, patch }); const row = await cursor.next(); return row ? conversationSchema.parse(withArangoKey(row as Record<string, unknown>)) : null; },
    async delete(owner, key) { return transact(async (trx) => { const cursor = await trx.query(`LET conversation = DOCUMENT(@@conversations, @key) FILTER conversation != null && ${owned} LET artifacts = (FOR artifact IN @@artifacts FILTER artifact.conversationKey == conversation._key && artifact.teamKey == @teamKey && artifact.scopeKey == @scopeKey && artifact.userKey == @userKey RETURN artifact) LET queuedStorage = (FOR artifact IN artifacts UPSERT { storageKey: artifact.stagedStorageKey } INSERT { storageKey: artifact.stagedStorageKey, createdAt: artifact.createdAt, status: "pending" } UPDATE {} IN @@storageJobs RETURN 1) LET removedArtifacts = (FOR artifact IN artifacts REMOVE artifact IN @@artifacts RETURN 1) LET removedMessages = (FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey REMOVE message IN @@messages RETURN 1) REMOVE conversation IN @@conversations RETURN true`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, '@artifacts': CONVERSATION_ATTACHMENT_ARTIFACTS_COLLECTION, '@storageJobs': STORAGE_DELETION_JOBS_COLLECTION, ...owner, key }); return Boolean(await cursor.next()); }); },
    async deleteMessageTurn(owner, conversationKey, messageKey, updatedAt) { return transact(async (trx) => { const cursor = await trx.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET selected = DOCUMENT(@@messages, @messageKey) FILTER selected != null && selected.conversationKey == conversation._key && selected.teamKey == @teamKey && selected.scopeKey == @scopeKey && selected.userKey == @userKey LET pending = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.turnKey == selected.turnKey && message.status == "PENDING" LIMIT 1 RETURN true) FILTER pending == null LET selectedMessages = (FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.turnKey == selected.turnKey RETURN message) LET selectedKeys = selectedMessages[*]._key LET selectedArtifactKeys = UNIQUE(FLATTEN(selectedMessages[*].imageReferenceArtifactKeys)) LET retainedArtifactKeys = UNIQUE(FLATTEN(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.turnKey != selected.turnKey RETURN message.imageReferenceArtifactKeys || [])) LET artifacts = (FOR artifact IN @@artifacts FILTER artifact.teamKey == @teamKey && artifact.scopeKey == @scopeKey && artifact.userKey == @userKey && artifact.conversationKey == conversation._key && (artifact.userMessageKey IN selectedKeys || artifact._key IN selectedArtifactKeys) && artifact._key NOT IN retainedArtifactKeys RETURN artifact) LET queuedStorage = (FOR artifact IN artifacts UPSERT { storageKey: artifact.stagedStorageKey } INSERT { storageKey: artifact.stagedStorageKey, createdAt: artifact.createdAt, status: "pending" } UPDATE {} IN @@storageJobs RETURN 1) LET removedArtifacts = (FOR artifact IN artifacts REMOVE artifact IN @@artifacts RETURN 1) LET deletedKeys = (FOR message IN selectedMessages REMOVE message IN @@messages RETURN OLD._key) UPDATE conversation WITH { updatedAt: @updatedAt } IN @@conversations RETURN deletedKeys`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, '@artifacts': CONVERSATION_ATTACHMENT_ARTIFACTS_COLLECTION, '@storageJobs': STORAGE_DELETION_JOBS_COLLECTION, ...owner, conversationKey, messageKey, updatedAt }); const deletedKeys = await cursor.next() as string[] | undefined; return deletedKeys?.length ? deletedKeys : null; }); },
    async beginTurn(owner, conversationKey, user, assistant, actorKey) {
      const validUser = conversationMessageSchema.parse(user), validAssistant = conversationMessageSchema.parse(assistant);
      try {
        return await transact(async (trx) => {
           const found = await trx.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET existingUser = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "USER" LIMIT 1 RETURN message) LET existingAssistant = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "ASSISTANT" LIMIT 1 RETURN message) LET active = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.type == "TEXT" && message.role == "ASSISTANT" && message.status == "PENDING" LIMIT 1 RETURN message._key) LET completed = LENGTH(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.type == "TEXT" && message.role == "ASSISTANT" && message.status == "COMPLETED" LIMIT 1 RETURN 1) RETURN { existingUser, existingAssistant, active, first: completed == 0 }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, turnKey: validUser.turnKey });
          const existing = await found.next() as { existingUser: Record<string, unknown> | null; existingAssistant: Record<string, unknown> | null; active: string | null; first: boolean } | undefined;
          if (!existing) return null;
          if (existing.existingUser || existing.existingAssistant) {
            if (!existing.existingUser || !existing.existingAssistant) return { state: 'idempotency-conflict' as const };
            const replayUser = conversationMessageSchema.parse(withArangoKey(existing.existingUser)), replayAssistant = conversationMessageSchema.parse(withArangoKey(existing.existingAssistant));
            return replayUser.requestHash === validUser.requestHash && replayAssistant.requestHash === validUser.requestHash ? { state: 'replay' as const, user: replayUser, assistant: replayAssistant, first: existing.first } : { state: 'idempotency-conflict' as const };
          }
           if (existing.active) return { state: 'busy' as const };
           const attachmentKeys = validUser.pendingAttachmentKeys ?? [];
           if (attachmentKeys.length) {
             if (!actorKey) return { state: 'attachment-conflict' as const };
             const claimed = await trx.query('FOR artifact IN @@artifacts FILTER artifact._key IN @attachmentKeys && artifact.teamKey == @teamKey && artifact.scopeKey == @scopeKey && artifact.userKey == @userKey && artifact.ownerKey == @actorKey && artifact.conversationKey == @conversationKey && artifact.requestKey == @turnKey && artifact.status == "PREPARED" && artifact.expiresAt > @now UPDATE artifact WITH { status: "CLAIMED", userMessageKey: @userMessageKey, availableAt: @now } IN @@artifacts RETURN NEW._key', { '@artifacts': CONVERSATION_ATTACHMENT_ARTIFACTS_COLLECTION, ...owner, actorKey, conversationKey, turnKey: validUser.turnKey, attachmentKeys, userMessageKey: validUser.key, now: validUser.createdAt });
             if ((await claimed.all()).length !== attachmentKeys.length) throw ATTACHMENT_CLAIM_CONFLICT;
           }
           const users = await trx.query('INSERT @user INTO @@messages RETURN NEW', { '@messages': CONVERSATION_MESSAGES_COLLECTION, user: toArangoDoc(validUser) });
          const assistants = await trx.query('INSERT @assistant INTO @@messages RETURN NEW', { '@messages': CONVERSATION_MESSAGES_COLLECTION, assistant: toArangoDoc(validAssistant) });
          return { state: 'created' as const, user: conversationMessageSchema.parse(withArangoKey(await users.next() as Record<string, unknown>)), assistant: conversationMessageSchema.parse(withArangoKey(await assistants.next() as Record<string, unknown>)), first: existing.first };
        });
      } catch (error) {
        if (error === ATTACHMENT_CLAIM_CONFLICT) return { state: 'attachment-conflict' as const };
        if (!isArangoUniqueConstraintError(error)) throw error;
        return await replayTurn(owner, conversationKey, validUser.turnKey, validUser.requestHash) ?? { state: 'idempotency-conflict' as const };
      }
    },
    async beginImageTurn(owner, conversationKey, user, assistant) {
      const validUser = conversationMessageSchema.parse(user), validAssistant = conversationMessageSchema.parse(assistant);
      if (validUser.type !== 'IMAGE' || validAssistant.type !== 'IMAGE') throw new Error('Image turn messages are required.');
      try {
        return await transact(async (trx) => {
          const found = await trx.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET existingUser = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "USER" LIMIT 1 RETURN message) LET existingAssistant = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "ASSISTANT" LIMIT 1 RETURN message) RETURN { existingUser, existingAssistant }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, turnKey: validUser.turnKey });
          const existing = await found.next() as { existingUser: Record<string, unknown> | null; existingAssistant: Record<string, unknown> | null } | undefined;
          if (!existing) return null;
          if (existing.existingUser || existing.existingAssistant) {
            if (!existing.existingUser || !existing.existingAssistant) return { state: 'idempotency-conflict' as const };
            const replayUser = conversationMessageSchema.parse(withArangoKey(existing.existingUser)), replayAssistant = conversationMessageSchema.parse(withArangoKey(existing.existingAssistant));
            return replayUser.type === 'IMAGE' && replayAssistant.type === 'IMAGE' && replayUser.requestHash === validUser.requestHash && replayAssistant.requestHash === validUser.requestHash ? { state: 'replay' as const, user: replayUser, assistant: replayAssistant } : { state: 'idempotency-conflict' as const };
          }
          const users = await trx.query('INSERT @user INTO @@messages RETURN NEW', { '@messages': CONVERSATION_MESSAGES_COLLECTION, user: toArangoDoc(validUser) });
          const assistants = await trx.query('INSERT @assistant INTO @@messages RETURN NEW', { '@messages': CONVERSATION_MESSAGES_COLLECTION, assistant: toArangoDoc(validAssistant) });
          await trx.query('UPDATE @conversationKey WITH { updatedAt: @updatedAt } IN @@conversations', { '@conversations': CONVERSATIONS_COLLECTION, conversationKey, updatedAt: validAssistant.createdAt });
          return { state: 'created' as const, user: conversationMessageSchema.parse(withArangoKey(await users.next() as Record<string, unknown>)), assistant: conversationMessageSchema.parse(withArangoKey(await assistants.next() as Record<string, unknown>)) };
        });
      } catch (error) {
        if (!isArangoUniqueConstraintError(error)) throw error;
        const replay = await replayTurn(owner, conversationKey, validUser.turnKey, validUser.requestHash);
        return replay?.state === 'replay' && replay.user.type === 'IMAGE' && replay.assistant.type === 'IMAGE' ? { state: 'replay', user: replay.user, assistant: replay.assistant } : replay ? { state: 'idempotency-conflict' } : null;
      }
    },
    async completeTurn(owner, conversationKey, assistantKey, content, embedding, retrievals, completedAt, generatedName) { const validRetrievals = conversationMessageBaseSchema.shape.retrievals.parse(retrievals); return transact(async (trx) => { const cursor = await trx.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET message = DOCUMENT(@@messages, @assistantKey) FILTER message != null && message.conversationKey == conversation._key && message.userKey == @userKey && message.type == "TEXT" && message.role == "ASSISTANT" && message.status == "PENDING" LET priorCompleted = LENGTH(FOR other IN @@messages FILTER other.conversationKey == conversation._key && other.type == "TEXT" && other.role == "ASSISTANT" && other.status == "COMPLETED" LIMIT 1 RETURN 1) LET nameApplied = @generatedName != null && conversation.name == @defaultName && priorCompleted == 0 LET completed = FIRST(UPDATE message WITH MERGE({ content: @content, retrievals: @retrievals, status: "COMPLETED", completedAt: @completedAt }, @embedding == null ? {} : { embedding: @embedding }) IN @@messages RETURN NEW) UPDATE conversation WITH MERGE({ updatedAt: @completedAt }, nameApplied ? { name: @generatedName } : {}) IN @@conversations RETURN { completed, nameApplied }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, content, embedding: embedding ?? null, retrievals: validRetrievals, completedAt, generatedName: generatedName ?? null, defaultName: 'New chat' }); const row = await cursor.next() as { completed: Record<string, unknown>; nameApplied: boolean } | undefined; return row ? { message: conversationMessageSchema.parse(withArangoKey(row.completed)), nameApplied: row.nameApplied } : null; }); },
    async setImageStatusText(owner, conversationKey, assistantKey, statusText) { const validStatusText = conversationMessageBaseSchema.shape.imageStatusText.unwrap().parse(statusText); const cursor = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET message = DOCUMENT(@@messages, @assistantKey) FILTER message != null && message.conversationKey == conversation._key && message.userKey == @userKey && message.type == "IMAGE" && message.role == "ASSISTANT" UPDATE message WITH { imageStatusText: @statusText } IN @@messages RETURN NEW`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, statusText: validStatusText }); const row = await cursor.next(); return row ? conversationMessageSchema.parse(withArangoKey(row as Record<string, unknown>)) : null; },
    async completeImageTurn(owner, conversationKey, assistantKey, imageKey, summaryText, completedAt) { const validSummary = conversationMessageBaseSchema.shape.imageSummaryText.unwrap().parse(summaryText); const cursor = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET message = DOCUMENT(@@messages, @assistantKey) FILTER message != null && message.conversationKey == conversation._key && message.userKey == @userKey && message.type == "IMAGE" && message.role == "ASSISTANT" && message.status == "PENDING" LET completed = FIRST(UPDATE message WITH { imageKey: @imageKey, imageSummaryText: @summaryText, status: "COMPLETED", completedAt: @completedAt } IN @@messages RETURN NEW) UPDATE conversation WITH { updatedAt: @completedAt } IN @@conversations RETURN completed`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, imageKey, summaryText: validSummary, completedAt }); const row = await cursor.next(); return row ? conversationMessageSchema.parse(withArangoKey(row as Record<string, unknown>)) : null; },
    async setMessageEmbedding(owner, conversationKey, messageKey, embedding) { const vector = currentEmbeddingSchema.parse(embedding); const cursor = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} FOR message IN @@messages FILTER message._key == @messageKey && message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.type == "TEXT" && message.status == "COMPLETED" UPDATE message WITH MERGE({ embedding: @embedding }, @metadata) IN @@messages RETURN true`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, messageKey, embedding: vector, metadata: embeddingMetadata() }); return Boolean(await cursor.next()); },
    async failTurn(owner, conversationKey, assistantKey, completedAt, fundingRequiredCode) { const cursor = await database.query(`LET selected = FIRST(FOR message IN @@messages FILTER message._key == @assistantKey && message.conversationKey == @conversationKey && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.role == "ASSISTANT" && message.status == "PENDING" LIMIT 1 RETURN message) FILTER selected != null FOR message IN @@messages FILTER message._key == selected._key || (@fundingRequiredCode != null && message.userKey == @userKey && message.fundingRequiredCode IN ["INSUFFICIENT_BALANCE", "OUTSTANDING_DEBT"] && message.fundingRequiredAcknowledgedAt == null) SORT message._key == selected._key DESC UPDATE message WITH (message._key == selected._key ? MERGE({ status: "FAILED", completedAt: @completedAt }, @fundingRequiredCode == null ? {} : { fundingRequiredCode: @fundingRequiredCode }) : { fundingRequiredAcknowledgedAt: @completedAt }) IN @@messages RETURN message._key == selected._key`, { '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, completedAt, fundingRequiredCode: fundingRequiredCode ?? null }); return await cursor.next() === true; },
    async listMessages(owner, conversationKey, cursor, limit) { const result = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} RETURN (FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey FILTER @cursor == null || message.createdAt < @cursor.createdAt || (message.createdAt == @cursor.createdAt && message._key < @cursor.key) SORT message.createdAt DESC, message._key DESC LIMIT @limit RETURN message)`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, cursor: cursor ?? null, limit }); const rows = await result.next() as unknown[] | undefined; return rows ? parseRows(rows, conversationMessageSchema).reverse() : null; },
    async latestCompletedMessages(owner, conversationKey, before, limit) { const result = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} RETURN (FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.type == "TEXT" && message.role IN ["USER", "ASSISTANT"] && message.status == "COMPLETED" && message.createdAt < @before SORT message.createdAt DESC, message.turnKey DESC, message.role ASC, message._key DESC LIMIT @limit RETURN message)`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, before, limit }); const rows = await result.next() as unknown[] | undefined; return rows ? parseRows(rows, conversationMessageSchema).reverse() : null; },
    async semanticMessages(owner, embedding, input) { const vector = currentEmbeddingSchema.parse(embedding); const metadata = embeddingMetadata(); const result = await database.query(`FOR message IN @@messages FILTER message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.type == "TEXT" && message.role IN ["USER", "ASSISTANT"] && message.status == "COMPLETED" && message.createdAt < @before && !POSITION(@excludedKeys, message._key) FILTER IS_ARRAY(message.embedding) && LENGTH(message.embedding) == @dimensions && message.embeddingProvider == @embeddingProvider && message.embeddingModel == @embeddingModel && message.embeddingDimensions == @dimensions LET conversation = DOCUMENT(@@conversations, message.conversationKey) FILTER conversation != null && ${owned} && message.conversationKey == conversation._key LET similarity = COSINE_SIMILARITY(message.embedding, @embedding) FILTER IS_NUMBER(similarity) && similarity >= @minimumSimilarity SORT similarity DESC, message.createdAt DESC, message._key DESC LIMIT @limit RETURN { message, similarity }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, embedding: vector, dimensions: EMBEDDING_DIMENSIONS, embeddingProvider: metadata.embeddingProvider, embeddingModel: metadata.embeddingModel, minimumSimilarity: CONVERSATION_SEMANTIC_MINIMUM_COSINE_SIMILARITY, before: input.before, excludedKeys: input.excludedKeys, limit: Math.min(input.limit, 20) }); const rows = await result.all() as Array<{ message: Record<string, unknown>; similarity: number }>; return rows.map((row) => ({ message: conversationMessageSchema.parse(withArangoKey(row.message)), similarity: row.similarity })); },
    async listPendingImageTurns() { const result = await database.query(`FOR message IN @@messages FILTER message.type == "IMAGE" && message.role == "ASSISTANT" && message.status == "PENDING" LET conversation = DOCUMENT(@@conversations, message.conversationKey) FILTER conversation != null && conversation.teamKey == message.teamKey && conversation.scopeKey == message.scopeKey && conversation.userKey == message.userKey LET membership = FIRST(FOR actor IN userTeams FILTER actor.teamKey == message.teamKey && actor.userId == message.userKey && actor.status == "active" LIMIT 1 RETURN actor._key) FILTER membership != null RETURN { message, actorKey: membership }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION }); const rows = await result.all() as Array<{ message: Record<string, unknown>; actorKey: string }>; return rows.map((row) => ({ message: conversationMessageSchema.parse(withArangoKey(row.message)), actorKey: row.actorKey })); },
  };
}

let repository: ConversationRepository | undefined;
export const getDefaultConversationRepository = () => repository ??= createConversationRepository();
