import { z } from 'zod';
import { db, withTransaction } from '@/lib/db/client';
import { isArangoUniqueConstraintError, toArangoDoc, withArangoKey } from '@/lib/db/base';
import { conversationMessageSchema, conversationSchema, type Conversation, type ConversationMessage } from './schemas';

export const CONVERSATIONS_COLLECTION = 'conversations';
export const CONVERSATION_MESSAGES_COLLECTION = 'conversationMessages';
type Database = Pick<typeof db, 'query'>;
type TransactionRunner = <T>(operation: (database: Database) => Promise<T>) => Promise<T>;
type Owner = { organizationKey: string; scopeKey: string; userKey: string };
const parseRows = <T>(rows: unknown[], schema: z.ZodType<T>) => rows.map((row) => schema.parse(withArangoKey(row as Record<string, unknown>)));

export interface ConversationRepository {
  create(value: Conversation): Promise<Conversation>;
  read(owner: Owner, key: string): Promise<Conversation | null>;
  list(owner: Owner, input: { query?: string; cursor?: { favorite: boolean; updatedAt: string; key: string }; limit: number; favoriteOnly: boolean }): Promise<Conversation[]>;
  update(owner: Owner, key: string, patch: { name?: string; isFavorite?: boolean; updatedAt: string }): Promise<Conversation | null>;
  delete(owner: Owner, key: string): Promise<boolean>;
  beginTurn(owner: Owner, conversationKey: string, user: ConversationMessage, assistant: ConversationMessage): Promise<{ state: 'created'; user: ConversationMessage; assistant: ConversationMessage; first: boolean } | { state: 'replay'; user: ConversationMessage; assistant: ConversationMessage; first: boolean } | { state: 'busy' } | { state: 'idempotency-conflict' } | null>;
  completeTurn(owner: Owner, conversationKey: string, assistantKey: string, content: string, embedding: number[], completedAt: string, generatedName?: string): Promise<{ message: ConversationMessage; nameApplied: boolean } | null>;
  failTurn(owner: Owner, conversationKey: string, assistantKey: string, completedAt: string): Promise<void>;
  listMessages(owner: Owner, conversationKey: string, cursor: { createdAt: string; key: string } | undefined, limit: number): Promise<ConversationMessage[] | null>;
  semanticMessages(owner: Owner, conversationKey: string, embedding: number[], limit: number): Promise<Array<{ message: ConversationMessage; similarity: number }> | null>;
}

export function createConversationRepository(database: Database = db, transact: TransactionRunner = database === db ? (operation) => withTransaction([CONVERSATIONS_COLLECTION, CONVERSATION_MESSAGES_COLLECTION], (transaction) => operation(transaction)) : (operation) => operation(database)): ConversationRepository {
  const owned = 'conversation.organizationKey == @organizationKey && conversation.scopeKey == @scopeKey && conversation.userKey == @userKey';
  const replayTurn = async (owner: Owner, conversationKey: string, turnKey: string, requestHash: string) => {
    const cursor = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET existingUser = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "USER" LIMIT 1 RETURN message) LET existingAssistant = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "ASSISTANT" LIMIT 1 RETURN message) FILTER existingUser != null && existingAssistant != null RETURN { existingUser, existingAssistant, first: LENGTH(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.role == "ASSISTANT" && message.status == "COMPLETED" && message.createdAt < existingAssistant.createdAt LIMIT 1 RETURN 1) == 0 }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, turnKey });
    const row = await cursor.next() as { existingUser: Record<string, unknown>; existingAssistant: Record<string, unknown>; first: boolean } | undefined;
    if (!row) return null;
    const user = conversationMessageSchema.parse(withArangoKey(row.existingUser)); const assistant = conversationMessageSchema.parse(withArangoKey(row.existingAssistant));
    return user.requestHash === requestHash && assistant.requestHash === requestHash ? { state: 'replay' as const, user, assistant, first: row.first } : { state: 'idempotency-conflict' as const };
  };
  return {
    async create(value) { const parsed = conversationSchema.parse(value); const cursor = await database.query('INSERT @value INTO @@collection RETURN NEW', { '@collection': CONVERSATIONS_COLLECTION, value: toArangoDoc(parsed) }); return conversationSchema.parse(withArangoKey(await cursor.next() as Record<string, unknown>)); },
    async read(owner, key) { const cursor = await database.query(`FOR conversation IN @@collection FILTER conversation._key == @key && ${owned} LIMIT 1 RETURN conversation`, { '@collection': CONVERSATIONS_COLLECTION, ...owner, key }); const row = await cursor.next(); return row ? conversationSchema.parse(withArangoKey(row as Record<string, unknown>)) : null; },
    async list(owner, input) {
      const cursor = await database.query(`FOR conversation IN @@collection FILTER ${owned} FILTER !@favoriteOnly || conversation.isFavorite == true FILTER @query == null || CONTAINS(LOWER(conversation.name), @query) FILTER @cursor == null || conversation.isFavorite < @cursor.favorite || (conversation.isFavorite == @cursor.favorite && (conversation.updatedAt < @cursor.updatedAt || (conversation.updatedAt == @cursor.updatedAt && conversation._key > @cursor.key))) SORT conversation.isFavorite DESC, conversation.updatedAt DESC, conversation._key ASC LIMIT @limit RETURN conversation`, { '@collection': CONVERSATIONS_COLLECTION, ...owner, favoriteOnly: input.favoriteOnly, query: input.query?.toLocaleLowerCase() ?? null, cursor: input.cursor ?? null, limit: input.limit });
      return parseRows(await cursor.all(), conversationSchema);
    },
    async update(owner, key, patch) { const cursor = await database.query(`FOR conversation IN @@collection FILTER conversation._key == @key && ${owned} UPDATE conversation WITH @patch IN @@collection RETURN NEW`, { '@collection': CONVERSATIONS_COLLECTION, ...owner, key, patch }); const row = await cursor.next(); return row ? conversationSchema.parse(withArangoKey(row as Record<string, unknown>)) : null; },
    async delete(owner, key) { return transact(async (trx) => { const cursor = await trx.query(`LET conversation = DOCUMENT(@@conversations, @key) FILTER conversation != null && ${owned} LET removedMessages = (FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.organizationKey == @organizationKey && message.scopeKey == @scopeKey && message.userKey == @userKey REMOVE message IN @@messages RETURN 1) REMOVE conversation IN @@conversations RETURN true`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, key }); return Boolean(await cursor.next()); }); },
    async beginTurn(owner, conversationKey, user, assistant) {
      const validUser = conversationMessageSchema.parse(user), validAssistant = conversationMessageSchema.parse(assistant);
      try {
        return await transact(async (trx) => {
          const found = await trx.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET existingUser = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "USER" LIMIT 1 RETURN message) LET existingAssistant = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "ASSISTANT" LIMIT 1 RETURN message) LET active = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.role == "ASSISTANT" && message.status == "PENDING" LIMIT 1 RETURN message._key) LET completed = LENGTH(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.role == "ASSISTANT" && message.status == "COMPLETED" LIMIT 1 RETURN 1) RETURN { existingUser, existingAssistant, active, first: completed == 0 }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, turnKey: validUser.turnKey });
          const existing = await found.next() as { existingUser: Record<string, unknown> | null; existingAssistant: Record<string, unknown> | null; active: string | null; first: boolean } | undefined;
          if (!existing) return null;
          if (existing.existingUser || existing.existingAssistant) {
            if (!existing.existingUser || !existing.existingAssistant) return { state: 'idempotency-conflict' as const };
            const replayUser = conversationMessageSchema.parse(withArangoKey(existing.existingUser)), replayAssistant = conversationMessageSchema.parse(withArangoKey(existing.existingAssistant));
            return replayUser.requestHash === validUser.requestHash && replayAssistant.requestHash === validUser.requestHash ? { state: 'replay' as const, user: replayUser, assistant: replayAssistant, first: existing.first } : { state: 'idempotency-conflict' as const };
          }
          if (existing.active) return { state: 'busy' as const };
          const users = await trx.query('INSERT @user INTO @@messages RETURN NEW', { '@messages': CONVERSATION_MESSAGES_COLLECTION, user: toArangoDoc(validUser) });
          const assistants = await trx.query('INSERT @assistant INTO @@messages RETURN NEW', { '@messages': CONVERSATION_MESSAGES_COLLECTION, assistant: toArangoDoc(validAssistant) });
          return { state: 'created' as const, user: conversationMessageSchema.parse(withArangoKey(await users.next() as Record<string, unknown>)), assistant: conversationMessageSchema.parse(withArangoKey(await assistants.next() as Record<string, unknown>)), first: existing.first };
        });
      } catch (error) {
        if (!isArangoUniqueConstraintError(error)) throw error;
        return await replayTurn(owner, conversationKey, validUser.turnKey, validUser.requestHash) ?? { state: 'idempotency-conflict' as const };
      }
    },
    async completeTurn(owner, conversationKey, assistantKey, content, embedding, completedAt, generatedName) { return transact(async (trx) => { const cursor = await trx.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET message = DOCUMENT(@@messages, @assistantKey) FILTER message != null && message.conversationKey == conversation._key && message.userKey == @userKey && message.role == "ASSISTANT" && message.status == "PENDING" LET priorCompleted = LENGTH(FOR other IN @@messages FILTER other.conversationKey == conversation._key && other.role == "ASSISTANT" && other.status == "COMPLETED" LIMIT 1 RETURN 1) LET nameApplied = @generatedName != null && conversation.name == @defaultName && priorCompleted == 0 LET completed = FIRST(UPDATE message WITH { content: @content, embedding: @embedding, status: "COMPLETED", completedAt: @completedAt } IN @@messages RETURN NEW) UPDATE conversation WITH MERGE({ updatedAt: @completedAt }, nameApplied ? { name: @generatedName } : {}) IN @@conversations RETURN { completed, nameApplied }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, content, embedding, completedAt, generatedName: generatedName ?? null, defaultName: 'New chat' }); const row = await cursor.next() as { completed: Record<string, unknown>; nameApplied: boolean } | undefined; return row ? { message: conversationMessageSchema.parse(withArangoKey(row.completed)), nameApplied: row.nameApplied } : null; }); },
    async failTurn(owner, conversationKey, assistantKey, completedAt) { await database.query(`FOR message IN @@messages FILTER message._key == @assistantKey && message.conversationKey == @conversationKey && message.organizationKey == @organizationKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.role == "ASSISTANT" && message.status == "PENDING" UPDATE message WITH { status: "FAILED", completedAt: @completedAt } IN @@messages`, { '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, completedAt }); },
    async listMessages(owner, conversationKey, cursor, limit) { const result = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} RETURN (FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.organizationKey == @organizationKey && message.scopeKey == @scopeKey && message.userKey == @userKey FILTER @cursor == null || message.createdAt < @cursor.createdAt || (message.createdAt == @cursor.createdAt && message._key < @cursor.key) SORT message.createdAt DESC, message._key DESC LIMIT @limit RETURN message)`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, cursor: cursor ?? null, limit }); const rows = await result.next() as unknown[] | undefined; return rows ? parseRows(rows, conversationMessageSchema).reverse() : null; },
    async semanticMessages(owner, conversationKey, embedding, limit) { const result = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} RETURN (FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.organizationKey == @organizationKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.role == "ASSISTANT" && message.status == "COMPLETED" FILTER IS_ARRAY(message.embedding) && LENGTH(message.embedding) == LENGTH(@embedding) LET similarity = COSINE_SIMILARITY(message.embedding, @embedding) FILTER IS_NUMBER(similarity) SORT similarity DESC, message.createdAt DESC, message._key DESC LIMIT @limit RETURN { message, similarity })`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, embedding, limit }); const rows = await result.next() as Array<{ message: Record<string, unknown>; similarity: number }> | undefined; return rows?.map((row) => ({ message: conversationMessageSchema.parse(withArangoKey(row.message)), similarity: row.similarity })) ?? null; },
  };
}

let repository: ConversationRepository | undefined;
export const getDefaultConversationRepository = () => repository ??= createConversationRepository();
