import { db, withTransaction } from '@/lib/db/client';
import { z } from 'zod';
import { isArangoUniqueConstraintError, toArangoDoc, withArangoKey } from '@/lib/db/base';
import { DEFAULT_CONVERSATION_NAME, conversationMessageBaseSchema, conversationMessageSchema, conversationSchema, guideModeSchema, guideTopicSelectionSchema, guideTopicsSchema, type Conversation, type ConversationMessage } from './schemas';
import type { AppSearchRetrieval } from '@/lib/app-search/service';
import { EMBEDDING_DIMENSIONS, currentEmbeddingSchema, embeddingMetadata } from '@/lib/embeddings';
import { CONVERSATION_ATTACHMENT_ARTIFACTS_COLLECTION, CONVERSATION_ATTACHMENT_LEASE_MS } from './attachment-artifacts';
import { STORAGE_DELETION_JOBS_COLLECTION } from '@/lib/db/storage-deletion-jobs.node';
import { DOCUMENTS_COLLECTION } from '@/lib/db/documents.node';
import { CONVERSATION_ARCHIVE_STATES_COLLECTION, CONVERSATION_ARCHIVE_SUMMARY_MAX_CHARACTERS, conversationArchiveKeys, conversationArchiveStateSchema, type ConversationArchiveState } from './archive-projection';

export const CONVERSATIONS_COLLECTION = 'conversations';
export const CONVERSATION_MESSAGES_COLLECTION = 'conversationMessages';
export const CONVERSATION_SEMANTIC_MINIMUM_COSINE_SIMILARITY = 0.25;
type Database = Pick<typeof db, 'query'>;
type TransactionCollections = { read?: string[]; write: string[]; exclusive?: string[] };
type TransactionRunner = <T>(operation: (database: Database) => Promise<T>, collections?: TransactionCollections) => Promise<T>;
const CONVERSATION_TRANSACTION_WRITE = [CONVERSATIONS_COLLECTION, CONVERSATION_MESSAGES_COLLECTION, CONVERSATION_ATTACHMENT_ARTIFACTS_COLLECTION, STORAGE_DELETION_JOBS_COLLECTION, CONVERSATION_ARCHIVE_STATES_COLLECTION, DOCUMENTS_COLLECTION];
const CONVERSATION_DELETE_WRITE = [CONVERSATIONS_COLLECTION, CONVERSATION_MESSAGES_COLLECTION, CONVERSATION_ATTACHMENT_ARTIFACTS_COLLECTION];
type Owner = { teamKey: string; scopeKey: string; userKey: string };
export type GuideTopicSnapshot = { message: ConversationMessage; question: string; recentTopicLabels: string[] };
const parseRows = <T>(rows: unknown[], schema: { parse(value: unknown): T }) => rows.map((row) => schema.parse(withArangoKey(row as Record<string, unknown>)));
const ATTACHMENT_CLAIM_CONFLICT = new Error('Conversation attachment claim conflict.');

export interface ConversationRepository {
  create(value: Conversation, actorKey: string, openingMessage?: ConversationMessage): Promise<Conversation>;
  read(owner: Owner, key: string): Promise<Conversation | null>;
  list(owner: Owner, input: { query?: string; cursor?: { favorite: boolean; updatedAt: string; key: string }; limit: number; favoriteOnly: boolean }): Promise<Conversation[]>;
  update(owner: Owner, key: string, patch: { name?: string; isFavorite?: boolean; updatedAt: string }): Promise<Conversation | null>;
  delete(owner: Owner, key: string): Promise<boolean>;
  deleteMessageTurn(owner: Owner, conversationKey: string, messageKey: string, updatedAt: string): Promise<string[] | null>;
  beginTurn(owner: Owner, conversationKey: string, user: ConversationMessage, assistant: ConversationMessage, actorKey?: string, selection?: unknown): Promise<{ state: 'created'; user: ConversationMessage; assistant: ConversationMessage; first: boolean } | { state: 'replay'; user: ConversationMessage; assistant: ConversationMessage; first: boolean } | { state: 'busy' } | { state: 'idempotency-conflict' } | { state: 'attachment-conflict' } | { state: 'guide-selection-conflict' } | null>;
  beginImageTurn(owner: Owner, conversationKey: string, user: ConversationMessage, assistant: ConversationMessage): Promise<{ state: 'created' | 'replay'; user: ConversationMessage; assistant: ConversationMessage } | { state: 'idempotency-conflict' } | null>;
  completeTurn(owner: Owner, conversationKey: string, assistantKey: string, content: string, embedding: number[] | undefined, retrievals: AppSearchRetrieval[], completedAt: string, generatedName?: string, guide?: { mode: 'recommend' | 'explain'; context: unknown }): Promise<{ message: ConversationMessage; nameApplied: boolean } | null>;
  setImageStatusText(owner: Owner, conversationKey: string, assistantKey: string, statusText: string): Promise<ConversationMessage | null>;
  completeImageTurn(owner: Owner, conversationKey: string, assistantKey: string, imageKey: string, summaryText: string, completedAt: string): Promise<ConversationMessage | null>;
  setMessageEmbedding(owner: Owner, conversationKey: string, messageKey: string, embedding: number[]): Promise<boolean>;
  failTurn(owner: Owner, conversationKey: string, assistantKey: string, completedAt: string, fundingRequiredCode?: 'INSUFFICIENT_BALANCE' | 'OUTSTANDING_DEBT'): Promise<boolean>;
  listMessages(owner: Owner, conversationKey: string, cursor: { createdAt: string; key: string } | undefined, limit: number): Promise<ConversationMessage[] | null>;
  latestCompletedMessages(owner: Owner, conversationKey: string, before: string, limit: number): Promise<ConversationMessage[] | null>;
  semanticMessages(owner: Owner, embedding: number[], input: { before: string; excludedKeys: string[]; limit: number }): Promise<Array<{ message: ConversationMessage; similarity: number }>>;
  readArchiveSummary?(owner: Owner, conversationKey: string): Promise<string | null>;
  listPendingImageTurns(): Promise<Array<{ message: ConversationMessage; actorKey: string }>>;
  readArchiveState?(owner: Owner, conversationKey: string): Promise<ConversationArchiveState | null>;
  requestArchiveProjection?(owner: Owner, conversationKey: string, updatedAt: string, actorKey: string): Promise<ConversationArchiveState | null>;
  readGuideTopicSnapshot(owner: Owner, conversationKey: string, assistantKey: string, generation: number): Promise<GuideTopicSnapshot | null>;
  commitGuideTopics(owner: Owner, conversationKey: string, assistantKey: string, generation: number, mode: 'recommend' | 'explain', topics: unknown): Promise<boolean>;
  failGuideTopics(owner: Owner, conversationKey: string, assistantKey: string, generation: number, code: string, fundingCode?: 'INSUFFICIENT_BALANCE' | 'OUTSTANDING_DEBT'): Promise<boolean>;
  listPendingGuideTopics(): Promise<Array<{ message: ConversationMessage; actorKey: string }>>;
  validateGuideTopicSelection(owner: Owner, conversationKey: string, selection: unknown, message: string): Promise<'recommend' | 'explain' | null>;
  applyGeneratedName?(owner: Owner, conversationKey: string, name: string, updatedAt: string): Promise<boolean>;
}

export function createConversationRepository(database: Database = db, transact: TransactionRunner = database === db ? (operation, collections) => withTransaction({ write: collections?.write ?? CONVERSATION_TRANSACTION_WRITE, read: collections?.read, exclusive: collections?.exclusive ?? [] }, (transaction) => operation(transaction)) : (operation) => operation(database)): ConversationRepository {
  const owned = 'conversation.teamKey == @teamKey && conversation.scopeKey == @scopeKey && conversation.userKey == @userKey';
  const replayTurn = async (owner: Owner, conversationKey: string, turnKey: string, requestHash: string) => {
    const cursor = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET existingUser = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "USER" LIMIT 1 RETURN message) LET existingAssistant = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "ASSISTANT" LIMIT 1 RETURN message) FILTER existingUser != null && existingAssistant != null RETURN { existingUser, existingAssistant, first: LENGTH(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.role == "ASSISTANT" && message.status == "COMPLETED" && message.createdAt < existingAssistant.createdAt LIMIT 1 RETURN 1) == 0 }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, turnKey });
    const row = await cursor.next() as { existingUser: Record<string, unknown>; existingAssistant: Record<string, unknown>; first: boolean } | undefined;
    if (!row) return null;
    const user = conversationMessageSchema.parse(withArangoKey(row.existingUser)); const assistant = conversationMessageSchema.parse(withArangoKey(row.existingAssistant));
    return user.requestHash === requestHash && assistant.requestHash === requestHash ? { state: 'replay' as const, user, assistant, first: row.first } : { state: 'idempotency-conflict' as const };
  };
  return {
    async create(value, _actorKey, openingMessage) {
      const parsed = conversationSchema.parse(value);
      const parsedOpening = openingMessage ? conversationMessageSchema.parse(openingMessage) : undefined;
      if (parsedOpening && (parsedOpening.conversationKey !== parsed.key || parsedOpening.teamKey !== parsed.teamKey || parsedOpening.scopeKey !== parsed.scopeKey || parsedOpening.userKey !== parsed.userKey || parsedOpening.role !== 'ASSISTANT' || parsedOpening.status !== 'COMPLETED')) throw new Error('Opening conversation message ownership is invalid.');
      return transact(async (trx) => {
        const cursor = await trx.query('INSERT @value INTO @@collection RETURN NEW', { '@collection': CONVERSATIONS_COLLECTION, value: toArangoDoc(parsed) });
        const created = conversationSchema.parse(withArangoKey(await cursor.next() as Record<string, unknown>));
        if (parsedOpening) await trx.query('INSERT @value INTO @@messages', { '@messages': CONVERSATION_MESSAGES_COLLECTION, value: toArangoDoc(parsedOpening) });
        return created;
      });
    },
    async read(owner, key) { const cursor = await database.query(`FOR conversation IN @@collection FILTER conversation._key == @key && ${owned} LIMIT 1 RETURN conversation`, { '@collection': CONVERSATIONS_COLLECTION, ...owner, key }); const row = await cursor.next(); return row ? conversationSchema.parse(withArangoKey(row as Record<string, unknown>)) : null; },
    async list(owner, input) {
      const cursor = await database.query(`FOR conversation IN @@collection FILTER ${owned} FILTER LENGTH(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.role == "USER" LIMIT 1 RETURN 1) == 1 FILTER !@favoriteOnly || conversation.isFavorite == true FILTER @query == null || CONTAINS(LOWER(conversation.name), @query) FILTER @cursor == null || conversation.isFavorite < @cursor.favorite || (conversation.isFavorite == @cursor.favorite && (conversation.updatedAt < @cursor.updatedAt || (conversation.updatedAt == @cursor.updatedAt && conversation._key > @cursor.key))) SORT conversation.isFavorite DESC, conversation.updatedAt DESC, conversation._key ASC LIMIT @limit RETURN conversation`, { '@collection': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, favoriteOnly: input.favoriteOnly, query: input.query?.toLocaleLowerCase() ?? null, cursor: input.cursor ?? null, limit: input.limit });
      return parseRows(await cursor.all(), conversationSchema);
    },
    async update(owner, key, patch) {
      return transact(async (trx) => {
        const cursor = await trx.query(`FOR conversation IN @@collection FILTER conversation._key == @key && ${owned} UPDATE conversation WITH @patch IN @@collection RETURN NEW`, { '@collection': CONVERSATIONS_COLLECTION, ...owner, key, patch });
        const row = await cursor.next();
        if (!row) return null;
        if (patch.name !== undefined) await trx.query('FOR state IN @@states FILTER state._key == @key && state.teamKey == @teamKey && state.scopeKey == @scopeKey && state.userKey == @userKey UPDATE state WITH { desiredRevision: state.desiredRevision + 1, updatedAt: @updatedAt } IN @@states', { '@states': CONVERSATION_ARCHIVE_STATES_COLLECTION, ...owner, key, updatedAt: patch.updatedAt });
        return conversationSchema.parse(withArangoKey(row as Record<string, unknown>));
      });
    },
    async delete(owner, key) {
      const deleted = await transact(async (trx) => {
        const cursor = await trx.query(`LET conversation = DOCUMENT(@@conversations, @key) FILTER conversation != null && ${owned} LET artifacts = (FOR artifact IN @@artifacts FILTER artifact.conversationKey == conversation._key && artifact.teamKey == @teamKey && artifact.scopeKey == @scopeKey && artifact.userKey == @userKey RETURN artifact) LET storageKeys = UNIQUE(FOR artifact IN artifacts FILTER IS_STRING(artifact.stagedStorageKey) && LENGTH(artifact.stagedStorageKey) > 0 RETURN artifact.stagedStorageKey) LET removedArtifacts = (FOR artifact IN artifacts REMOVE artifact IN @@artifacts RETURN 1) LET removedMessages = (FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey REMOVE message IN @@messages RETURN 1) REMOVE conversation IN @@conversations RETURN storageKeys`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, '@artifacts': CONVERSATION_ATTACHMENT_ARTIFACTS_COLLECTION, ...owner, key });
        return await cursor.next() as string[] | undefined;
      }, { write: CONVERSATION_DELETE_WRITE, exclusive: [] });
      if (!deleted) return false;
      if (deleted.length) await database.query('FOR storageKey IN @storageKeys UPSERT { storageKey } INSERT { storageKey, createdAt: @now, status: "pending" } UPDATE {} IN @@storageJobs', { '@storageJobs': STORAGE_DELETION_JOBS_COLLECTION, storageKeys: deleted, now: new Date().toISOString() }).catch((error) => { if (!isArangoUniqueConstraintError(error)) throw error; });
      await database.query('LET state = DOCUMENT(@@states, @key) FILTER state != null && state.userKey == @userKey REMOVE state IN @@states', { '@states': CONVERSATION_ARCHIVE_STATES_COLLECTION, userKey: owner.userKey, key }).catch(() => undefined);
      return true;
    },
    async deleteMessageTurn(owner, conversationKey, messageKey, updatedAt) {
      return transact(async (trx) => {
        const cursor = await trx.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET selected = DOCUMENT(@@messages, @messageKey) FILTER selected != null && selected.conversationKey == conversation._key && selected.teamKey == @teamKey && selected.scopeKey == @scopeKey && selected.userKey == @userKey LET pending = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.turnKey == selected.turnKey && message.status == "PENDING" LIMIT 1 RETURN true) FILTER pending == null LET selectedMessages = (FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.turnKey == selected.turnKey RETURN message) LET selectedKeys = selectedMessages[*]._key LET selectedArtifactKeys = UNIQUE(FLATTEN(selectedMessages[*].imageReferenceArtifactKeys)) LET retainedArtifactKeys = UNIQUE(FLATTEN(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.turnKey != selected.turnKey RETURN message.imageReferenceArtifactKeys || [])) LET artifacts = (FOR artifact IN @@artifacts FILTER artifact.teamKey == @teamKey && artifact.scopeKey == @scopeKey && artifact.userKey == @userKey && artifact.conversationKey == conversation._key && (artifact.userMessageKey IN selectedKeys || artifact._key IN selectedArtifactKeys) && artifact._key NOT IN retainedArtifactKeys RETURN artifact) LET storageKeys = UNIQUE(FOR artifact IN artifacts FILTER IS_STRING(artifact.stagedStorageKey) && LENGTH(artifact.stagedStorageKey) > 0 RETURN artifact.stagedStorageKey) LET queuedStorage = (FOR storageKey IN storageKeys UPSERT { storageKey } INSERT { storageKey, createdAt: @updatedAt, status: "pending" } UPDATE {} IN @@storageJobs RETURN 1) LET removedArtifacts = (FOR artifact IN artifacts REMOVE artifact IN @@artifacts RETURN 1) LET removedArchiveDocuments = (FOR document IN @@documents FILTER document.scopeKey == @scopeKey && document.privateOwnerUserKey == @userKey && document.managedPurpose == "conversation-message" && document.managedOwnerKey IN selectedKeys REMOVE document IN @@documents RETURN 1) LET deletedKeys = (FOR message IN selectedMessages REMOVE message IN @@messages RETURN OLD._key) UPDATE conversation WITH { updatedAt: @updatedAt } IN @@conversations RETURN deletedKeys`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, '@artifacts': CONVERSATION_ATTACHMENT_ARTIFACTS_COLLECTION, '@storageJobs': STORAGE_DELETION_JOBS_COLLECTION, '@documents': DOCUMENTS_COLLECTION, ...owner, conversationKey, messageKey, updatedAt });
        const deletedKeys = await cursor.next() as string[] | undefined;
        return deletedKeys?.length ? deletedKeys : null;
      });
    },
    async beginTurn(owner, conversationKey, user, assistant, actorKey, rawSelection) {
      const validUser = conversationMessageSchema.parse(user), validAssistant = conversationMessageSchema.parse(assistant);
      const selection = rawSelection === undefined ? undefined : guideTopicSelectionSchema.parse(rawSelection);
      if (selection && !z.string().cuid().safeParse(selection.sourceAssistantMessageKey).success) return { state: 'guide-selection-conflict' as const };
      try {
        return await transact(async (trx) => {
           const found = await trx.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET existingUser = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "USER" LIMIT 1 RETURN message) LET existingAssistant = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "ASSISTANT" LIMIT 1 RETURN message) LET active = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.type == "TEXT" && message.role == "ASSISTANT" && message.status == "PENDING" LIMIT 1 RETURN message._key) LET completed = LENGTH(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.type == "TEXT" && message.role == "ASSISTANT" && message.status == "COMPLETED" LIMIT 1 RETURN 1) LET latestAssistant = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.type == "TEXT" && message.role == "ASSISTANT" && message.status == "COMPLETED" SORT message.createdAt DESC, message._key DESC LIMIT 1 RETURN message) LET selectedSource = @selection == null ? null : DOCUMENT(@@messages, @selection.sourceAssistantMessageKey) LET selectedTopic = FIRST(FOR topic IN TO_ARRAY(selectedSource.guideTopics.topics) FILTER @selection != null && topic.key == @selection.topicKey && topic.question == @message LIMIT 1 RETURN topic) LET selectionValid = @selection == null || (selectedSource != null && latestAssistant != null && selectedSource._key == latestAssistant._key && selectedSource.conversationKey == conversation._key && selectedSource.teamKey == @teamKey && selectedSource.scopeKey == @scopeKey && selectedSource.userKey == @userKey && selectedSource.type == "TEXT" && selectedSource.role == "ASSISTANT" && selectedSource.status == "COMPLETED" && selectedSource.guideTopics.status == "READY" && selectedSource.guideTopicMode IN ["recommend", "explain"] && selectedTopic != null) RETURN { existingUser, existingAssistant, active, first: completed == 0, selectionValid, selectedGuideMode: selectionValid && selectedSource != null ? selectedSource.guideTopicMode : null }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, turnKey: validUser.turnKey, selection: selection ?? null, message: validUser.content });
           const existing = await found.next() as { existingUser: Record<string, unknown> | null; existingAssistant: Record<string, unknown> | null; active: string | null; first: boolean; selectionValid: boolean; selectedGuideMode: unknown } | undefined;
          if (!existing) return null;
          if (existing.existingUser || existing.existingAssistant) {
            if (!existing.existingUser || !existing.existingAssistant) return { state: 'idempotency-conflict' as const };
            const replayUser = conversationMessageSchema.parse(withArangoKey(existing.existingUser)), replayAssistant = conversationMessageSchema.parse(withArangoKey(existing.existingAssistant));
            return replayUser.requestHash === validUser.requestHash && replayAssistant.requestHash === validUser.requestHash ? { state: 'replay' as const, user: replayUser, assistant: replayAssistant, first: existing.first } : { state: 'idempotency-conflict' as const };
          }
           if (existing.active) return { state: 'busy' as const };
           if (selection && !existing.selectionValid) return { state: 'guide-selection-conflict' as const };
           const attachmentKeys = validUser.pendingAttachmentKeys ?? [];
           if (attachmentKeys.length) {
             if (!actorKey) return { state: 'attachment-conflict' as const };
              const claimed = await trx.query('FOR artifact IN @@artifacts FILTER artifact._key IN @attachmentKeys && artifact.teamKey == @teamKey && artifact.scopeKey == @scopeKey && artifact.userKey == @userKey && artifact.ownerKey == @actorKey && artifact.conversationKey == @conversationKey && artifact.requestKey == @turnKey && artifact.status == "PREPARED" && artifact.expiresAt > @now UPDATE artifact WITH { status: "CLAIMED", userMessageKey: @userMessageKey, availableAt: @persistenceRecoveryAt } IN @@artifacts RETURN NEW._key', { '@artifacts': CONVERSATION_ATTACHMENT_ARTIFACTS_COLLECTION, ...owner, actorKey, conversationKey, turnKey: validUser.turnKey, attachmentKeys, userMessageKey: validUser.key, now: validUser.createdAt, persistenceRecoveryAt: new Date(new Date(validUser.createdAt).getTime() + CONVERSATION_ATTACHMENT_LEASE_MS).toISOString() });
             if ((await claimed.all()).length !== attachmentKeys.length) throw ATTACHMENT_CLAIM_CONFLICT;
           }
           await trx.query('FOR message IN @@messages FILTER message.conversationKey == @conversationKey && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.type == "TEXT" && message.role == "ASSISTANT" && message.guideTopics.status == "PENDING" UPDATE message WITH { guideTopics: { status: "FAILED" }, guideTopicGeneration: message.guideTopicGeneration + 1, guideTopicFailureCode: "SUPERSEDED" } IN @@messages', { '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey });
           const persistedUser = existing.selectedGuideMode ? conversationMessageSchema.parse({ ...validUser, selectedGuideMode: guideModeSchema.parse(existing.selectedGuideMode) }) : validUser;
           const users = await trx.query('INSERT @user INTO @@messages RETURN NEW', { '@messages': CONVERSATION_MESSAGES_COLLECTION, user: toArangoDoc(persistedUser) });
          const assistants = await trx.query('INSERT @assistant INTO @@messages RETURN NEW', { '@messages': CONVERSATION_MESSAGES_COLLECTION, assistant: toArangoDoc(validAssistant) });
          return { state: 'created' as const, user: conversationMessageSchema.parse(withArangoKey(await users.next() as Record<string, unknown>)), assistant: conversationMessageSchema.parse(withArangoKey(await assistants.next() as Record<string, unknown>)), first: existing.first };
        });
      } catch (error) {
        if (error === ATTACHMENT_CLAIM_CONFLICT) return { state: 'attachment-conflict' as const };
        if (!isArangoUniqueConstraintError(error)) throw error;
        return await replayTurn(owner, conversationKey, validUser.turnKey, validUser.requestHash) ?? { state: 'idempotency-conflict' as const };
      }
    },
    async beginImageTurn(owner, conversationKey, user, assistant) {
      const validUser = conversationMessageSchema.parse(user), validAssistant = conversationMessageSchema.parse(assistant);
      if (validUser.type !== 'IMAGE' || validAssistant.type !== 'IMAGE') throw new Error('Image turn messages are required.');
      try {
        return await transact(async (trx) => {
          const found = await trx.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET existingUser = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "USER" LIMIT 1 RETURN message) LET existingAssistant = FIRST(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.userKey == @userKey && message.turnKey == @turnKey && message.role == "ASSISTANT" LIMIT 1 RETURN message) RETURN { existingUser, existingAssistant }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, turnKey: validUser.turnKey });
          const existing = await found.next() as { existingUser: Record<string, unknown> | null; existingAssistant: Record<string, unknown> | null } | undefined;
          if (!existing) return null;
          if (existing.existingUser || existing.existingAssistant) {
            if (!existing.existingUser || !existing.existingAssistant) return { state: 'idempotency-conflict' as const };
            const replayUser = conversationMessageSchema.parse(withArangoKey(existing.existingUser)), replayAssistant = conversationMessageSchema.parse(withArangoKey(existing.existingAssistant));
            return replayUser.type === 'IMAGE' && replayAssistant.type === 'IMAGE' && replayUser.requestHash === validUser.requestHash && replayAssistant.requestHash === validUser.requestHash ? { state: 'replay' as const, user: replayUser, assistant: replayAssistant } : { state: 'idempotency-conflict' as const };
          }
          const users = await trx.query('INSERT @user INTO @@messages RETURN NEW', { '@messages': CONVERSATION_MESSAGES_COLLECTION, user: toArangoDoc(validUser) });
          const assistants = await trx.query('INSERT @assistant INTO @@messages RETURN NEW', { '@messages': CONVERSATION_MESSAGES_COLLECTION, assistant: toArangoDoc(validAssistant) });
          await trx.query('UPDATE @conversationKey WITH { updatedAt: @updatedAt } IN @@conversations', { '@conversations': CONVERSATIONS_COLLECTION, conversationKey, updatedAt: validAssistant.createdAt });
          return { state: 'created' as const, user: conversationMessageSchema.parse(withArangoKey(await users.next() as Record<string, unknown>)), assistant: conversationMessageSchema.parse(withArangoKey(await assistants.next() as Record<string, unknown>)) };
        });
      } catch (error) {
        if (!isArangoUniqueConstraintError(error)) throw error;
        const replay = await replayTurn(owner, conversationKey, validUser.turnKey, validUser.requestHash);
        return replay?.state === 'replay' && replay.user.type === 'IMAGE' && replay.assistant.type === 'IMAGE' ? { state: 'replay', user: replay.user, assistant: replay.assistant } : replay ? { state: 'idempotency-conflict' } : null;
      }
    },
    async completeTurn(owner, conversationKey, assistantKey, content, embedding, retrievals, completedAt, generatedName, guide) { const validRetrievals = conversationMessageBaseSchema.shape.retrievals.parse(retrievals); const validGuide = guide ? { mode: guideModeSchema.parse(guide.mode), context: guide.context } : null; const cursor = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET message = DOCUMENT(@@messages, @assistantKey) FILTER message != null && message.conversationKey == conversation._key && message.userKey == @userKey && message.type == "TEXT" && message.role == "ASSISTANT" && message.status == "PENDING" LET userTurns = LENGTH(FOR other IN @@messages FILTER other.conversationKey == conversation._key && other.role == "USER" && other.status == "COMPLETED" LIMIT 2 RETURN 1) LET nameApplied = @generatedName != null && conversation.name == @defaultName && userTurns == 1 LET guidePatch = @guide == null ? { guideTopics: { status: "NONE" } } : { guideTopics: { status: "PENDING" }, guideMode: @guide.mode, guideContext: @guide.context, guideTopicGeneration: 1 } LET completed = FIRST(UPDATE message WITH MERGE({ content: @content, retrievals: @retrievals, status: "COMPLETED", completedAt: @completedAt }, guidePatch, @embedding == null ? {} : { embedding: @embedding }) IN @@messages RETURN NEW) UPDATE conversation WITH MERGE({ updatedAt: @completedAt }, nameApplied ? { name: @generatedName } : {}) IN @@conversations RETURN { completed, nameApplied }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, content, embedding: embedding ?? null, retrievals: validRetrievals, completedAt, generatedName: generatedName ?? null, guide: validGuide, defaultName: DEFAULT_CONVERSATION_NAME }); const row = await cursor.next() as { completed: Record<string, unknown>; nameApplied: boolean } | undefined; return row ? { message: conversationMessageSchema.parse(withArangoKey(row.completed)), nameApplied: row.nameApplied } : null; },
    async setImageStatusText(owner, conversationKey, assistantKey, statusText) { const validStatusText = conversationMessageBaseSchema.shape.imageStatusText.unwrap().parse(statusText); const cursor = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET message = DOCUMENT(@@messages, @assistantKey) FILTER message != null && message.conversationKey == conversation._key && message.userKey == @userKey && message.type == "IMAGE" && message.role == "ASSISTANT" UPDATE message WITH { imageStatusText: @statusText } IN @@messages RETURN NEW`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, statusText: validStatusText }); const row = await cursor.next(); return row ? conversationMessageSchema.parse(withArangoKey(row as Record<string, unknown>)) : null; },
    async completeImageTurn(owner, conversationKey, assistantKey, imageKey, summaryText, completedAt) { const validSummary = conversationMessageBaseSchema.shape.imageSummaryText.unwrap().parse(summaryText); const cursor = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET message = DOCUMENT(@@messages, @assistantKey) FILTER message != null && message.conversationKey == conversation._key && message.userKey == @userKey && message.type == "IMAGE" && message.role == "ASSISTANT" && message.status == "PENDING" LET completed = FIRST(UPDATE message WITH { imageKey: @imageKey, imageSummaryText: @summaryText, status: "COMPLETED", completedAt: @completedAt } IN @@messages RETURN NEW) UPDATE conversation WITH { updatedAt: @completedAt } IN @@conversations RETURN completed`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, imageKey, summaryText: validSummary, completedAt }); const row = await cursor.next(); return row ? conversationMessageSchema.parse(withArangoKey(row as Record<string, unknown>)) : null; },
    async setMessageEmbedding(owner, conversationKey, messageKey, embedding) { const vector = currentEmbeddingSchema.parse(embedding); const cursor = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} FOR message IN @@messages FILTER message._key == @messageKey && message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.type == "TEXT" && message.status == "COMPLETED" UPDATE message WITH MERGE({ embedding: @embedding }, @metadata) IN @@messages RETURN true`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, messageKey, embedding: vector, metadata: embeddingMetadata() }); return Boolean(await cursor.next()); },
    async failTurn(owner, conversationKey, assistantKey, completedAt, fundingRequiredCode) { const cursor = await database.query(`LET selected = FIRST(FOR message IN @@messages FILTER message._key == @assistantKey && message.conversationKey == @conversationKey && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.role == "ASSISTANT" && message.status == "PENDING" LIMIT 1 RETURN message) FILTER selected != null FOR message IN @@messages FILTER message._key == selected._key || (@fundingRequiredCode != null && message.userKey == @userKey && message.fundingRequiredCode IN ["INSUFFICIENT_BALANCE", "OUTSTANDING_DEBT"] && message.fundingRequiredAcknowledgedAt == null) SORT message._key == selected._key DESC UPDATE message WITH (message._key == selected._key ? MERGE({ status: "FAILED", completedAt: @completedAt }, @fundingRequiredCode == null ? {} : { fundingRequiredCode: @fundingRequiredCode }) : { fundingRequiredAcknowledgedAt: @completedAt }) IN @@messages RETURN message._key == selected._key`, { '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, completedAt, fundingRequiredCode: fundingRequiredCode ?? null }); return await cursor.next() === true; },
    async listMessages(owner, conversationKey, cursor, limit) { const result = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} RETURN (FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey FILTER @cursor == null || message.createdAt < @cursor.createdAt || (message.createdAt == @cursor.createdAt && message._key < @cursor.key) SORT message.createdAt DESC, message._key DESC LIMIT @limit RETURN message)`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, cursor: cursor ?? null, limit }); const rows = await result.next() as unknown[] | undefined; return rows ? parseRows(rows, conversationMessageSchema).reverse() : null; },
    async latestCompletedMessages(owner, conversationKey, before, limit) { const result = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} RETURN (FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.role IN ["USER", "ASSISTANT"] && message.status == "COMPLETED" && message.createdAt < @before SORT message.createdAt DESC, message.turnKey DESC, message.role ASC, message._key DESC LIMIT @limit RETURN message)`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, before, limit }); const rows = await result.next() as unknown[] | undefined; return rows ? parseRows(rows, conversationMessageSchema).reverse() : null; },
    async semanticMessages(owner, embedding, input) { const vector = currentEmbeddingSchema.parse(embedding); const metadata = embeddingMetadata(); const result = await database.query(`FOR message IN @@messages FILTER message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.type == "TEXT" && message.role IN ["USER", "ASSISTANT"] && message.status == "COMPLETED" && message.createdAt < @before && !POSITION(@excludedKeys, message._key) FILTER IS_ARRAY(message.embedding) && LENGTH(message.embedding) == @dimensions && message.embeddingProvider == @embeddingProvider && message.embeddingModel == @embeddingModel && message.embeddingDimensions == @dimensions LET conversation = DOCUMENT(@@conversations, message.conversationKey) FILTER conversation != null && ${owned} && message.conversationKey == conversation._key LET similarity = COSINE_SIMILARITY(message.embedding, @embedding) FILTER IS_NUMBER(similarity) && similarity >= @minimumSimilarity SORT similarity DESC, message.createdAt DESC, message._key DESC LIMIT @limit RETURN { message, similarity }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, embedding: vector, dimensions: EMBEDDING_DIMENSIONS, embeddingProvider: metadata.embeddingProvider, embeddingModel: metadata.embeddingModel, minimumSimilarity: CONVERSATION_SEMANTIC_MINIMUM_COSINE_SIMILARITY, before: input.before, excludedKeys: input.excludedKeys, limit: Math.min(input.limit, 20) }); const rows = await result.all() as Array<{ message: Record<string, unknown>; similarity: number }>; return rows.map((row) => ({ message: conversationMessageSchema.parse(withArangoKey(row.message)), similarity: row.similarity })); },
    async readArchiveSummary(owner, conversationKey) { const keys = conversationArchiveKeys({ ...owner, conversationKey }); const cursor = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} LET summary = DOCUMENT(@@documents, @summaryKey) FILTER summary != null && summary.scopeKey == @scopeKey && summary.privateOwnerUserKey == @userKey && summary.managedPurpose == "conversation-summary" && summary.managedOwnerKey == conversation._key RETURN summary.content`, { '@conversations': CONVERSATIONS_COLLECTION, '@documents': DOCUMENTS_COLLECTION, ...owner, conversationKey, summaryKey: keys.summaryDocumentKey }); const content = await cursor.next(); return typeof content === 'string' ? z.string().trim().min(1).max(CONVERSATION_ARCHIVE_SUMMARY_MAX_CHARACTERS).parse(content) : null; },
    async listPendingImageTurns() { const result = await database.query(`FOR message IN @@messages FILTER message.type == "IMAGE" && message.role == "ASSISTANT" && message.status == "PENDING" LET conversation = DOCUMENT(@@conversations, message.conversationKey) FILTER conversation != null && conversation.teamKey == message.teamKey && conversation.scopeKey == message.scopeKey && conversation.userKey == message.userKey LET membership = FIRST(FOR actor IN userTeams FILTER actor.teamKey == message.teamKey && actor.userId == message.userKey && actor.status == "active" LIMIT 1 RETURN actor._key) FILTER membership != null RETURN { message, actorKey: membership }`, { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION }); const rows = await result.all() as Array<{ message: Record<string, unknown>; actorKey: string }>; return rows.map((row) => ({ message: conversationMessageSchema.parse(withArangoKey(row.message)), actorKey: row.actorKey })); },
    async readArchiveState(owner, conversationKey) { const cursor = await database.query(`FOR state IN @@states FILTER state._key == @conversationKey && state.teamKey == @teamKey && state.scopeKey == @scopeKey && state.userKey == @userKey LIMIT 1 RETURN state`, { '@states': CONVERSATION_ARCHIVE_STATES_COLLECTION, ...owner, conversationKey }); const row = await cursor.next(); return row ? conversationArchiveStateSchema.parse(withArangoKey(row as Record<string, unknown>)) : null; },
    async requestArchiveProjection(owner, conversationKey, updatedAt, actorKey) { const cursor = await database.query(`LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && ${owned} && conversation.name != @defaultName UPSERT { _key: conversation._key } INSERT { _key: conversation._key, conversationKey: conversation._key, teamKey: conversation.teamKey, scopeKey: conversation.scopeKey, userKey: conversation.userKey, actorKey: @actorKey, desiredRevision: 1, projectedRevision: 0, createdAt: conversation.createdAt, updatedAt: @updatedAt } UPDATE { actorKey: @actorKey, desiredRevision: OLD.desiredRevision + 1, updatedAt: @updatedAt } IN @@states RETURN NEW`, { '@conversations': CONVERSATIONS_COLLECTION, '@states': CONVERSATION_ARCHIVE_STATES_COLLECTION, ...owner, conversationKey, actorKey: z.string().cuid().parse(actorKey), updatedAt, defaultName: DEFAULT_CONVERSATION_NAME }); const row = await cursor.next(); return row ? conversationArchiveStateSchema.parse(withArangoKey(row as Record<string, unknown>)) : null; },
    async readGuideTopicSnapshot(owner, conversationKey, assistantKey, generation) { const cursor = await database.query(`LET assistant = DOCUMENT(@@messages, @assistantKey) FILTER assistant != null && assistant.conversationKey == @conversationKey && assistant.teamKey == @teamKey && assistant.scopeKey == @scopeKey && assistant.userKey == @userKey && assistant.type == "TEXT" && assistant.role == "ASSISTANT" && assistant.status == "COMPLETED" && assistant.guideTopics.status == "PENDING" && assistant.guideTopicGeneration == @generation LET question = FIRST(FOR message IN @@messages FILTER message.conversationKey == @conversationKey && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.turnKey == assistant.turnKey && message.role == "USER" && message.status == "COMPLETED" LIMIT 1 RETURN message.content) FILTER question != null LET recentTopicLabels = (FOR message IN @@messages FILTER message.conversationKey == @conversationKey && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.type == "TEXT" && message.role == "ASSISTANT" && message.status == "COMPLETED" && message.createdAt < assistant.createdAt && message.guideTopics.status == "READY" SORT message.createdAt DESC LIMIT 5 FOR topic IN message.guideTopics.topics LIMIT 15 RETURN topic.label) RETURN { assistant, question, recentTopicLabels }`, { '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, generation }); const row = await cursor.next() as { assistant: Record<string, unknown>; question: string; recentTopicLabels: string[] } | undefined; return row ? { message: conversationMessageSchema.parse(withArangoKey(row.assistant)), question: row.question, recentTopicLabels: row.recentTopicLabels } : null; },
    async commitGuideTopics(owner, conversationKey, assistantKey, generation, mode, topics) { const parsedTopics = guideTopicsSchema.parse({ status: 'READY', topics }); const cursor = await database.query('FOR message IN @@messages FILTER message._key == @assistantKey && message.conversationKey == @conversationKey && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.type == "TEXT" && message.role == "ASSISTANT" && message.status == "COMPLETED" && message.guideTopics.status == "PENDING" && message.guideTopicGeneration == @generation UPDATE message WITH { guideTopics: @guideTopics, guideTopicMode: @mode, guideTopicFailureCode: null, guideTopicFundingRequiredCode: null } IN @@messages OPTIONS { keepNull: false } RETURN true', { '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, generation, mode: guideModeSchema.parse(mode), guideTopics: parsedTopics }); return await cursor.next() === true; },
    async failGuideTopics(owner, conversationKey, assistantKey, generation, code, fundingCode) { const cursor = await database.query('FOR message IN @@messages FILTER message._key == @assistantKey && message.conversationKey == @conversationKey && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.type == "TEXT" && message.role == "ASSISTANT" && message.status == "COMPLETED" && message.guideTopics.status == "PENDING" && message.guideTopicGeneration == @generation UPDATE message WITH MERGE({ guideTopics: { status: "FAILED" }, guideTopicFailureCode: @code }, @fundingCode == null ? {} : { guideTopicFundingRequiredCode: @fundingCode }) IN @@messages RETURN true', { '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, assistantKey, generation, code: z.string().trim().min(1).max(100).parse(code), fundingCode: fundingCode ?? null }); return await cursor.next() === true; },
    async listPendingGuideTopics() { const cursor = await database.query('FOR message IN @@messages FILTER message.type == "TEXT" && message.role == "ASSISTANT" && message.status == "COMPLETED" && message.guideTopics.status == "PENDING" && IS_NUMBER(message.guideTopicGeneration) LET conversation = DOCUMENT(@@conversations, message.conversationKey) FILTER conversation != null && conversation.teamKey == message.teamKey && conversation.scopeKey == message.scopeKey && conversation.userKey == message.userKey LET membership = FIRST(FOR actor IN userTeams FILTER actor.teamKey == message.teamKey && actor.userId == message.userKey && actor.status == "active" LIMIT 1 RETURN actor._key) FILTER membership != null RETURN { message, actorKey: membership }', { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION }); const rows = await cursor.all() as Array<{ message: Record<string, unknown>; actorKey: string }>; return rows.map((row) => ({ message: conversationMessageSchema.parse(withArangoKey(row.message)), actorKey: row.actorKey })); },
    async validateGuideTopicSelection(owner, conversationKey, rawSelection, message) {
      const selection = guideTopicSelectionSchema.parse(rawSelection);
      const content = conversationMessageBaseSchema.shape.content.parse(message);
      const cursor = await database.query('LET conversation = DOCUMENT(@@conversations, @conversationKey) FILTER conversation != null && conversation.teamKey == @teamKey && conversation.scopeKey == @scopeKey && conversation.userKey == @userKey LET source = DOCUMENT(@@messages, @sourceAssistantMessageKey) FILTER source != null && source.conversationKey == conversation._key && source.teamKey == @teamKey && source.scopeKey == @scopeKey && source.userKey == @userKey && source.type == "TEXT" && source.role == "ASSISTANT" && source.status == "COMPLETED" && source.guideTopics.status == "READY" LET topic = FIRST(FOR item IN source.guideTopics.topics FILTER item.key == @topicKey && item.question == @message LIMIT 1 RETURN item) FILTER topic != null RETURN source.guideTopicMode IN ["recommend", "explain"] ? source.guideTopicMode : REGEX_TEST(topic.key, "(^|\\.)explain(\\.|$)") ? "explain" : REGEX_TEST(topic.key, "(^|\\.)recommend(\\.|$)") ? "recommend" : null', { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, sourceAssistantMessageKey: selection.sourceAssistantMessageKey, topicKey: selection.topicKey, message: content });
      const mode = await cursor.next();
      return mode === 'recommend' || mode === 'explain' ? mode : null;
    },
    async applyGeneratedName(owner, conversationKey, name, updatedAt) {
      const validName = conversationSchema.shape.name.parse(name);
      const cursor = await database.query('FOR conversation IN @@conversations FILTER conversation._key == @conversationKey && conversation.teamKey == @teamKey && conversation.scopeKey == @scopeKey && conversation.userKey == @userKey && conversation.name == @defaultName LET userTurns = LENGTH(FOR message IN @@messages FILTER message.conversationKey == conversation._key && message.teamKey == @teamKey && message.scopeKey == @scopeKey && message.userKey == @userKey && message.role == "USER" && message.status == "COMPLETED" LIMIT 2 RETURN 1) FILTER userTurns == 1 UPDATE conversation WITH { name: @name, updatedAt: @updatedAt } IN @@conversations RETURN true', { '@conversations': CONVERSATIONS_COLLECTION, '@messages': CONVERSATION_MESSAGES_COLLECTION, ...owner, conversationKey, defaultName: 'New chat', name: validName, updatedAt });
      return await cursor.next() === true;
    },
  };
}

let repository: ConversationRepository | undefined;
export const getDefaultConversationRepository = () => repository ??= createConversationRepository();
