import { PROVIDER_REGISTRY } from './registry';

export {
  PROVIDER_SLUGS,
  providerSlugSchema,
  providerIdSchema,
  providerExecuteRequestSchema,
  chatInputSchema,
  chatMessageSchema,
  chatToolSchema,
  chatOutputSchema,
  imageGenerateInputSchema,
  imageOutputSchema,
  generatedImageMimeTypeSchema,
  imageCaptionInputSchema,
  imageCaptionOutputSchema,
  visualIdentityDescriptionInputSchema,
  visualIdentityDescriptionOutputSchema,
  embeddingInputSchema,
  resolveRequestSignal,
  type ProviderId,
  type ProviderSlug,
  type ProviderAdapter,
  type ProviderFactory,
  type ProviderExecuteRequest,
  type ProviderExecuteResponse,
  type ProviderStreamChunk,
  type ProviderEmbedRequest,
  type ProviderEmbedResponse,
  type ProviderHealth,
  type ChatInput,
  type ChatMessage,
  type ChatTool,
  type ChatOutput,
  type NormalizedToolCall,
  type ImageGenerateInput,
  type ImageOutput,
  type ImageCaptionInput,
  type ImageCaptionOutput,
  type VisualIdentityDescriptionInput,
  type VisualIdentityDescriptionOutput,
  type EmbeddingInput,
  type EmbeddingOutput,
} from './types';
export {
  ProviderError,
  isProviderError,
  normalizeProviderError,
  providerErrorCodeForStatus,
  PROVIDER_ERROR_CODES,
  PRE_EXECUTION_ERROR_CODES,
  type ProviderErrorCode,
} from './errors';
export {
  createGoogleVertexProvider,
  googleVertexCredentialsSchema,
  googleVertexProviderConfigSchema,
  googleVertexProviderFactory,
  type GoogleVertexCredentials,
  type GoogleVertexProviderConfig,
} from './google-vertex';
export {
  createAwsPollyProvider,
  awsPollyProviderConfigSchema,
  awsPollyProviderFactory,
  buildPollySpeechSsml,
  splitPollySpeechText,
  extractPollyMp3Frames,
  type AwsPollyProviderConfig,
} from './aws-polly';
export {
  createAzureAIFoundryProvider,
  azureAIFoundryCredentialsSchema,
  azureAIFoundryProviderConfigSchema,
  azureAIFoundryProviderFactory,
  type AzureAIFoundryCredentials,
  type AzureAIFoundryProviderConfig,
} from './azure-ai-foundry';
export { PROVIDER_REGISTRY, MODEL_REGISTRY, MODEL_IDS, modelIdSchema, getModel, getExternalModelId, isProviderAvailable, createRegisteredProviderAdapter, assertProviderRegistryIntegrity, type ModelId, type ProviderEnvironment, type ProviderRegistration } from './registry';
