export const BOOK_GENERATION_LEASE_MS = 2 * 60_000;
export const BOOK_GENERATION_RENEW_MS = 30_000;
export const BOOK_GENERATION_RETRY_ATTEMPTS = 8;
export const BOOK_GENERATION_RETRY_DELAY_MS = 30_000;
