import { describe, expect, test } from 'bun:test';
import sharp from 'sharp';
import { EMBEDDING_DIMENSIONS } from '@/lib/embeddings';
import { newId } from '@/lib/ids';
import { BOOK_CHAPTER_WORD_MAX, BOOK_CHAPTER_WORD_MIN } from '@/lib/db/book-chapters.node';
import { createBookRuntime } from './runtime';

const prose = (word: string) => Array(BOOK_CHAPTER_WORD_MIN).fill(word).join(' ');
const timestamp = '2026-08-28T12:00:00.000Z';
const embedding = () => Array(EMBEDDING_DIMENSIONS).fill(0.1);

describe('book runtime progressive generation', () => {
  test('persists one coherent plan, batches summaries once, and starts each audio after its parallel text', async () => {
    const scopeKey = newId(); const bookKey = newId(); const userKey = newId();
    const input = { organizationKey: 'organization', scopeKey, topic: 'Decision making', goal: 'Decide well', currentKnowledge: 'Basics', writingTone: 'Clear', chapterCount: 10 as const, language: 'English', archiveDocumentKeys: [], narratorVoiceKey: 'clear' as const, narrationPace: 1, chapterImages: false };
    let book: any = { key: bookKey, scopeKey, title: input.topic, description: input.goal, goal: input.goal, audience: input.currentKnowledge, outcome: input.goal, language: input.language, generationBriefFingerprint: 'a'.repeat(64), generationStage: 'accepted', generationCompletedUnits: 0, generationTotalUnits: 33, generationAttempt: 0, estimatedMinutes: 0, chapterCount: 10, status: 'queued', embedding: embedding(), createdAt: timestamp, updatedAt: timestamp };
    let chapters: any[] = []; let summaryCalls = 0; let writingCalls = 0; let audioCalls = 0; let imageCalls = 0; let inspectionCalls = 0; let titlesNotified = false; let coverPrompt = ''; let releaseCover!: () => void; const coverGate = new Promise<void>((resolve) => { releaseCover = resolve; });
    const png = new Uint8Array(await sharp({ create: { width: 2, height: 2, channels: 4, background: '#111827' } }).png().toBuffer());
    const repository: any = {
      detail: async () => ({ book, chapters: chapters.map((chapter) => ({ chapter, progress: null })) }), sources: async () => [], pendingExtension: async () => null, isCancellationRequested: async () => false,
      updateBook: async (_context: unknown, _key: string, patch: any) => { book = { ...book, ...patch }; return book; },
      updateChapter: async (_context: unknown, key: string, patch: any) => { const chapter = chapters.find((value) => value.key === key); Object.assign(chapter, patch); return { ...chapter }; },
      replaceChapters: async (_context: unknown, _key: string, values: any[], _contexts: any[], patch: any) => { chapters = values; book = { ...book, ...patch }; },
      advanceGeneration: async () => {}, reconcileGeneration: async () => {}, enqueueUnreferencedStorage: async () => {},
      publishArchive: async (_context: unknown, _key: string, values: any[]) => { book.archiveFolderKey = newId(); for (const value of values) chapters.find((chapter) => chapter.key === value.chapterKey).archiveDocumentKey = value.document.key; },
      publishChapters: async (_context: unknown, _key: string, count: number) => { expect(count).toBe(10); book.status = 'ready'; }, ensureGalleryExportCollection: async () => ({ collectionKey: newId(), ownerKey: newId() }), linkGalleryExportImages: async () => {},
    };
    const runtime = createBookRuntime({ repository, ask: async (request: any) => {
      expect(request.systemPrompt).toContain('Treat the requested topic and goal as the primary brief');
      expect(request.systemPrompt).toContain('Ignore any context that is irrelevant, nonsensical, contradictory, low quality, or otherwise unhelpful');
      expect(request.systemPrompt).toContain('simple, friendly, conversational language');
      if (request.systemPrompt.startsWith('Design one coherent')) { expect(request.responseFormat).toMatchObject({ name: 'book_generation_plan', schema: { type: 'object', required: ['title', 'description', 'outcome', 'summary', 'chapters'] } }); expect(request.responseFormat.schema.properties.chapters).not.toHaveProperty('minItems'); expect(request.responseFormat.schema.properties.chapters.items.properties.targetWordMin).not.toHaveProperty('const'); return JSON.stringify({ title: 'Clear Decisions', description: 'A complete guide to practical decisions.', outcome: input.goal, summary: 'A coherent progression.', chapters: Array.from({ length: 10 }, (_, index) => ({ title: `Chapter ${index + 1}`, objective: `Objective ${index + 1}`, visualPlan: `Visual ${index + 1}`, evidenceKeyPoints: ['One', 'Two'], topics: ['Decisions'], priorTransition: `Prior ${index + 1}`, nextTransition: `Next ${index + 1}`, repetitionBoundaries: ['Avoid repetition'], targetWordMin: BOOK_CHAPTER_WORD_MIN, targetWordMax: BOOK_CHAPTER_WORD_MAX })) }); }
      if (request.systemPrompt.startsWith('Write one concise summary')) { summaryCalls += 1; expect(titlesNotified).toBe(true); expect(request.responseFormat).toMatchObject({ name: 'book_chapter_summaries', schema: { type: 'object', required: ['chapters'] } }); const data = JSON.parse(request.messages[0].content[0].text); const summaries = data.requestedChapters.map((chapter: any) => ({ key: chapter.key, position: chapter.position, title: chapter.title, description: `Concise distinct summary ${chapter.position}`, promptGuidance: `Develop objective ${chapter.position} with one concrete example and a clear transition to the adjacent chapter.` })); return JSON.stringify(summaryCalls === 1 ? summaries : { chapters: summaries }); }
      if (request.systemPrompt.startsWith(`Write ${BOOK_CHAPTER_WORD_MIN}-${BOOK_CHAPTER_WORD_MAX} words`)) { writingCalls += 1; expect(request.systemPrompt).toContain('natural paragraphs of roughly 40 words'); return prose(`chapter${writingCalls}`); }
      throw new Error(`Unexpected prompt: ${request.systemPrompt}`);
    }, images: { generateRaw: async ({ prompt }: any) => { imageCalls += 1; coverPrompt = prompt; await coverGate; return { output: { images: [{ base64: Buffer.from(png).toString('base64'), mimeType: 'image/png' }] }, durationMs: 1, costUsd: null }; } }, inspectArtwork: async () => { inspectionCalls += 1; return inspectionCalls === 1 ? { compliant: false, reason: 'visible writing' } : { compliant: true, reason: 'compliant' }; }, appAudio: { generateForTarget: async (target: any, options: any) => { const chapter = chapters.find((value) => target.storageKey.includes(`chapter-${value.position}-`)); expect(chapter.content).toContain('\n\n'); expect(target.text).not.toContain('\n'); expect(target.text).toBe(chapter.content.replace(/\s+/g, ' ').trim()); audioCalls += 1; const persisted = await options.persist({ storageKey: target.storageKey, durationSeconds: 300 }); return { target: persisted, storageKey: target.storageKey, durationSeconds: 300 }; } }, storage: { upload: async ({ key }) => ({ storageKey: key }), download: async () => ({ bytes: png, mimeType: 'image/png' }), delete: async () => {}, copy: async ({ destinationKey }) => ({ storageKey: destinationKey }) }, embed: async () => embedding(), processImageBatch: async (values: readonly any[]) => values.map(({ imageKey }) => ({ key: imageKey })) as any, publishChanged: async () => { if (chapters.length === 10) titlesNotified = true; }, publishContentChanged: async () => {}, publishGalleryChanged: async () => {}, now: () => timestamp });
    const writing = runtime.write(bookKey, input, { organizationKey: input.organizationKey, scopeKey, userKey, generationLeaseToken: 'lease' });
    while (audioCalls < 10) await new Promise((resolve) => setTimeout(resolve, 1));
    expect(book.coverStorageKey).toBeUndefined(); expect(summaryCalls).toBe(2); expect(writingCalls).toBe(10); releaseCover(); await writing;
    expect(book.status).toBe('ready'); expect(chapters.every((chapter) => chapter.status === 'audio-ready' && chapter.description.startsWith('Concise distinct summary'))).toBe(true); expect(imageCalls).toBe(2); expect(inspectionCalls).toBe(2); expect(coverPrompt).toContain(input.topic); expect(coverPrompt).toContain('zero words, letters'); expect(coverPrompt).toContain('zero humans, faces'); expect(coverPrompt).toContain('full-bleed editorial book-cover'); expect(coverPrompt).toContain('recognizable, literal real-world scene'); expect(coverPrompt).toContain('Do not use a predominantly black'); expect(coverPrompt).toContain('deliberately cropped by the frame'); expect(coverPrompt).toContain('Do not render a small or fully visible object in the center'); expect(coverPrompt).not.toContain('Black should dominate'); expect(coverPrompt).not.toContain('keeping it fully visible'); expect(coverPrompt).not.toContain('plants, fungi'); expect(coverPrompt).not.toContain('Vorinthex');
  });

  test('resumes a durable extension and mutates only its progressively appended suffix', async () => {
    const scopeKey = newId(); const bookKey = newId(); const userKey = newId(); const extensionKey = newId();
    const input = { organizationKey: 'organization', scopeKey, topic: 'Thinking', goal: 'Think well', currentKnowledge: 'Basics', writingTone: 'Clear', chapterCount: 10 as const, language: 'English', archiveDocumentKeys: [], narratorVoiceKey: 'clear' as const, narrationPace: 1, chapterImages: true };
    let book: any = { key: bookKey, scopeKey, title: 'Thinking', description: 'The full existing book description.', goal: input.goal, audience: input.currentKnowledge, outcome: input.goal, language: input.language, generationBriefFingerprint: 'b'.repeat(64), generationInput: { ...input, organizationKey: undefined, scopeKey: undefined }, generationOwnerKey: userKey, generationStage: 'outline', generationCompletedUnits: 0, generationTotalUnits: 5, generationAttempt: 0, estimatedMinutes: 10, chapterCount: 3, status: 'queued', coverStorageKey: 'cover.png', coverInputHash: 'c'.repeat(64), embedding: embedding(), activeExtensionKey: extensionKey, createdAt: timestamp, updatedAt: timestamp };
    const existing = Array.from({ length: 2 }, (_, index) => ({ key: newId(), scopeKey, bookKey, position: index + 1, title: `Existing ${index + 1}`, description: `Existing summary ${index + 1}`, objective: `Existing objective ${index + 1}`, evidenceKeyPoints: ['Existing'], topics: ['Thinking'], priorTransition: 'Prior', nextTransition: 'Next', repetitionBoundaries: ['Boundary'], targetWordMin: BOOK_CHAPTER_WORD_MIN, targetWordMax: BOOK_CHAPTER_WORD_MAX, content: `existing content ${index + 1}`, status: 'audio-ready', audioStorageKey: `existing-${index + 1}.mp3`, audioInputHash: 'd'.repeat(64), audioDurationSeconds: 300, imageStorageKey: `existing-${index + 1}.png`, imageInputHash: 'e'.repeat(64), archiveDocumentKey: newId(), embedding: embedding(), createdAt: timestamp, updatedAt: timestamp }));
    const chapters: any[] = [...existing]; let appendNotifications = 0; let extensionStatus = 'pending'; let imagePrompt = ''; let publishedCount = 0;
    const extension = { key: extensionKey, scopeKey, bookKey, userKey, requestKey: 'request', requestFingerprint: 'f'.repeat(64), titles: ['New Horizon'], baseChapterCount: 2, targetChapterCount: 3, status: 'pending', createdAt: timestamp, updatedAt: timestamp };
    const png = new Uint8Array(await sharp({ create: { width: 2, height: 2, channels: 4, background: '#111827' } }).png().toBuffer());
    const repository: any = { detail: async () => ({ book, chapters: chapters.map((chapter) => ({ chapter, progress: null })) }), sources: async () => [], pendingExtension: async () => extensionStatus === 'complete' ? null : { ...extension, status: extensionStatus }, updateExtension: async (_context: unknown, _key: string, status: string) => { extensionStatus = status; return { ...extension, status }; }, isCancellationRequested: async () => false, updateBook: async (_context: unknown, _key: string, patch: any) => { book = { ...book, ...patch }; return book; }, updateChapter: async (_context: unknown, key: string, patch: any) => { const chapter = chapters.find((value) => value.key === key); Object.assign(chapter, patch); return { ...chapter }; }, appendChapter: async (_context: unknown, _key: string, chapter: any) => { chapters.push(chapter); }, advanceGeneration: async () => {}, reconcileGeneration: async () => {}, enqueueUnreferencedStorage: async () => {}, publishArchive: async (_context: unknown, _key: string, values: any[]) => { book.archiveFolderKey = newId(); for (const value of values) chapters.find((chapter) => chapter.key === value.chapterKey).archiveDocumentKey = value.document.key; }, publishChapters: async (_context: unknown, _key: string, count: number) => { publishedCount = count; book.status = 'ready'; extensionStatus = 'complete'; }, ensureGalleryExportCollection: async () => ({ collectionKey: newId(), ownerKey: newId() }), linkGalleryExportImages: async () => {} };
    const runtime = createBookRuntime({ repository, ask: async (request: any) => { const data = JSON.parse(request.messages[0].content[0].text); if (request.systemPrompt.startsWith('Write one concise summary')) { expect(data.book.description).toBe(book.description); expect(data.allOrderedChapters.slice(0, 2).map((chapter: any) => chapter.description)).toEqual(['Existing summary 1', 'Existing summary 2']); const chapter = data.requestedChapters[0]; return JSON.stringify({ chapters: [{ key: chapter.key, position: chapter.position, title: chapter.title, description: 'A concise continuation summary.', promptGuidance: 'Build directly on every existing chapter and advance the argument with a fresh practical synthesis.' }] }); } return prose('extension'); }, images: { generateRaw: async ({ prompt }: any) => { imagePrompt = prompt; return { output: { images: [{ base64: Buffer.from(png).toString('base64'), mimeType: 'image/png' }] }, durationMs: 1, costUsd: null }; } }, inspectArtwork: async () => ({ compliant: true, reason: 'compliant' }), appAudio: { generateForTarget: async (target: any, options: any) => { const persisted = await options.persist({ storageKey: target.storageKey, durationSeconds: 300 }); return { target: persisted, storageKey: target.storageKey, durationSeconds: 300 }; } }, storage: { upload: async ({ key }) => ({ storageKey: key }), download: async () => ({ bytes: png, mimeType: 'image/png' }), delete: async () => {}, copy: async ({ destinationKey }) => ({ storageKey: destinationKey }) }, embed: async () => embedding(), processImageBatch: async (values: readonly any[]) => values.map(({ imageKey }) => ({ key: imageKey })) as any, publishChanged: async () => { if (chapters.length === 3 && !chapters[2]!.summaryInputHash) appendNotifications += 1; }, publishContentChanged: async () => {}, publishGalleryChanged: async () => {}, now: () => timestamp });
    await runtime.write(bookKey, input, { organizationKey: input.organizationKey, scopeKey, userKey, generationLeaseToken: 'lease' });
    expect(appendNotifications).toBeGreaterThan(0); expect(chapters).toHaveLength(3); expect(chapters.slice(0, 2)).toEqual(existing); expect(chapters[2]).toMatchObject({ title: 'New Horizon', status: 'audio-ready' }); expect(imagePrompt).toContain('New Horizon'); expect(imagePrompt).toContain('zero words, letters'); expect(imagePrompt).toContain('zero humans, faces'); expect(imagePrompt).toContain('full-bleed editorial chapter-cover'); expect(imagePrompt).toContain('recognizable real-world scene'); expect(imagePrompt).toContain('ignore any abstract, symbolic, futuristic, or dark direction'); expect(imagePrompt).toContain('Do not use a predominantly black'); expect(imagePrompt).toContain('deliberately cropped by the frame'); expect(imagePrompt).toContain('Do not render a small or fully visible object in the center'); expect(imagePrompt).not.toContain('Black should dominate'); expect(imagePrompt).not.toContain('keeping it fully visible'); expect(imagePrompt).not.toContain('plants, fungi'); expect(imagePrompt).not.toContain('"title"'); expect(imagePrompt).not.toContain('Vorinthex'); expect(imagePrompt).not.toContain(chapters[2].content); expect(publishedCount).toBe(3); expect(extensionStatus).toBe('complete');
  });
});
