import { createHash } from 'node:crypto';
import { z } from 'zod';
import { buildEmbeddingText } from '@/lib/db/base';
import { bookSchema, type Book } from '@/lib/db/books.node';
import { bookContextSchema } from '@/lib/db/book-contexts.node';
import { bookChapterSchema, bookChaptersEmbeddingFields, type BookChapter } from '@/lib/db/book-chapters.node';
import { bookSourceSchema, bookSourcesEmbeddingFields, type BookSource } from '@/lib/db/book-sources.node';
import { chapterContextSchema, chapterContextsEmbeddingFields, type ChapterContext } from '@/lib/db/chapter-contexts.node';
import { currentEmbeddingSchema, EMBEDDING_DIMENSIONS } from '@/lib/embeddings';
import { newId } from '@/lib/ids';
import { documentStorage, type DocumentObjectStorage } from '@/lib/ai/document-processing/storage';
import { executeAction, executeAsk } from '@/lib/ai/router';
import type { ChatOutput, ImageOutput } from '@/lib/ai/providers';
import { canonicalizeImageToPng } from '@/lib/ai/image-processing';
import { webSearchOutputSchema } from '@/lib/ai/actions/web-search';
import { speechOutputSchema, type SpeechInput } from '@/lib/ai/actions/generate-speech';
import type { BookGenerator } from './service';
import { createBookRepository, type BookRepository } from './repository';

const ideaSchema = z.object({ title: z.string().trim().min(1), subtitle: z.string().trim().min(1).optional(), description: z.string().trim().min(1), outcome: z.string().trim().min(1), summary: z.string().trim().min(1) }).strict();
const words = (value: string) => value.trim().split(/\s+/).filter(Boolean).length;
const chapterBriefSchema = z.object({
  title: z.string().trim().min(1),
  description: z.string().trim().refine((value) => words(value) >= 80 && words(value) <= 120, 'Chapter briefs must contain 80-120 words.'),
  objective: z.string().trim().min(1), evidenceKeyPoints: z.array(z.string().trim().min(1)).min(2).max(12), topics: z.array(z.string().trim().min(1)).min(1).max(20),
  priorTransition: z.string().trim().min(1), nextTransition: z.string().trim().min(1), repetitionBoundaries: z.array(z.string().trim().min(1)).min(1).max(12),
  targetWordMin: z.literal(500), targetWordMax: z.literal(750),
}).strict();
const outlineSchema = z.object({ chapters: z.array(chapterBriefSchema) }).strict();
type Ask = (input: Record<string, unknown>, organizationKey: string, signal?: AbortSignal) => Promise<string>;
type Media = (prompt: string, organizationKey: string, signal?: AbortSignal) => Promise<{ bytes: Uint8Array; mimeType: string } | null>;

function json<T>(schema: z.ZodType<T>, value: string): T { return schema.parse(JSON.parse(value.trim().replace(/^```(?:json)?\s*/i, '').replace(/\s*```$/, ''))); }
function hash(value: unknown) { return createHash('sha256').update(typeof value === 'string' ? value : JSON.stringify(value)).digest('hex'); }
async function boundedMap<T>(values: readonly T[], concurrency: number, run: (value: T, index: number) => Promise<void>) { let next = 0; await Promise.all(Array.from({ length: Math.min(concurrency, values.length) }, async () => { while (true) { const index = next++; if (index >= values.length) return; await run(values[index]!, index); } })); }
function sourceEvidence(sources: readonly BookSource[]) { let remaining = 24_000; return sources.flatMap((source) => { if (remaining <= 0) return []; const content = source.content.slice(0, Math.min(4_000, remaining)); remaining -= content.length; return [{ title: source.title, type: source.sourceType, content, contentHash: source.contentHash, ...(source.url ? { url: source.url } : {}) }]; }); }
function stableChapterBrief(chapter: BookChapter) { const { title, description, objective, evidenceKeyPoints, topics, priorTransition, nextTransition, repetitionBoundaries, targetWordMin, targetWordMax, position } = chapter; return { title, description, objective, evidenceKeyPoints, topics, priorTransition, nextTransition, repetitionBoundaries, targetWordMin, targetWordMax, position }; }

export interface BookRuntimeDependencies {
  repository?: BookRepository; ask?: Ask; cover?: Media; art?: Media;
  research?: (prompt: string, organizationKey: string, signal?: AbortSignal) => Promise<z.output<typeof webSearchOutputSchema>>;
  speech?: (input: SpeechInput, organizationKey: string, signal?: AbortSignal) => Promise<{ bytes: Uint8Array; mimeType: string; durationSeconds?: number }>;
  storage?: DocumentObjectStorage; embed?: (text: string, organizationKey: string, signal?: AbortSignal) => Promise<number[]>;
  publishChanged?: (scopeKey: string) => Promise<unknown>; publishContentChanged?: (scopeKey: string) => Promise<unknown>; id?: () => string; now?: () => string;
}

export function createBookRuntime(options: BookRuntimeDependencies = {}): BookGenerator {
  const repository = options.repository ?? createBookRepository(); const storage = options.storage ?? documentStorage; const id = options.id ?? newId; const now = options.now ?? (() => new Date().toISOString());
  const ask = options.ask ?? (async (input, organizationKey, signal) => (await executeAsk<ChatOutput>(organizationKey, input as never, { signal })).output.text);
  const embed = options.embed ?? (async (text, organizationKey, signal) => (await executeAction<{ text: string }, { embedding: number[] }>({ mode: 'auto', organizationKey, actionSlug: 'embed' }, { text }, { signal })).output.embedding);
  const image = options.cover ?? (async (prompt, organizationKey, signal) => { try { const output = (await executeAction<Record<string, unknown>, ImageOutput>({ mode: 'auto', organizationKey, actionSlug: 'generate-image' }, { prompt, count: 1, size: '1024x1024' }, { signal })).output.images[0]; return output ? { bytes: Buffer.from(output.base64, 'base64'), mimeType: output.mimeType } : null; } catch { return null; } });
  const speech = options.speech ?? (async (input, organizationKey, signal) => { const output = speechOutputSchema.parse((await executeAction({ mode: 'auto', organizationKey, actionSlug: 'generate-speech' }, input, { signal })).output); return { bytes: Buffer.from(output.base64, 'base64'), mimeType: output.mimeType, durationSeconds: output.durationSeconds }; });
  const research = options.research ?? (async (researchPrompt, organizationKey, signal) => webSearchOutputSchema.parse((await executeAction({ mode: 'auto', organizationKey, actionSlug: 'web-search' }, { mode: 'deep', prompt: researchPrompt }, { signal })).output));
  const notify = options.publishChanged ?? (async (scopeKey) => (await import('@/api/events')).publishScopeEvent(scopeKey, 'book.changed'));
  const notifyContent = options.publishContentChanged ?? (async (scopeKey) => (await import('@/api/events')).publishScopeEvent(scopeKey, 'content.changed'));
  const pngMedia = async (media: Awaited<ReturnType<Media>>) => media == null || media.mimeType === 'image/png' ? media : { bytes: (await canonicalizeImageToPng(media.bytes)).bytes, mimeType: 'image/png' };
  const vector = async (fields: readonly string[], value: Record<string, unknown>, organizationKey: string, signal?: AbortSignal) => currentEmbeddingSchema.parse(await embed(buildEmbeddingText(fields, value)!, organizationKey, signal));
  const prompt = (systemPrompt: string, text: string, maxTokens = 8_000) => ({ systemPrompt, messages: [{ role: 'user', content: [{ type: 'text', text }] }], options: { temperature: 0.3, maxTokens } });
  const check = async (context: Parameters<BookRepository['isCancellationRequested']>[0], bookKey: string) => { if (context.signal?.aborted || await repository.isCancellationRequested(context, bookKey)) throw new Error('Book generation cancelled.'); };
  return {
    async create(input, context) {
      await repository.authorize(context, true); const timestamp = now(); const bookKey = id(); const sourceDocuments = await repository.sourceDocuments(context, input.archiveDocumentKeys);
      const generationInput = { topic: input.topic, goal: input.goal, currentKnowledge: input.currentKnowledge, writingTone: input.writingTone, chapterCount: input.chapterCount, language: input.language, archiveDocumentKeys: input.archiveDocumentKeys, narratorVoiceKey: input.narratorVoiceKey, narrationPace: input.narrationPace, chapterImages: input.chapterImages, additionalInstructions: input.additionalInstructions };
      const total = input.chapterCount * (input.chapterImages ? 4 : 3) + 4;
      const draft = { key: bookKey, scopeKey: input.scopeKey, generationRequestKey: input.generationRequestKey, generationBriefFingerprint: input.generationBriefFingerprint, generationInput, generationOwnerKey: context.userKey, title: input.topic, description: `Personalized audiobook about ${input.topic}`, goal: input.goal, audience: input.currentKnowledge, outcome: input.goal, language: input.language, narratorVoiceKey: input.narratorVoiceKey, narrationPace: input.narrationPace, status: 'queued' as const, generationStage: 'accepted' as const, generationCompletedUnits: 0, generationTotalUnits: total, generationAttempt: 0, estimatedMinutes: 0, chapterCount: input.chapterCount, embedding: Array(EMBEDDING_DIMENSIONS).fill(0), createdAt: timestamp, updatedAt: timestamp };
      const contextDraft = { key: id(), scopeKey: input.scopeKey, bookKey, userContext: `Topic: ${input.topic}\nGoal: ${input.goal}\nCurrent knowledge: ${input.currentKnowledge}\nTone: ${input.writingTone}`, priorKnowledge: sourceDocuments.length ? 'Selected Archive snapshots are attached.' : input.currentKnowledge, priorBookContext: input.topic, personalizationContext: input.currentKnowledge, researchContext: 'Provider-neutral web research is enabled.', noveltyContext: 'Prefer concrete examples and original synthesis.', generationBrief: input.additionalInstructions || input.goal, embedding: Array(EMBEDDING_DIMENSIONS).fill(0), createdAt: timestamp, updatedAt: timestamp };
      const sources = sourceDocuments.map((source) => bookSourceSchema.parse({ key: id(), scopeKey: input.scopeKey, bookKey, sourceType: 'document', sourceKey: source.key, title: source.name, content: source.content, contentHash: hash(source.content), sourceUpdatedAt: source.updatedAt, relevance: 'Explicitly selected by the user.', embedding: Array(EMBEDDING_DIMENSIONS).fill(0), createdAt: timestamp }));
      await repository.create(context, bookSchema.parse(draft), bookContextSchema.parse(contextDraft), sources); return bookKey;
    },
    async write(bookKey, input, context) {
      if (!context.generationLeaseToken) throw new Error('Book generation lease token is required.'); const pendingUploads = new Set<string>(); const signal = context.signal; const uploadAttempt = hash(context.generationLeaseToken).slice(0, 12);
      const upload = async (value: Parameters<DocumentObjectStorage['upload']>[0]) => { pendingUploads.add(value.key); const stored = await storage.upload(value); if (stored.storageKey !== value.key) { pendingUploads.delete(value.key); pendingUploads.add(stored.storageKey); } return stored; };
      const stage = async (generationStage: Book['generationStage'], status: Book['status']) => { await repository.updateBook(context, bookKey, { generationStage, status, generationError: undefined, updatedAt: now() }); await notify(input.scopeKey).catch(() => undefined); };
      const provider = async <T>(operation: () => Promise<T>) => { const value = await operation(); await check(context, bookKey); return value; };
      try {
        await check(context, bookKey); let detail = await repository.detail(context, bookKey); let sources = await repository.sources(context, bookKey);
        const unembeddedSources = sources.filter(({ embedding }) => embedding.every((value) => value === 0));
        if (unembeddedSources.length) { const embedded: BookSource[] = []; await boundedMap(unembeddedSources, 4, async (source) => { embedded.push({ ...source, embedding: await vector(bookSourcesEmbeddingFields, source, context.organizationKey, signal) }); }); await repository.addSources(context, bookKey, embedded); sources = sources.map((source) => embedded.find(({ key }) => key === source.key) ?? source); }
        if (!sources.some(({ sourceType }) => sourceType === 'web')) {
          await stage('research', 'researching');
          const result = await provider(() => research(`Research reliable current evidence for this audiobook. Topic: ${input.topic}. Goal: ${input.goal}. Selected evidence: ${JSON.stringify(sourceEvidence(sources))}`, context.organizationKey, signal));
          if (!result.citations.length) throw new Error('Grounded book research must include at least one citation.');
          const webSources: BookSource[] = [];
          await boundedMap(result.citations, 4, async (citation) => { const value = { key: id(), scopeKey: input.scopeKey, bookKey, sourceType: 'web' as const, url: citation.url, title: citation.title, content: result.text, contentHash: hash(result.text), relevance: `Web research for ${input.topic}`, createdAt: now() }; webSources.push(bookSourceSchema.parse({ ...value, embedding: await vector(bookSourcesEmbeddingFields, value, context.organizationKey, signal) })); });
          await repository.addSources(context, bookKey, webSources); await repository.advanceGeneration(context, bookKey, now()); sources = [...sources, ...webSources];
        }
        await repository.reconcileGeneration(context, bookKey, 1, now()); const evidence = sourceEvidence(sources);
        let chapters = detail.chapters.map(({ chapter }) => chapter);
        if (!chapters.length) {
          await stage('outline', 'planning');
          const idea = json(ideaSchema, await provider(() => ask(prompt('Design a grounded useful nonfiction audiobook. Use the supplied Archive snapshots and web evidence. Return strict JSON with title, optional subtitle, description, outcome, and summary.', JSON.stringify({ input, evidence })), context.organizationKey, signal)));
          await repository.updateBook(context, bookKey, { title: idea.title, subtitle: idea.subtitle, description: idea.description, outcome: idea.outcome, embedding: await vector(['title', 'subtitle', 'description', 'goal', 'audience', 'outcome'], { ...detail.book, ...idea }, context.organizationKey, signal), updatedAt: now() });
          const outline = json(outlineSchema, await provider(() => ask(prompt(`Create exactly ${input.chapterCount} ordered chapter briefs grounded in the supplied evidence. Every description must contain 80-120 words. Return strict JSON {"chapters":[{"title","description","objective","evidenceKeyPoints":[],"topics":[],"priorTransition","nextTransition","repetitionBoundaries":[],"targetWordMin":500,"targetWordMax":750}]}.`, JSON.stringify({ input, book: idea, evidence })), context.organizationKey, signal)));
          if (outline.chapters.length !== input.chapterCount) throw new Error(`Outline must contain exactly ${input.chapterCount} chapters.`);
          const timestamp = now(); chapters = new Array(outline.chapters.length); const contexts: ChapterContext[] = new Array(outline.chapters.length);
          await boundedMap(outline.chapters, 4, async (brief, index) => { const chapterDraft = { ...brief, key: id(), scopeKey: input.scopeKey, bookKey, position: index + 1, status: 'planned' as const, createdAt: timestamp, updatedAt: timestamp }; const chapter = bookChapterSchema.parse({ ...chapterDraft, embedding: await vector(bookChaptersEmbeddingFields, chapterDraft, context.organizationKey, signal) }); chapters[index] = chapter; const contextDraft = { key: id(), scopeKey: input.scopeKey, chapterKey: chapter.key, previousContext: brief.priorTransition, objectiveContext: brief.objective, sourceContext: brief.evidenceKeyPoints.join('\n'), personalizationContext: input.currentKnowledge, noveltyContext: brief.repetitionBoundaries.join('\n'), nextContext: brief.nextTransition, generationBrief: brief.description, createdAt: timestamp, updatedAt: timestamp }; contexts[index] = chapterContextSchema.parse({ ...contextDraft, embedding: await vector(chapterContextsEmbeddingFields, contextDraft, context.organizationKey, signal) }); });
          await repository.replaceChapters(context, bookKey, chapters, contexts, { chapterCount: chapters.length, generationStage: 'draft', status: 'writing', updatedAt: now() }); await repository.advanceGeneration(context, bookKey, now());
        }
        await repository.reconcileGeneration(context, bookKey, 2, now()); await stage('draft', 'writing');
        await boundedMap(chapters, 4, async (chapter, index) => {
          const draftInputHash = hash({ generation: detail.book.generationBriefFingerprint, chapter: stableChapterBrief(chapter), evidence });
          if (chapter.content && chapter.draftInputHash === draftInputHash) return;
          await check(context, bookKey); await repository.updateChapter(context, chapter.key, { status: 'writing', updatedAt: now() });
          const content = (await provider(() => ask(prompt(`Write 500-750 words of finished nonfiction prose in ${input.language}. Ground factual claims in the supplied source evidence and chapter evidence points. Respect transitions and repetition boundaries. No headings, lists, meta commentary, or unsupported claims.`, JSON.stringify({ chapter, evidence, personalization: input.currentKnowledge, tone: input.writingTone })), context.organizationKey, signal))).trim();
          if (words(content) < 500 || words(content) > 750) throw new Error(`Chapter ${index + 1} must contain 500-750 words.`);
          const supersededStorageKeys = [chapter.audioStorageKey, chapter.imageStorageKey].filter((key): key is string => Boolean(key)); const updated = await repository.updateChapter(context, chapter.key, { content, draftInputHash, finalizationInputHash: undefined, audioInputHash: undefined, audioStorageKey: undefined, audioDurationSeconds: undefined, imageInputHash: undefined, imageStorageKey: undefined, status: 'written', estimatedMinutes: Math.ceil(words(content) / 220), embedding: await vector(bookChaptersEmbeddingFields, { ...chapter, content }, context.organizationKey, signal), updatedAt: now() }); chapters[index] = updated; if (supersededStorageKeys.length) await repository.enqueueUnreferencedStorage(context, supersededStorageKeys, now()); await repository.advanceGeneration(context, bookKey, now()); await notify(input.scopeKey).catch(() => undefined);
        });
        await repository.reconcileGeneration(context, bookKey, 2 + chapters.length, now()); await stage('continuity', 'finalizing'); let previous = '';
        for (let index = 0; index < chapters.length; index += 1) { const chapter = chapters[index]!; const finalizationInputHash = hash({ draftInputHash: chapter.draftInputHash, previous: hash(previous), boundaries: chapter.repetitionBoundaries, transitions: [chapter.priorTransition, chapter.nextTransition] }); if (chapter.content && chapter.finalizationInputHash === finalizationInputHash) { previous = chapter.content; continue; } await check(context, bookKey); const finalized = (await provider(() => ask(prompt('Continuity-edit this chapter while preserving 500-750 words and grounded claims. Return only final prose. Honor prior/next transitions and repetition boundaries.', JSON.stringify({ previousEnding: previous.slice(-1_500), chapter, evidence })), context.organizationKey, signal))).trim(); if (words(finalized) < 500 || words(finalized) > 750) throw new Error('Finalized chapter must contain 500-750 words.'); previous = finalized; chapters[index] = await repository.updateChapter(context, chapter.key, { content: finalized, finalizationInputHash, status: 'finalized', estimatedMinutes: Math.ceil(words(finalized) / 220), embedding: await vector(bookChaptersEmbeddingFields, { ...chapter, content: finalized }, context.organizationKey, signal), updatedAt: now() }); await repository.advanceGeneration(context, bookKey, now()); }
        await repository.reconcileGeneration(context, bookKey, 2 + chapters.length * 2, now()); await stage('audio', 'narrating');
        await boundedMap(chapters, 3, async (chapter, index) => { const audioInputHash = hash({ content: chapter.content, voice: input.narratorVoiceKey, pace: input.narrationPace }); if (chapter.audioStorageKey && chapter.audioInputHash === audioInputHash) return; await check(context, bookKey); const previousStorageKey = chapter.audioStorageKey; const voice = input.narratorVoiceKey === 'calm' ? 'sage' : input.narratorVoiceKey === 'warm' ? 'coral' : 'alloy'; const audio = await provider(() => speech({ text: chapter.content!, voice, pace: input.narrationPace, format: 'mp3' }, context.organizationKey, signal)); const stored = await upload({ key: `books/${input.scopeKey}/${bookKey}/chapter-${chapter.position}-${audioInputHash.slice(0, 12)}-${uploadAttempt}.mp3`, bytes: audio.bytes, mimeType: audio.mimeType }); chapters[index] = await repository.updateChapter(context, chapter.key, { audioStorageKey: stored.storageKey, audioInputHash, audioDurationSeconds: audio.durationSeconds ?? Math.max(1, Math.ceil(words(chapter.content!) / (2.7 * input.narrationPace))), status: 'audio-ready', updatedAt: now() }); pendingUploads.delete(stored.storageKey); if (previousStorageKey && previousStorageKey !== stored.storageKey) await repository.enqueueUnreferencedStorage(context, [previousStorageKey], now()); await repository.advanceGeneration(context, bookKey, now()); await notify(input.scopeKey).catch(() => undefined); });
        await repository.reconcileGeneration(context, bookKey, 2 + chapters.length * 3, now()); detail = await repository.detail(context, bookKey); const coverInputHash = hash({ title: detail.book.title, description: detail.book.description, generation: detail.book.generationBriefFingerprint });
        if (!detail.book.coverStorageKey || detail.book.coverInputHash !== coverInputHash) { const previousStorageKey = detail.book.coverStorageKey; const cover = await pngMedia(await provider(() => image(`Editorial audiobook cover without logos. Title: ${detail.book.title}. ${detail.book.description}`, context.organizationKey, signal))); if (!cover) throw new Error('Automatic book cover generation failed.'); const stored = await upload({ key: `books/${input.scopeKey}/${bookKey}/cover-${coverInputHash.slice(0, 12)}-${uploadAttempt}.png`, bytes: cover.bytes, mimeType: cover.mimeType }); await repository.updateBook(context, bookKey, { coverStorageKey: stored.storageKey, coverInputHash, updatedAt: now() }); pendingUploads.delete(stored.storageKey); if (previousStorageKey && previousStorageKey !== stored.storageKey) await repository.enqueueUnreferencedStorage(context, [previousStorageKey], now()); await repository.advanceGeneration(context, bookKey, now()); }
        if (input.chapterImages) { await stage('art', 'narrating'); await boundedMap(chapters, 3, async (chapter, index) => { const imageInputHash = hash({ title: chapter.title, description: chapter.description, content: chapter.content }); if (chapter.imageInputHash === imageInputHash) return; const previousStorageKey = chapter.imageStorageKey; let art: { bytes: Uint8Array; mimeType: string } | null = null; try { art = await pngMedia(await provider(() => (options.art ?? image)(`Editorial chapter illustration, no text. ${chapter.title}: ${chapter.description}`, context.organizationKey, signal))); } catch (error) { if (context.signal?.aborted || await repository.isCancellationRequested(context, bookKey).catch(() => false)) throw error; } if (art) { const stored = await upload({ key: `books/${input.scopeKey}/${bookKey}/chapter-${chapter.position}-${imageInputHash.slice(0, 12)}-${uploadAttempt}.png`, bytes: art.bytes, mimeType: art.mimeType }); chapters[index] = await repository.updateChapter(context, chapter.key, { imageStorageKey: stored.storageKey, imageInputHash, updatedAt: now() }); pendingUploads.delete(stored.storageKey); if (previousStorageKey && previousStorageKey !== stored.storageKey) await repository.enqueueUnreferencedStorage(context, [previousStorageKey], now()); } await repository.advanceGeneration(context, bookKey, now()); }); await repository.reconcileGeneration(context, bookKey, 3 + chapters.length * 4, now()); }
        else await repository.reconcileGeneration(context, bookKey, 3 + chapters.length * 3, now());
        await stage('publish', 'finalizing'); await check(context, bookKey); await repository.publishChapters(context, bookKey, input.chapterCount, now()); await notify(input.scopeKey).catch(() => undefined); await notifyContent(input.scopeKey).catch(() => undefined);
      } catch (error) { if (pendingUploads.size) await repository.enqueueUnreferencedStorage(context, [...pendingUploads], now()).catch(() => undefined); const cancellation = await repository.isCancellationRequested(context, bookKey).catch(() => false); if (!cancellation && context.persistFailure !== false) await repository.updateBook(context, bookKey, { status: 'failed', generationError: error instanceof Error ? error.message.slice(0, 4_000) : 'Generation failed.', updatedAt: now() }).catch(() => undefined); throw error; }
    },
  };
}
