import { db, withTransaction } from '@/lib/db/client';
import { toArangoDoc, withArangoKey } from '@/lib/db/base';
import { collectionSchema, type Collection } from '@/lib/db/collections.node';
import { collectionMemberSchema, type CollectionMember } from '@/lib/db/collection-members.node';
import { collectionInviteSchema, type CollectionInvite } from '@/lib/db/collection-invites.node';
import { shareSchema, type Share } from '@/lib/db/shares.node';
import { collectionImageSchema, type CollectionImage } from '@/lib/db/collection-images.node';
import { galleryUploadSchema, getGalleryUploadById, insertGalleryUpload, updateGalleryUpload, type GalleryUpload } from '@/lib/db/gallery-uploads.node';
import { getImageById, imageSchema, type Image } from '@/lib/db/images.node';
import { visualIdentitySchema, type VisualIdentity } from '@/lib/db/visual-identities.node';
import { imageIdentitySchema, type ImageIdentity } from '@/lib/db/image-identities.node';
import { createMediaLibraryRepository, searchAccessibleImages, type AccessibleImageSearchInput, type AccessibleImageSearchResult, type MediaLibraryDatabase } from '@/lib/media-library';
import { findRedundantGalleryImageKeys } from '@/lib/gallery-duplicates';
import { newId } from '@/lib/ids';
import { cursorPage, decodeCursor, encodeCursor, type CursorPage } from '@/lib/cursor-pagination';
import { z } from 'zod';

export interface GallerySubjectRow { identity: VisualIdentity; reference: Image; imageCount: number; }
export interface GalleryCollectionRow { collection: Collection; count: number; cover: Image | null; }
export type GalleryCollectionRole = 'owner' | 'collaborator' | 'viewer';
export interface GalleryMemberRow { member: CollectionMember; displayName: string; joinedAt: string; }
export interface GalleryInviteRow { invite: CollectionInvite; collection: Collection; inviterDisplayName: string; }
export interface GalleryShareRow { share: Share; responseCiphertext: string; }
export interface GalleryRepository {
  canManageScope(scopeKey: string, actorKey: string): Promise<boolean>;
  canAccessImage(scopeKey: string, imageKey: string, actorKey: string): Promise<boolean>;
  canAccessCollection(scopeKey: string, collectionKey: string, actorKey: string): Promise<boolean>;
  ownsCollection(scopeKey: string, collectionKey: string, actorKey: string): Promise<boolean>;
  ownsImage(scopeKey: string, imageKey: string, actorKey: string): Promise<boolean>;
  canMutateImage(scopeKey: string, imageKey: string, actorKey: string): Promise<boolean>;
  getCollectionRole(scopeKey: string, collectionKey: string, actorKey: string): Promise<GalleryCollectionRole | null>;
  getCollection(scopeKey: string, collectionKey: string): Promise<Collection | null>;
  getImage(imageKey: string): Promise<Image | null>;
  getVisualIdentity(scopeKey: string, identityKey: string, actorKey: string): Promise<VisualIdentity | null>;
  addImageToCollection(relation: CollectionImage): Promise<CollectionImage>;
  createCollection(collection: Collection, member: CollectionMember): Promise<void>;
  listOverview(input: { scopeKey: string; actorKey: string; collectionKey?: string; cursor?: string; limit: number }): Promise<{ collections: Array<GalleryCollectionRow & { role: GalleryCollectionRole }>; images: CursorPage<Image> }>;
  listCollectionMembers(scopeKey: string, collectionKey: string): Promise<GalleryMemberRow[]>;
  listPendingInvites(scopeKey: string, actorKey: string, now: string): Promise<GalleryInviteRow[]>;
  createCollectionInvite(invite: CollectionInvite, replay: { requestHash: string; responseCiphertext: string }): Promise<{ invite: CollectionInvite; requestHash: string; responseCiphertext: string } | null>;
  acceptCollectionInvite(scopeKey: string, inviteKey: string, actorKey: string, memberKey: string, now: string): Promise<CollectionMember | null>;
  rejectCollectionInvite(scopeKey: string, inviteKey: string, actorKey: string, now: string): Promise<string | null>;
  revokeCollectionInvite(scopeKey: string, collectionKey: string, inviteKey: string, ownerKey: string, now: string): Promise<boolean>;
  updateCollectionMemberRole(scopeKey: string, collectionKey: string, memberKey: string, role: Exclude<GalleryCollectionRole, 'owner'>, ownerKey: string): Promise<CollectionMember | null>;
  removeCollectionMember(scopeKey: string, collectionKey: string, memberKey: string, ownerKey: string): Promise<boolean>;
  leaveCollection(scopeKey: string, collectionKey: string, actorKey: string): Promise<boolean>;
  listCollectionShares(scopeKey: string, collectionKey: string, ownerKey: string): Promise<GalleryShareRow[]>;
  createCollectionShare(share: Share, ownerKey: string, replay: { requestHash: string; responseCiphertext: string }): Promise<{ share: Share; requestHash: string; responseCiphertext: string } | null>;
  setCollectionShareActive(scopeKey: string, collectionKey: string, shareKey: string, ownerKey: string, active: boolean, now: string): Promise<GalleryShareRow | null>;
  activateCollectionShare(scopeKey: string, tokenHash: string, actorKey: string, memberKey: string, now: string): Promise<CollectionMember | null>;
  getUserKeyByMemberKey(memberKey: string): Promise<string | null>;
  getInviteRecipientUserKey(inviteKey: string): Promise<string | null>;
  listCollectionUserKeys(collectionKey: string): Promise<string[]>;
  listImageCollectionKeys(scopeKey: string, imageKeys: string[]): Promise<string[]>;
  listRedundantCollectionImages(scopeKey: string, collectionKey: string): Promise<Image[]>;
  deleteDuplicateImages(scopeKey: string, collectionKey: string, imageKeys: string[], actorKey: string, now: string): Promise<{ removedImageKeys: string[]; deletedImageKeys: string[] } | null>;
  deleteImages(scopeKey: string, imageKeys: string[], actorKey: string, now: string): Promise<{ deletedImageKeys: string[] } | null>;
  transferCollectionImages(input: { scopeKey: string; actorKey: string; sourceCollectionKey: string; destinationCollectionKeys: string[]; imageKeys: string[]; mode: 'copy' | 'move'; now: string }): Promise<{ status: 'ok'; createdRelationCount: number } | { status: 'selection-changed' | 'destination-forbidden' }>;
  insertUpload(upload: GalleryUpload): Promise<GalleryUpload>;
  getUpload(uploadKey: string): Promise<GalleryUpload | null>;
  listRecoverableUploads(): Promise<GalleryUpload[]>;
  updateUpload(uploadKey: string, patch: Partial<Omit<GalleryUpload, 'key'>>): Promise<GalleryUpload>;
  failUpload(uploadKey: string, scopeKey: string, errorCode: string, now: string): Promise<boolean>;
  searchAccessibleImages(input: AccessibleImageSearchInput): Promise<AccessibleImageSearchResult[]>;
  listMatchingIdentityNames(scopeKey: string, query: string): Promise<VisualIdentity[]>;
  listIdentityMatches(scopeKey: string, embedding: number[]): Promise<Array<{ identityKey: string; confidence: number }>>;
  persistIdentityMatches(scopeKey: string, identityKey: string, matches: Array<{ imageKey: string; confidence: number }>): Promise<void>;
  setImageFavorite(scopeKey: string, imageKey: string, actorKey: string, isFavorite: boolean, now: string): Promise<Image | null>;
  updateImageDetails(scopeKey: string, imageKey: string, actorKey: string, filename: string, isFavorite: boolean, embedding: number[], now: string): Promise<Image | null>;
  updateCollectionDetails(scopeKey: string, collectionKey: string, name: string, isFavorite: boolean, embedding: number[], now: string): Promise<Collection | null>;
  deleteCollection(scopeKey: string, collectionKey: string, now: string): Promise<boolean>;
  listSubjects(scopeKey: string, includeDeleted: boolean): Promise<GallerySubjectRow[]>;
  getSubject(scopeKey: string, identityKey: string, includeDeleted: boolean): Promise<GallerySubjectRow | null>;
  createSubject(identity: VisualIdentity, relations: ImageIdentity[], referenceImageKeys: string[]): Promise<boolean>;
  listSubjectImages(scopeKey: string, identityKey: string, collectionKey?: string): Promise<Array<{ image: Image; confidence: number }>>;
  setSubjectDeleted(scopeKey: string, identityKey: string, deleted: boolean, now: string): Promise<boolean>;
}

type TransactionRunner = <T>(collections: string[] | { read: string[]; write: string[] }, operation: (database: MediaLibraryDatabase) => Promise<T>) => Promise<T>;
const runTransaction: TransactionRunner = (collections, operation) => withTransaction(collections, (transaction) => operation(transaction));
const parse = <T>(schema: { parse(value: unknown): T }, value: unknown) => schema.parse(withArangoKey(value as Record<string, unknown>));
async function all(database: MediaLibraryDatabase, query: string, bindVars: Record<string, unknown>) { return (await database.query(query, bindVars)).all(); }
const liveCollectionOwner = 'LET scope = DOCUMENT(scopes, @scopeKey) LET actor = DOCUMENT(userOrganizations, @ownerKey) LET collection = DOCUMENT(collections, @collectionKey) LET owner = FIRST(FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @collectionKey && member.memberKey == @ownerKey && member.role == "owner" LIMIT 1 RETURN member) FILTER scope != null && scope.deletedAt == null && actor != null && actor.status == "active" && actor.organizationId == scope.organizationKey && collection != null && collection.scopeKey == @scopeKey && collection.deletedAt == null && owner != null';

async function redundantCollectionImages(database: MediaLibraryDatabase, scopeKey: string, collectionKey: string) {
  const rows = await all(database, `FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.collectionKey == @collectionKey LET image = DOCUMENT(images, relation.imageKey) FILTER image != null && image.scopeKey == @scopeKey && image.deletedAt == null LET caption = DOCUMENT(imageCaptions, image.imageCaptionKey) FILTER caption != null && caption.scopeKey == @scopeKey && caption.perceptualHash != null LET protected = LENGTH(FOR identityRelation IN imageIdentities FILTER identityRelation.scopeKey == @scopeKey && identityRelation.imageKey == image._key && identityRelation.isReference == true LIMIT 1 RETURN 1) > 0 SORT image.createdAt ASC, image._key ASC RETURN { image, perceptualHash: caption.perceptualHash, protected }`, { scopeKey, collectionKey }) as Array<{ image: unknown; perceptualHash: string; protected: boolean }>;
  const parsed = rows.map((row) => ({ image: parse(imageSchema, row.image), perceptualHash: row.perceptualHash, protected: row.protected }));
  const redundantKeys = new Set(findRedundantGalleryImageKeys(parsed.map(({ image, perceptualHash, protected: isProtected }) => ({ key: image.key, createdAt: image.createdAt, perceptualHash, protected: isProtected }))));
  return parsed.map(({ image }) => image).filter(({ key }) => redundantKeys.has(key));
}

const overviewCursorSchema = z.object({
  version: z.literal(1), scopeKey: z.string().cuid(), collectionKey: z.string().cuid().nullable(), createdAt: z.string().datetime(), imageKey: z.string().cuid(),
}).strict();

export function createGalleryRepository(database: MediaLibraryDatabase = db, transaction: TransactionRunner = runTransaction): GalleryRepository {
  const media = createMediaLibraryRepository(database);
  const subjectRows = async (query: string, bindVars: Record<string, unknown>) => (await all(database, query, bindVars) as Array<{ identity: unknown; reference: unknown; imageCount: number }>).map((row) => ({ identity: parse(visualIdentitySchema, row.identity), reference: parse(imageSchema, row.reference), imageCount: row.imageCount }));
  return {
    canManageScope: media.canManageScope,
    canAccessImage: media.canAccessImage,
    canAccessCollection: media.canAccessCollection,
    ownsCollection: media.ownsCollection,
    ownsImage: media.ownsImage,
    async canMutateImage(scopeKey, imageKey, actorKey) { return Boolean((await all(database, `LET membership = DOCUMENT(userOrganizations, @actorKey) LET scope = DOCUMENT(scopes, @scopeKey) LET image = DOCUMENT(images, @imageKey) FILTER membership != null && membership.status == "active" && scope != null && scope.deletedAt == null && membership.organizationId == scope.organizationKey && image != null && image.scopeKey == @scopeKey && image.deletedAt == null LET scopeRole = FIRST(FOR item IN scopeMembers FILTER item.scopeKey == @scopeKey && item.userOrganizationKey == @actorKey && item.status == "active" LIMIT 1 RETURN item.role) LET elevated = membership.orgRole IN ["owner", "admin"] || scopeRole IN ["owner", "admin"] LET relationCount = LENGTH(FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == @imageKey RETURN 1) LET roles = (FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == @imageKey FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == relation.collectionKey && member.memberKey == @actorKey RETURN member.role == "member" ? "collaborator" : member.role) FILTER elevated || "owner" IN roles || (image.createdByKey == @actorKey && (relationCount == 0 || "collaborator" IN roles)) RETURN true`, { scopeKey, imageKey, actorKey }))[0]); },
    async getCollectionRole(scopeKey, collectionKey, actorKey) {
      const value = (await all(database, `LET membership = DOCUMENT(userOrganizations, @actorKey) LET scope = DOCUMENT(scopes, @scopeKey) FILTER membership != null && membership.status == "active" && scope != null && scope.deletedAt == null && membership.organizationId == scope.organizationKey LET scopeRole = FIRST(FOR item IN scopeMembers FILTER item.scopeKey == @scopeKey && item.userOrganizationKey == @actorKey && item.status == "active" LIMIT 1 RETURN item.role) LET elevated = membership.orgRole IN ["owner", "admin"] || scopeRole IN ["owner", "admin"] LET collection = DOCUMENT(collections, @collectionKey) FILTER collection != null && collection.scopeKey == @scopeKey && collection.deletedAt == null LET member = FIRST(FOR item IN collectionMembers FILTER item.scopeKey == @scopeKey && item.collectionKey == @collectionKey && item.memberKey == @actorKey LIMIT 1 RETURN item) FILTER elevated || member != null RETURN elevated ? "owner" : (member.role == "member" ? "collaborator" : member.role)`, { scopeKey, collectionKey, actorKey }))[0];
      return value === 'owner' || value === 'collaborator' || value === 'viewer' ? value : null;
    },
    getCollection: media.getCollection,
    getImage: getImageById,
    async getVisualIdentity(scopeKey, identityKey, actorKey) { if (!await media.canManageScope(scopeKey, actorKey)) return null; const value = (await all(database, 'FOR identity IN visualIdentities FILTER identity._key == @identityKey && identity.scopeKey == @scopeKey && identity.deletedAt == null LIMIT 1 RETURN identity', { scopeKey, identityKey }))[0]; return value ? parse(visualIdentitySchema, value) : null; },
    addImageToCollection: media.addImageToCollection,
    createCollection(collection, member) { return transaction(['collections', 'collectionMembers'], async (tx) => { await tx.query('INSERT @collection INTO collections', { collection: toArangoDoc(collection) }); await tx.query('INSERT @member INTO collectionMembers', { member: toArangoDoc(member) }); }); },
    async listOverview({ scopeKey, actorKey, collectionKey, cursor, limit }) {
      const after = decodeCursor(cursor, overviewCursorSchema);
      if (after && (after.scopeKey !== scopeKey || after.collectionKey !== (collectionKey ?? null))) throw new z.ZodError([{ code: 'custom', path: ['cursor'], message: 'Cursor does not belong to this Gallery location.' }]);
      const access = `LET membership = DOCUMENT(userOrganizations, @actorKey) LET scope = DOCUMENT(scopes, @scopeKey) FILTER membership != null && membership.status == "active" && scope != null && scope.deletedAt == null && membership.organizationId == scope.organizationKey LET scopeRole = FIRST(FOR item IN scopeMembers FILTER item.scopeKey == @scopeKey && item.userOrganizationKey == @actorKey && item.status == "active" LIMIT 1 RETURN item.role) LET elevated = membership.orgRole IN ["owner", "admin"] || scopeRole IN ["owner", "admin"]`;
      const collectionRows = await all(database, `${access} FOR collection IN collections FILTER collection.scopeKey == @scopeKey && collection.deletedAt == null LET member = FIRST(FOR item IN collectionMembers FILTER item.scopeKey == @scopeKey && item.collectionKey == collection._key && item.memberKey == @actorKey LIMIT 1 RETURN item) FILTER elevated || member != null LET role = elevated ? "owner" : (member.role == "member" ? "collaborator" : member.role) LET imageKeys = (FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.collectionKey == collection._key RETURN relation.imageKey) LET cover = collection.coverImageKey == null ? (LENGTH(imageKeys) == 0 ? null : DOCUMENT(images, imageKeys[0])) : DOCUMENT(images, collection.coverImageKey) SORT collection.name ASC RETURN { collection, count: LENGTH(imageKeys), cover, role }`, { scopeKey, actorKey }) as Array<{ collection: unknown; count: number; cover: unknown | null; role: GalleryCollectionRole }>;
      const imageRows = await all(database, `${access} FOR image IN images FILTER image.scopeKey == @scopeKey && image.deletedAt == null LET relationCount = LENGTH(FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == image._key RETURN 1) LET accessibleCollections = (FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == image._key FILTER @collectionKey == null || relation.collectionKey == @collectionKey LET collection = DOCUMENT(collections, relation.collectionKey) FILTER collection != null && collection.deletedAt == null LET member = FIRST(FOR item IN collectionMembers FILTER item.scopeKey == @scopeKey && item.collectionKey == relation.collectionKey && item.memberKey == @actorKey LIMIT 1 RETURN item) FILTER elevated || member != null RETURN 1) FILTER @collectionKey == null ? (elevated || (image.createdByKey == @actorKey && relationCount == 0) || LENGTH(accessibleCollections) > 0) : LENGTH(accessibleCollections) > 0 FILTER @afterCreatedAt == null || image.createdAt < @afterCreatedAt || (image.createdAt == @afterCreatedAt && image._key > @afterImageKey) SORT image.createdAt DESC, image._key ASC LIMIT @queryLimit RETURN image`, { scopeKey, actorKey, collectionKey: collectionKey ?? null, afterCreatedAt: after?.createdAt ?? null, afterImageKey: after?.imageKey ?? '', queryLimit: limit + 1 });
      const parsedImages = imageRows.map((value) => parse(imageSchema, value));
      return {
        collections: collectionRows.map((row) => ({ collection: parse(collectionSchema, row.collection), count: row.count, cover: row.cover ? parse(imageSchema, row.cover) : null, role: row.role })),
        images: cursorPage(parsedImages, limit, (image) => encodeCursor({ version: 1, scopeKey, collectionKey: collectionKey ?? null, createdAt: image.createdAt, imageKey: image.key })),
      };
    },
    async listCollectionMembers(scopeKey, collectionKey) { return (await all(database, 'FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @collectionKey LET membership = DOCUMENT(userOrganizations, member.memberKey) LET user = membership == null ? null : DOCUMENT(users, membership.userId) FILTER membership != null && membership.status == "active" && user != null LET displayName = LENGTH(TRIM(user.name || "")) > 0 ? TRIM(user.name) : (LENGTH(TRIM(user.alias || "")) > 0 ? TRIM(user.alias) : "Member") SORT member.role == "owner" DESC, member.createdAt ASC RETURN { member, displayName, joinedAt: member.createdAt }', { scopeKey, collectionKey }) as Array<{ member: unknown; displayName: string; joinedAt: string }>).map((row) => ({ member: parse(collectionMemberSchema, row.member), displayName: row.displayName, joinedAt: row.joinedAt })); },
    async listPendingInvites(scopeKey, actorKey, now) { return (await all(database, 'LET membership = DOCUMENT(userOrganizations, @actorKey) LET user = membership == null ? null : DOCUMENT(users, membership.userId) FILTER membership != null && membership.status == "active" && user != null FOR invite IN collectionInvites FILTER invite.scopeKey == @scopeKey && invite.acceptedAt == null && invite.rejectedAt == null && invite.revokedAt == null && (invite.expiresAt == null || invite.expiresAt > @now) LET ownsCollection = LENGTH(FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == invite.collectionKey && member.memberKey == @actorKey && member.role == "owner" LIMIT 1 RETURN 1) > 0 FILTER ownsCollection || invite.inviteeKey == @actorKey || invite.email == LOWER(user.email) LET collection = DOCUMENT(collections, invite.collectionKey) LET inviterMembership = DOCUMENT(userOrganizations, invite.invitedByKey) LET inviter = inviterMembership == null ? null : DOCUMENT(users, inviterMembership.userId) FILTER collection != null && collection.deletedAt == null && inviter != null LET inviterDisplayName = LENGTH(TRIM(inviter.name || "")) > 0 ? TRIM(inviter.name) : (LENGTH(TRIM(inviter.alias || "")) > 0 ? TRIM(inviter.alias) : "Member") SORT invite.createdAt DESC RETURN { invite, collection, inviterDisplayName }', { scopeKey, actorKey, now }) as Array<{ invite: unknown; collection: unknown; inviterDisplayName: string }>).map((row) => ({ invite: parse(collectionInviteSchema, row.invite), collection: parse(collectionSchema, row.collection), inviterDisplayName: row.inviterDisplayName })); },
    async createCollectionInvite(invite, replay) { const value = (await all(database, `${liveCollectionOwner} UPSERT { _key: @inviteKey } INSERT MERGE(@invite, @replay) UPDATE {} IN collectionInvites RETURN NEW`, { scopeKey: invite.scopeKey, collectionKey: invite.collectionKey, ownerKey: invite.invitedByKey, inviteKey: invite.key, invite: toArangoDoc(invite), replay }))[0] as Record<string, unknown> | undefined; return value ? { invite: parse(collectionInviteSchema, value), requestHash: String(value.requestHash), responseCiphertext: String(value.responseCiphertext) } : null; },
    acceptCollectionInvite(scopeKey, inviteKey, actorKey, memberKey, now) { return transaction({ read: ['users', 'userOrganizations', 'collections', 'scopes'], write: ['collectionInvites', 'collectionMembers'] }, async (tx) => {
      const inviteValue = (await all(tx, 'LET recipientMembership = DOCUMENT(userOrganizations, @actorKey) LET recipient = recipientMembership == null ? null : DOCUMENT(users, recipientMembership.userId) LET invite = DOCUMENT(collectionInvites, @inviteKey) LET scope = invite == null ? null : DOCUMENT(scopes, invite.scopeKey) LET collection = invite == null ? null : DOCUMENT(collections, invite.collectionKey) LET inviter = invite == null ? null : FIRST(FOR owner IN collectionMembers FILTER owner.scopeKey == invite.scopeKey && owner.collectionKey == invite.collectionKey && owner.memberKey == invite.invitedByKey && owner.role == "owner" LIMIT 1 RETURN owner) FILTER invite != null && invite.scopeKey == @scopeKey && invite.acceptedAt == null && invite.rejectedAt == null && invite.revokedAt == null && (invite.expiresAt == null || invite.expiresAt > @now) FILTER invite.inviteeKey == @actorKey || (invite.email != null && recipient != null && invite.email == LOWER(recipient.email)) FILTER recipientMembership != null && recipientMembership.status == "active" && scope != null && scope.deletedAt == null && recipientMembership.organizationId == scope.organizationKey FILTER collection != null && collection.scopeKey == invite.scopeKey && collection.deletedAt == null && inviter != null RETURN invite', { scopeKey, inviteKey, actorKey, now }))[0];
      if (!inviteValue) return null;
      const invite = parse(collectionInviteSchema, inviteValue);
      const requestedRole = invite.role === 'viewer' ? 'viewer' : 'collaborator';
      const saved = (await all(tx, 'UPSERT { scopeKey: @scopeKey, collectionKey: @collectionKey, memberKey: @actorKey } INSERT { _key: @memberKey, scopeKey: @scopeKey, collectionKey: @collectionKey, memberKey: @actorKey, role: @requestedRole, createdAt: @now } UPDATE { role: OLD.role == "owner" || OLD.role == "collaborator" ? OLD.role : @requestedRole } IN collectionMembers RETURN NEW', { scopeKey: invite.scopeKey, collectionKey: invite.collectionKey, actorKey, memberKey, requestedRole, now }))[0];
      if (!saved) return null;
      const finalized = (await all(tx, 'FOR invite IN collectionInvites FILTER invite._key == @inviteKey && invite.acceptedAt == null && invite.rejectedAt == null && invite.revokedAt == null UPDATE invite WITH { acceptedAt: @now, updatedAt: @now } IN collectionInvites RETURN true', { inviteKey, now }))[0];
      if (!finalized) throw new Error('Invite acceptance could not be finalized.');
      return parse(collectionMemberSchema, saved);
    }); },
    async rejectCollectionInvite(scopeKey, inviteKey, actorKey, now) { const value = (await all(database, 'LET membership = DOCUMENT(userOrganizations, @actorKey) LET user = membership == null ? null : DOCUMENT(users, membership.userId) FOR invite IN collectionInvites FILTER invite._key == @inviteKey && invite.scopeKey == @scopeKey FILTER invite.inviteeKey == @actorKey || invite.email == LOWER(user.email) FILTER invite.acceptedAt == null && invite.rejectedAt == null && invite.revokedAt == null UPDATE invite WITH { rejectedAt: @now, updatedAt: @now } IN collectionInvites RETURN OLD.collectionKey', { scopeKey, inviteKey, actorKey, now }))[0]; return typeof value === 'string' ? value : null; },
    async revokeCollectionInvite(scopeKey, collectionKey, inviteKey, ownerKey, now) { return Boolean((await all(database, `${liveCollectionOwner} FOR invite IN collectionInvites FILTER invite._key == @inviteKey && invite.scopeKey == @scopeKey && invite.collectionKey == @collectionKey && invite.acceptedAt == null && invite.revokedAt == null UPDATE invite WITH { revokedAt: @now, updatedAt: @now } IN collectionInvites RETURN true`, { scopeKey, collectionKey, inviteKey, ownerKey, now }))[0]); },
    async updateCollectionMemberRole(scopeKey, collectionKey, memberKey, role, ownerKey) { const value = (await all(database, `${liveCollectionOwner} FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @collectionKey && member.memberKey == @memberKey && member.role != "owner" UPDATE member WITH { role: @role } IN collectionMembers RETURN NEW`, { scopeKey, collectionKey, memberKey, role, ownerKey }))[0]; return value ? parse(collectionMemberSchema, value) : null; },
    async removeCollectionMember(scopeKey, collectionKey, memberKey, ownerKey) { return Boolean((await all(database, `${liveCollectionOwner} FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @collectionKey && member.memberKey == @memberKey && member.role != "owner" REMOVE member IN collectionMembers RETURN true`, { scopeKey, collectionKey, memberKey, ownerKey }))[0]); },
    async leaveCollection(scopeKey, collectionKey, actorKey) { return Boolean((await all(database, 'FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @collectionKey && member.memberKey == @actorKey && member.role != "owner" REMOVE member IN collectionMembers RETURN true', { scopeKey, collectionKey, actorKey }))[0]); },
    async listCollectionShares(scopeKey, collectionKey, ownerKey) { return (await all(database, `${liveCollectionOwner} FOR share IN shares FILTER share.scopeKey == @scopeKey && share.sourceType == "collection" && share.sourceKey == @collectionKey && share.deletedAt == null && IS_STRING(share.responseCiphertext) SORT share.createdAt DESC RETURN { share, responseCiphertext: share.responseCiphertext }`, { scopeKey, collectionKey, ownerKey }) as Array<{ share: unknown; responseCiphertext: string }>).map((row) => ({ share: parse(shareSchema, row.share), responseCiphertext: row.responseCiphertext })); },
    async createCollectionShare(share, ownerKey, replay) { const value = (await all(database, `${liveCollectionOwner} UPSERT { _key: @shareKey } INSERT MERGE(@share, @replay) UPDATE {} IN shares RETURN NEW`, { scopeKey: share.scopeKey, collectionKey: share.sourceKey, ownerKey, shareKey: share.key, share: toArangoDoc(share), replay }))[0] as Record<string, unknown> | undefined; return value ? { share: parse(shareSchema, value), requestHash: String(value.requestHash), responseCiphertext: String(value.responseCiphertext) } : null; },
    async setCollectionShareActive(scopeKey, collectionKey, shareKey, ownerKey, active, now) { const value = (await all(database, `${liveCollectionOwner} FOR share IN shares FILTER share._key == @shareKey && share.scopeKey == @scopeKey && share.sourceType == "collection" && share.sourceKey == @collectionKey && share.deletedAt == null && IS_STRING(share.responseCiphertext) UPDATE share WITH { revokedAt: @revokedAt, updatedAt: @now } IN shares OPTIONS { keepNull: true } RETURN { share: NEW, responseCiphertext: NEW.responseCiphertext }`, { scopeKey, collectionKey, shareKey, ownerKey, revokedAt: active ? null : now, now }))[0] as { share?: unknown; responseCiphertext?: unknown } | undefined; return value?.share && typeof value.responseCiphertext === 'string' ? { share: parse(shareSchema, value.share), responseCiphertext: value.responseCiphertext } : null; },
    activateCollectionShare(scopeKey, tokenHash, actorKey, memberKey, now) { return transaction({ read: ['shares', 'collections', 'scopes', 'userOrganizations'], write: ['collectionMembers'] }, async (tx) => { const value = (await all(tx, 'LET actor = DOCUMENT(userOrganizations, @actorKey) FOR share IN shares FILTER share.scopeKey == @scopeKey && share.tokenHash == @tokenHash && share.sourceType == "collection" && share.permission IN ["viewer", "collaborator"] && share.deletedAt == null && share.revokedAt == null && (share.expiresAt == null || share.expiresAt > @now) LET collection = DOCUMENT(collections, share.sourceKey) LET scope = DOCUMENT(scopes, share.scopeKey) FILTER actor != null && actor.status == "active" && collection != null && collection.scopeKey == share.scopeKey && collection.deletedAt == null && scope != null && scope.deletedAt == null && actor.organizationId == scope.organizationKey LET requestedRole = share.permission == "collaborator" ? "collaborator" : "viewer" UPSERT { scopeKey: share.scopeKey, collectionKey: share.sourceKey, memberKey: @actorKey } INSERT { _key: @memberKey, scopeKey: share.scopeKey, collectionKey: share.sourceKey, memberKey: @actorKey, role: requestedRole, createdAt: @now } UPDATE { role: OLD.role == "owner" || OLD.role == "collaborator" ? OLD.role : requestedRole } IN collectionMembers RETURN NEW', { scopeKey, tokenHash, actorKey, memberKey, now }))[0]; return value ? parse(collectionMemberSchema, value) : null; }); },
    async getUserKeyByMemberKey(memberKey) { const value = (await all(database, 'LET membership = DOCUMENT(userOrganizations, @memberKey) FILTER membership != null RETURN membership.userId', { memberKey }))[0]; return typeof value === 'string' ? value : null; },
    async getInviteRecipientUserKey(inviteKey) { const value = (await all(database, 'LET invite = DOCUMENT(collectionInvites, @inviteKey) FILTER invite != null LET membership = invite.inviteeKey == null ? FIRST(FOR user IN users FILTER LOWER(user.email) == invite.email FOR candidate IN userOrganizations FILTER candidate.userId == user._key && candidate.status == "active" LIMIT 1 RETURN candidate) : DOCUMENT(userOrganizations, invite.inviteeKey) FILTER membership != null RETURN membership.userId', { inviteKey }))[0]; return typeof value === 'string' ? value : null; },
    async listCollectionUserKeys(collectionKey) { return await all(database, 'FOR member IN collectionMembers FILTER member.collectionKey == @collectionKey LET membership = DOCUMENT(userOrganizations, member.memberKey) FILTER membership != null && membership.status == "active" RETURN DISTINCT membership.userId', { collectionKey }) as string[]; },
    async listImageCollectionKeys(scopeKey, imageKeys) { return await all(database, 'FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey IN @imageKeys RETURN DISTINCT relation.collectionKey', { scopeKey, imageKeys }) as string[]; },
    listRedundantCollectionImages: (scopeKey, collectionKey) => redundantCollectionImages(database, scopeKey, collectionKey),
    deleteDuplicateImages(scopeKey, collectionKey, imageKeys, actorKey, now) { return transaction({ read: ['imageCaptions', 'visualIdentities', 'userOrganizations', 'scopes', 'scopeMembers', 'collectionMembers'], write: ['images', 'collectionImages', 'collections', 'imageIdentities'] }, async (tx) => {
      const owner = await all(tx, 'LET actor = DOCUMENT(userOrganizations, @actorKey) LET scope = DOCUMENT(scopes, @scopeKey) LET collection = DOCUMENT(collections, @collectionKey) LET scopeRole = FIRST(FOR member IN scopeMembers FILTER member.scopeKey == @scopeKey && member.userOrganizationKey == @actorKey && member.status == "active" LIMIT 1 RETURN member.role) LET collectionOwner = FIRST(FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @collectionKey && member.memberKey == @actorKey && member.role == "owner" LIMIT 1 RETURN member) FILTER actor != null && actor.status == "active" && scope != null && scope.deletedAt == null && actor.organizationId == scope.organizationKey && collection != null && collection.scopeKey == @scopeKey && collection.deletedAt == null FILTER actor.orgRole IN ["owner", "admin"] || scopeRole IN ["owner", "admin"] || collectionOwner != null RETURN true', { scopeKey, collectionKey, actorKey });
      if (!owner.length) return null;
      const allowed = new Set((await redundantCollectionImages(tx, scopeKey, collectionKey)).map(({ key }) => key));
      if (imageKeys.some((key) => !allowed.has(key))) return null;
      await tx.query('FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.collectionKey == @collectionKey && relation.imageKey IN @imageKeys REMOVE relation IN collectionImages', { imageKeys, scopeKey, collectionKey });
      await tx.query('FOR collection IN collections FILTER collection._key == @collectionKey && collection.scopeKey == @scopeKey && collection.coverImageKey IN @imageKeys UPDATE collection WITH { coverImageKey: null, updatedAt: @now } IN collections', { imageKeys, scopeKey, collectionKey, now });
      const deletedImageKeys = await all(tx, 'FOR image IN images FILTER image._key IN @imageKeys && image.scopeKey == @scopeKey && image.deletedAt == null LET collectionCount = LENGTH(FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == image._key LIMIT 1 RETURN 1) LET subjectCount = LENGTH(FOR relation IN imageIdentities FILTER relation.scopeKey == @scopeKey && relation.imageKey == image._key LET identity = DOCUMENT(visualIdentities, relation.identityKey) FILTER identity != null && identity.deletedAt == null LIMIT 1 RETURN 1) FILTER collectionCount == 0 && subjectCount == 0 UPDATE image WITH { deletedAt: @now, updatedAt: @now } IN images RETURN OLD._key', { imageKeys, scopeKey, now }) as string[];
      return { removedImageKeys: imageKeys, deletedImageKeys };
    }); },
    deleteImages(scopeKey, imageKeys, actorKey, now) { return transaction({ read: ['images', 'userOrganizations', 'scopes', 'scopeMembers', 'collectionMembers'], write: ['images', 'collectionImages', 'collections', 'imageIdentities', 'visualIdentities'] }, async (tx) => {
      const existing = await all(tx, 'LET actor = DOCUMENT(userOrganizations, @actorKey) LET scope = DOCUMENT(scopes, @scopeKey) LET scopeRole = FIRST(FOR member IN scopeMembers FILTER member.scopeKey == @scopeKey && member.userOrganizationKey == @actorKey && member.status == "active" LIMIT 1 RETURN member.role) FILTER actor != null && actor.status == "active" && scope != null && scope.deletedAt == null && actor.organizationId == scope.organizationKey FOR imageKey IN @imageKeys LET image = DOCUMENT(images, imageKey) FILTER image != null && image.scopeKey == @scopeKey && image.deletedAt == null LET relationCount = LENGTH(FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == imageKey RETURN 1) LET roles = (FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == imageKey FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == relation.collectionKey && member.memberKey == @actorKey RETURN member.role) FILTER actor.orgRole IN ["owner", "admin"] || scopeRole IN ["owner", "admin"] || "owner" IN roles || (image.createdByKey == @actorKey && (relationCount == 0 || "collaborator" IN roles || "member" IN roles)) RETURN imageKey', { scopeKey, imageKeys, actorKey });
      if (existing.length !== imageKeys.length) return null;
      await tx.query('FOR collection IN collections FILTER collection.scopeKey == @scopeKey && collection.deletedAt == null && collection.coverImageKey IN @imageKeys UPDATE collection WITH { coverImageKey: null, updatedAt: @now } IN collections', { scopeKey, imageKeys, now });
      await tx.query('FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey IN @imageKeys REMOVE relation IN collectionImages', { scopeKey, imageKeys });
      await tx.query('FOR relation IN imageIdentities FILTER relation.scopeKey == @scopeKey && relation.imageKey IN @imageKeys REMOVE relation IN imageIdentities', { scopeKey, imageKeys });
      await tx.query('FOR identity IN visualIdentities FILTER identity.scopeKey == @scopeKey && identity.referenceImageKey IN @imageKeys LET replacement = FIRST(FOR relation IN imageIdentities FILTER relation.scopeKey == @scopeKey && relation.identityKey == identity._key && relation.imageKey NOT IN @imageKeys LET image = DOCUMENT(images, relation.imageKey) FILTER image != null && image.scopeKey == @scopeKey && image.deletedAt == null SORT relation.isReference DESC, relation.confidence DESC, relation.createdAt ASC RETURN relation.imageKey) LET patch = replacement == null ? { deletedAt: @now, updatedAt: @now } : { referenceImageKey: replacement, updatedAt: @now } UPDATE identity WITH patch IN visualIdentities', { scopeKey, imageKeys, now });
      await tx.query('FOR image IN images FILTER image._key IN @imageKeys && image.scopeKey == @scopeKey && image.deletedAt == null UPDATE image WITH { deletedAt: @now, updatedAt: @now } IN images', { scopeKey, imageKeys, now });
      return { deletedImageKeys: imageKeys };
    }); },
    transferCollectionImages(input) { return transaction({ read: ['images', 'collectionMembers', 'userOrganizations', 'scopes', 'scopeMembers'], write: ['collections', 'collectionImages'] }, async (tx) => {
       const source = await all(tx, 'LET actor = DOCUMENT(userOrganizations, @actorKey) LET scope = DOCUMENT(scopes, @scopeKey) LET scopeRole = FIRST(FOR item IN scopeMembers FILTER item.scopeKey == @scopeKey && item.userOrganizationKey == @actorKey && item.status == "active" LIMIT 1 RETURN item.role) FILTER actor != null && actor.status == "active" && scope != null && scope.deletedAt == null && actor.organizationId == scope.organizationKey LET elevated = actor.orgRole IN ["owner", "admin"] || scopeRole IN ["owner", "admin"] FOR imageKey IN @imageKeys LET image = DOCUMENT(images, imageKey) LET relation = FIRST(FOR candidate IN collectionImages FILTER candidate.scopeKey == @scopeKey && candidate.collectionKey == @sourceCollectionKey && candidate.imageKey == imageKey LIMIT 1 RETURN candidate) LET member = FIRST(FOR candidate IN collectionMembers FILTER candidate.scopeKey == @scopeKey && candidate.collectionKey == @sourceCollectionKey && candidate.memberKey == @actorKey LIMIT 1 RETURN candidate) FILTER image != null && image.scopeKey == @scopeKey && image.deletedAt == null && relation != null FILTER elevated || member != null && (member.role == "owner" || (member.role IN ["collaborator", "member"] && image.createdByKey == @actorKey)) RETURN imageKey', { imageKeys: input.imageKeys, scopeKey: input.scopeKey, sourceCollectionKey: input.sourceCollectionKey, actorKey: input.actorKey });
      if (source.length !== input.imageKeys.length) return { status: 'selection-changed' as const };
       const destinations = await all(tx, 'LET actor = DOCUMENT(userOrganizations, @actorKey) LET scope = DOCUMENT(scopes, @scopeKey) LET scopeRole = FIRST(FOR item IN scopeMembers FILTER item.scopeKey == @scopeKey && item.userOrganizationKey == @actorKey && item.status == "active" LIMIT 1 RETURN item.role) FILTER actor != null && actor.status == "active" && scope != null && scope.deletedAt == null && actor.organizationId == scope.organizationKey LET elevated = actor.orgRole IN ["owner", "admin"] || scopeRole IN ["owner", "admin"] FOR collectionKey IN @collectionKeys LET collection = DOCUMENT(collections, collectionKey) LET member = FIRST(FOR candidate IN collectionMembers FILTER candidate.scopeKey == @scopeKey && candidate.collectionKey == collectionKey && candidate.memberKey == @actorKey LIMIT 1 RETURN candidate) FILTER collection != null && collection.scopeKey == @scopeKey && collection.deletedAt == null FILTER elevated || member != null && member.role IN ["owner", "collaborator", "member"] RETURN collectionKey', { collectionKeys: input.destinationCollectionKeys, scopeKey: input.scopeKey, actorKey: input.actorKey });
      if (destinations.length !== input.destinationCollectionKeys.length) return { status: 'destination-forbidden' as const };
      let createdRelationCount = 0;
      for (const collectionKey of input.destinationCollectionKeys) for (const imageKey of input.imageKeys) {
        const relation = collectionImageSchema.parse({ key: newId(), scopeKey: input.scopeKey, collectionKey, imageKey, addedByKey: input.actorKey, createdAt: input.now });
        const created = await all(tx, 'UPSERT { scopeKey: @scopeKey, collectionKey: @collectionKey, imageKey: @imageKey } INSERT @relation UPDATE {} IN collectionImages RETURN OLD == null', { scopeKey: input.scopeKey, collectionKey, imageKey, relation: toArangoDoc(relation) });
        if (created[0] === true) createdRelationCount += 1;
      }
      if (input.mode === 'move') { await tx.query('FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.collectionKey == @sourceCollectionKey && relation.imageKey IN @imageKeys REMOVE relation IN collectionImages', { scopeKey: input.scopeKey, sourceCollectionKey: input.sourceCollectionKey, imageKeys: input.imageKeys }); await tx.query('FOR collection IN collections FILTER collection._key == @sourceCollectionKey && collection.scopeKey == @scopeKey && collection.coverImageKey IN @imageKeys UPDATE collection WITH { coverImageKey: null, updatedAt: @now } IN collections', { scopeKey: input.scopeKey, sourceCollectionKey: input.sourceCollectionKey, imageKeys: input.imageKeys, now: input.now }); }
      return { status: 'ok' as const, createdRelationCount };
    }); },
    insertUpload: insertGalleryUpload,
    getUpload: getGalleryUploadById,
    async listRecoverableUploads() { return (await all(database, 'FOR upload IN galleryUploads FILTER upload.status IN ["queued", "processing"] SORT upload.updatedAt ASC, upload._key ASC RETURN upload', {})).map((value) => parse(galleryUploadSchema, value)); },
    updateUpload: updateGalleryUpload,
    failUpload(uploadKey, scopeKey, errorCode, now) { return transaction({ read: ['images'], write: ['galleryUploads', 'images', 'collectionImages', 'collections', 'imageIdentities', 'visualIdentities'] }, async (tx) => {
      const updated = await all(tx, 'FOR upload IN galleryUploads FILTER upload._key == @uploadKey && upload.scopeKey == @scopeKey && upload.status != "completed" LIMIT 1 UPDATE upload WITH { status: "failed", errorCode: @errorCode, updatedAt: @now } IN galleryUploads RETURN OLD.imageKey', { uploadKey, scopeKey, errorCode, now }) as string[];
      if (!updated.length) return false;
      const imageKey = updated[0]!;
      await tx.query('FOR collection IN collections FILTER collection.scopeKey == @scopeKey && collection.deletedAt == null && collection.coverImageKey == @imageKey UPDATE collection WITH { coverImageKey: null, updatedAt: @now } IN collections', { scopeKey, imageKey, now });
      await tx.query('FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == @imageKey REMOVE relation IN collectionImages', { scopeKey, imageKey });
      await tx.query('FOR relation IN imageIdentities FILTER relation.scopeKey == @scopeKey && relation.imageKey == @imageKey REMOVE relation IN imageIdentities', { scopeKey, imageKey });
      await tx.query('FOR identity IN visualIdentities FILTER identity.scopeKey == @scopeKey && identity.referenceImageKey == @imageKey LET replacement = FIRST(FOR relation IN imageIdentities FILTER relation.scopeKey == @scopeKey && relation.identityKey == identity._key && relation.imageKey != @imageKey LET image = DOCUMENT(images, relation.imageKey) FILTER image != null && image.scopeKey == @scopeKey && image.deletedAt == null SORT relation.isReference DESC, relation.confidence DESC, relation.createdAt ASC RETURN relation.imageKey) LET patch = replacement == null ? { deletedAt: @now, updatedAt: @now } : { referenceImageKey: replacement, updatedAt: @now } UPDATE identity WITH patch IN visualIdentities', { scopeKey, imageKey, now });
      await tx.query('FOR image IN images FILTER image._key == @imageKey && image.scopeKey == @scopeKey && image.deletedAt == null UPDATE image WITH { deletedAt: @now, updatedAt: @now } IN images', { scopeKey, imageKey, now });
      // Normal image deletion retains sanitized media behind the soft-deleted
      // record so future trash/recovery behavior can restore it.
      return true;
    }); },
    searchAccessibleImages: (input) => searchAccessibleImages(input, database),
    async listMatchingIdentityNames(scopeKey, query) { return (await all(database, 'FOR identity IN visualIdentities FILTER identity.scopeKey == @scopeKey && identity.deletedAt == null FILTER CONTAINS(LOWER(@query), LOWER(identity.name)) RETURN identity', { scopeKey, query })).map((value) => parse(visualIdentitySchema, value)); },
    async listIdentityMatches(scopeKey, embedding) { return await all(database, 'FOR identity IN visualIdentities FILTER identity.scopeKey == @scopeKey && identity.deletedAt == null FILTER IS_ARRAY(identity.embedding) && LENGTH(identity.embedding) == @dimensions LET confidence = COSINE_SIMILARITY(identity.embedding, @embedding) FILTER IS_NUMBER(confidence) && confidence >= 0.82 RETURN { identityKey: identity._key, confidence }', { scopeKey, embedding, dimensions: embedding.length }) as Array<{ identityKey: string; confidence: number }>; },
    async persistIdentityMatches(scopeKey, identityKey, matches) { if (!matches.length) return; const now = new Date().toISOString(); await transaction(['imageIdentities'], async (tx) => { for (const match of matches) { const relation = imageIdentitySchema.parse({ key: newId(), scopeKey, imageKey: match.imageKey, identityKey, confidence: match.confidence, isReference: false, createdAt: now }); await tx.query('UPSERT { scopeKey: @scopeKey, identityKey: @identityKey, imageKey: @imageKey } INSERT @relation UPDATE { confidence: MAX([OLD.confidence, @confidence]) } IN imageIdentities', { scopeKey, identityKey, imageKey: match.imageKey, confidence: match.confidence, relation: toArangoDoc(relation) }); } }); },
    async setImageFavorite(scopeKey, imageKey, actorKey, isFavorite, now) { const value = await all(database, 'LET actor = DOCUMENT(userOrganizations, @actorKey) LET scope = DOCUMENT(scopes, @scopeKey) LET image = DOCUMENT(images, @imageKey) LET scopeRole = FIRST(FOR member IN scopeMembers FILTER member.scopeKey == @scopeKey && member.userOrganizationKey == @actorKey && member.status == "active" LIMIT 1 RETURN member.role) LET roles = (FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == @imageKey FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == relation.collectionKey && member.memberKey == @actorKey RETURN member.role) LET relationCount = LENGTH(FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == @imageKey RETURN 1) FILTER actor != null && actor.status == "active" && scope != null && scope.deletedAt == null && actor.organizationId == scope.organizationKey && image != null && image.scopeKey == @scopeKey && image.deletedAt == null FILTER actor.orgRole IN ["owner", "admin"] || scopeRole IN ["owner", "admin"] || "owner" IN roles || (image.createdByKey == @actorKey && (relationCount == 0 || "collaborator" IN roles || "member" IN roles)) UPDATE image WITH { isFavorite: @isFavorite, updatedAt: @now } IN images RETURN NEW', { scopeKey, imageKey, actorKey, isFavorite, now }); return value[0] ? parse(imageSchema, value[0]) : null; },
    async updateImageDetails(scopeKey, imageKey, actorKey, filename, isFavorite, embedding, now) { const value = await all(database, 'LET actor = DOCUMENT(userOrganizations, @actorKey) LET scope = DOCUMENT(scopes, @scopeKey) LET image = DOCUMENT(images, @imageKey) LET scopeRole = FIRST(FOR member IN scopeMembers FILTER member.scopeKey == @scopeKey && member.userOrganizationKey == @actorKey && member.status == "active" LIMIT 1 RETURN member.role) LET roles = (FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == @imageKey FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == relation.collectionKey && member.memberKey == @actorKey RETURN member.role) LET relationCount = LENGTH(FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == @imageKey RETURN 1) FILTER actor != null && actor.status == "active" && scope != null && scope.deletedAt == null && actor.organizationId == scope.organizationKey && image != null && image.scopeKey == @scopeKey && image.deletedAt == null FILTER actor.orgRole IN ["owner", "admin"] || scopeRole IN ["owner", "admin"] || "owner" IN roles || (image.createdByKey == @actorKey && (relationCount == 0 || "collaborator" IN roles || "member" IN roles)) UPDATE image WITH { filename: @filename, isFavorite: @isFavorite, embedding: @embedding, updatedAt: @now } IN images RETURN NEW', { scopeKey, imageKey, actorKey, filename, isFavorite, embedding, now }); return value[0] ? parse(imageSchema, value[0]) : null; },
    async updateCollectionDetails(scopeKey, collectionKey, name, isFavorite, embedding, now) { const value = await all(database, 'FOR collection IN collections FILTER collection._key == @collectionKey && collection.scopeKey == @scopeKey && collection.deletedAt == null LIMIT 1 UPDATE collection WITH { name: @name, isFavorite: @isFavorite, embedding: @embedding, updatedAt: @now } IN collections RETURN NEW', { scopeKey, collectionKey, name, isFavorite, embedding, now }); return value[0] ? parse(collectionSchema, value[0]) : null; },
    deleteCollection(scopeKey, collectionKey, now) { return transaction({ read: ['collections'], write: ['collections', 'collectionImages', 'collectionMembers'] }, async (tx) => Boolean((await all(tx, 'FOR collection IN collections FILTER collection._key == @collectionKey && collection.scopeKey == @scopeKey && collection.deletedAt == null LIMIT 1 UPDATE collection WITH { deletedAt: @now, updatedAt: @now } IN collections LET removed = (FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.collectionKey == @collectionKey REMOVE relation IN collectionImages RETURN 1) LET members = (FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @collectionKey REMOVE member IN collectionMembers RETURN 1) RETURN NEW._key', { scopeKey, collectionKey, now }))[0])); },
    listSubjects: (scopeKey, includeDeleted) => subjectRows('FOR identity IN visualIdentities FILTER identity.scopeKey == @scopeKey FILTER @includeDeleted || identity.deletedAt == null LET reference = DOCUMENT(images, identity.referenceImageKey) FILTER reference != null && reference.scopeKey == @scopeKey && reference.deletedAt == null LET imageCount = LENGTH(FOR relation IN imageIdentities FILTER relation.scopeKey == @scopeKey && relation.identityKey == identity._key LET image = DOCUMENT(images, relation.imageKey) FILTER image != null && image.deletedAt == null RETURN 1) SORT identity.deletedAt == null DESC, identity.name ASC, identity._key ASC RETURN { identity, reference, imageCount }', { scopeKey, includeDeleted }),
    async getSubject(scopeKey, identityKey, includeDeleted) { return (await subjectRows('FOR identity IN visualIdentities FILTER identity._key == @identityKey && identity.scopeKey == @scopeKey FILTER @includeDeleted || identity.deletedAt == null LET reference = DOCUMENT(images, identity.referenceImageKey) FILTER reference != null && reference.scopeKey == @scopeKey && reference.deletedAt == null LET imageCount = LENGTH(FOR relation IN imageIdentities FILTER relation.scopeKey == @scopeKey && relation.identityKey == identity._key LET image = DOCUMENT(images, relation.imageKey) FILTER image != null && image.deletedAt == null RETURN 1) LIMIT 1 RETURN { identity, reference, imageCount }', { scopeKey, identityKey, includeDeleted }))[0] ?? null; },
    createSubject(identity, relations, referenceImageKeys) { return transaction({ read: ['images'], write: ['visualIdentities', 'imageIdentities'] }, async (tx) => { const references = await all(tx, 'FOR image IN images FILTER image._key IN @imageKeys && image.scopeKey == @scopeKey && image.deletedAt == null RETURN image._key', { imageKeys: referenceImageKeys, scopeKey: identity.scopeKey }); if (references.length !== referenceImageKeys.length) return false; await tx.query('INSERT @identity INTO visualIdentities', { identity: toArangoDoc(identity) }); for (const relation of relations) await tx.query('INSERT @relation INTO imageIdentities', { relation: toArangoDoc(relation) }); return true; }); },
    async listSubjectImages(scopeKey, identityKey, collectionKey) { return (await all(database, 'FOR relation IN imageIdentities FILTER relation.scopeKey == @scopeKey && relation.identityKey == @identityKey LET image = DOCUMENT(images, relation.imageKey) FILTER image != null && image.scopeKey == @scopeKey && image.deletedAt == null FILTER @collectionKey == null || LENGTH(FOR collectionImage IN collectionImages FILTER collectionImage.scopeKey == @scopeKey && collectionImage.collectionKey == @collectionKey && collectionImage.imageKey == image._key LIMIT 1 RETURN 1) > 0 SORT relation.confidence DESC, image.createdAt DESC RETURN { image, confidence: relation.confidence }', { scopeKey, identityKey, collectionKey: collectionKey ?? null }) as Array<{ image: unknown; confidence: number }>).map((row) => ({ image: parse(imageSchema, row.image), confidence: row.confidence })); },
    setSubjectDeleted(scopeKey, identityKey, deleted, now) { return transaction({ read: ['images'], write: ['visualIdentities'] }, async (tx) => Boolean((await all(tx, 'FOR identity IN visualIdentities FILTER identity._key == @identityKey && identity.scopeKey == @scopeKey LET reference = DOCUMENT(images, identity.referenceImageKey) FILTER @deleted || (reference != null && reference.scopeKey == @scopeKey && reference.deletedAt == null) LIMIT 1 UPDATE identity WITH { deletedAt: @deletedAt, updatedAt: @now } IN visualIdentities RETURN NEW', { identityKey, scopeKey, deleted, deletedAt: deleted ? now : null, now }))[0])); },
  };
}

let defaultRepository: GalleryRepository | undefined;
export function getDefaultGalleryRepository() { return defaultRepository ??= createGalleryRepository(); }
