import { db, withTransaction } from '@/lib/db/client';
import { toArangoDoc, withArangoKey } from '@/lib/db/base';
import { imageSchema } from '@/lib/db/images.node';
import { collectionSchema } from '@/lib/db/collections.node';
import { collectionImageSchema } from '@/lib/db/collection-images.node';
import { collectionMemberSchema } from '@/lib/db/collection-members.node';
import { collectionInviteSchema, type CollectionInvite } from '@/lib/db/collection-invites.node';
import { tagSchema } from '@/lib/db/tags.node';
import { tagAssignmentSchema } from '@/lib/db/tag-assignments.node';
import { shareSchema } from '@/lib/db/shares.node';

export interface GalleryDatabase { query(query: string, bindVars?: Record<string, unknown>): Promise<{ all(): Promise<unknown[]> }>; }
export type GalleryTransactionRunner = <T>(operation: (database: GalleryDatabase) => Promise<T>) => Promise<T>;
type Image = ReturnType<typeof imageSchema.parse>;
type Collection = ReturnType<typeof collectionSchema.parse>;
type CollectionImage = ReturnType<typeof collectionImageSchema.parse>;
type CollectionMember = ReturnType<typeof collectionMemberSchema.parse>;
type Tag = ReturnType<typeof tagSchema.parse>;
type TagAssignment = ReturnType<typeof tagAssignmentSchema.parse>;
type GlobalShare = ReturnType<typeof shareSchema.parse>;
const transactionCollections = ['images', 'collections', 'collectionImages', 'collectionMembers', 'collectionInvites', 'tags', 'tagAssignments', 'shares', 'documents', 'scopes', 'scopeMembers', 'userOrganizations', 'users'] as const;
const defaultTransactionRunner: GalleryTransactionRunner = (operation) => withTransaction([...transactionCollections], (transaction) => operation(transaction));

function parse<T>(schema: { parse(value: unknown): T }, value: unknown): T { return schema.parse(withArangoKey(value as Record<string, unknown>)); }
async function one(database: GalleryDatabase, query: string, bindVars: Record<string, unknown>): Promise<unknown | null> { return (await (await database.query(query, bindVars)).all())[0] ?? null; }
const activeActor = `LET actorMembership = DOCUMENT(userOrganizations, @actorKey) LET actorScope = DOCUMENT(scopes, @scopeKey) FILTER actorMembership != null && actorMembership.status == "active" FILTER actorScope != null && actorScope.deletedAt == null && actorMembership.organizationId == actorScope.organizationKey`;

export interface GalleryRepository {
  getImage(scopeKey: string, imageKey: string): Promise<Image | null>;
  getCollection(scopeKey: string, collectionKey: string): Promise<Collection | null>;
  ownsImage(scopeKey: string, imageKey: string, ownerKey: string): Promise<boolean>;
  canAccessImage(scopeKey: string, imageKey: string, actorKey: string): Promise<boolean>;
  ownsCollection(scopeKey: string, collectionKey: string, ownerKey: string): Promise<boolean>;
  addImageToCollection(relation: CollectionImage): Promise<CollectionImage>;
  copyImageToCollection(relation: CollectionImage): Promise<CollectionImage>;
  moveImageBetweenCollections(sourceCollectionKey: string, relation: CollectionImage): Promise<CollectionImage>;
  leaveCollection(scopeKey: string, collectionKey: string, actorKey: string): Promise<boolean>;
  createCollectionInvite(invite: CollectionInvite, replay: { requestHash: string; responseCiphertext: string }): Promise<{ invite: CollectionInvite; requestHash: string; responseCiphertext: string }>;
  getAcceptedCollectionInviteMembership(tokenHash: string, recipientKey: string): Promise<CollectionMember | null>;
  acceptCollectionInvite(input: { tokenHash: string; recipientKey: string; now: string; memberKey: string }): Promise<CollectionMember | null>;
  createTagAssignment(assignment: TagAssignment, actorKey: string): Promise<TagAssignment | null>;
  setCollectionCoverImage(scopeKey: string, collectionKey: string, imageKey: string, ownerKey: string, now: string): Promise<Collection | null>;
  createGlobalShare(share: GlobalShare, ownerKey: string, replay: { requestHash: string; responseCiphertext: string }): Promise<{ share: GlobalShare; requestHash: string; responseCiphertext: string } | null>;
  getActiveGlobalShareByTokenHash(tokenHash: string, at: string): Promise<GlobalShare | null>;
  getTag(scopeKey: string, tagKey: string): Promise<Tag | null>;
}

export function createGalleryRepository(database: GalleryDatabase = db, runTransaction: GalleryTransactionRunner = defaultTransactionRunner): GalleryRepository {
  const add = async (relation: CollectionImage) => {
    const valid = collectionImageSchema.parse(relation);
    const value = await one(database, `LET image = DOCUMENT(images, @imageKey) LET collection = DOCUMENT(collections, @collectionKey) ${activeActor} LET actor = FIRST(FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @collectionKey && member.memberKey == @addedByKey LIMIT 1 RETURN member) LET sourceAccess = image != null && image.ownerKey == @addedByKey ? true : LENGTH(FOR link IN collectionImages FILTER link.scopeKey == @scopeKey && link.imageKey == @imageKey LET sourceCollection = DOCUMENT(collections, link.collectionKey) FILTER sourceCollection != null && sourceCollection.deletedAt == null FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == link.collectionKey && member.memberKey == @addedByKey LIMIT 1 RETURN 1) > 0 FILTER image != null && image.deletedAt == null && collection != null && collection.deletedAt == null FILTER image.scopeKey == @scopeKey && collection.scopeKey == @scopeKey && actor != null && sourceAccess UPSERT { scopeKey: @scopeKey, collectionKey: @collectionKey, imageKey: @imageKey } INSERT @relation UPDATE {} IN collectionImages RETURN NEW`, { scopeKey: valid.scopeKey, collectionKey: valid.collectionKey, imageKey: valid.imageKey, addedByKey: valid.addedByKey, actorKey: valid.addedByKey, relation: toArangoDoc(valid) });
    if (!value) throw new GalleryReferenceError('Source image access, destination membership, and live same-scope resources are required');
    return parse(collectionImageSchema, value);
  };
  const owns = async (kind: 'image' | 'collection', scopeKey: string, resourceKey: string, ownerKey: string) => Boolean(await one(database, kind === 'collection'
    ? `LET target = DOCUMENT(collections, @resourceKey) ${activeActor} FILTER target != null && target.scopeKey == @scopeKey && target.deletedAt == null FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @resourceKey && member.memberKey == @ownerKey && member.role == "owner" LIMIT 1 RETURN true`
    : `LET target = DOCUMENT(images, @resourceKey) ${activeActor} FILTER target != null && target.scopeKey == @scopeKey && target.deletedAt == null FILTER target.ownerKey == @ownerKey || LENGTH(FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == @resourceKey LET collection = DOCUMENT(collections, relation.collectionKey) FILTER collection != null && collection.deletedAt == null FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == relation.collectionKey && member.memberKey == @ownerKey && member.role == "owner" LIMIT 1 RETURN 1) > 0 RETURN true`, { scopeKey, resourceKey, ownerKey, actorKey: ownerKey }));
  return {
    async getImage(scopeKey, imageKey) { const value = await one(database, 'FOR image IN images FILTER image._key == @imageKey && image.scopeKey == @scopeKey && image.deletedAt == null LIMIT 1 RETURN image', { scopeKey, imageKey }); return value ? parse(imageSchema, value) : null; },
    async getCollection(scopeKey, collectionKey) { const value = await one(database, 'FOR collection IN collections FILTER collection._key == @collectionKey && collection.scopeKey == @scopeKey && collection.deletedAt == null LIMIT 1 RETURN collection', { scopeKey, collectionKey }); return value ? parse(collectionSchema, value) : null; },
    ownsImage: (scopeKey, imageKey, ownerKey) => owns('image', scopeKey, imageKey, ownerKey),
    canAccessImage: async (scopeKey, imageKey, actorKey) => Boolean(await one(database, `LET image = DOCUMENT(images, @imageKey) ${activeActor} FILTER image != null && image.scopeKey == @scopeKey && image.deletedAt == null FILTER image.ownerKey == @actorKey || LENGTH(FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == @imageKey LET collection = DOCUMENT(collections, relation.collectionKey) FILTER collection != null && collection.deletedAt == null FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == relation.collectionKey && member.memberKey == @actorKey LIMIT 1 RETURN 1) > 0 RETURN true`, { scopeKey, imageKey, actorKey })),
    ownsCollection: (scopeKey, collectionKey, ownerKey) => owns('collection', scopeKey, collectionKey, ownerKey),
    addImageToCollection: add, copyImageToCollection: add,
    moveImageBetweenCollections(sourceCollectionKey, relation) { return runTransaction(async (transaction) => { const bound = createGalleryRepository(transaction, runTransaction); const source = await one(transaction, `${activeActor} LET image = DOCUMENT(images, @imageKey) LET current = FIRST(FOR link IN collectionImages FILTER link.scopeKey == @scopeKey && link.collectionKey == @sourceCollectionKey && link.imageKey == @imageKey LIMIT 1 RETURN link) LET sourceMember = FIRST(FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @sourceCollectionKey && member.memberKey == @actorKey LIMIT 1 RETURN member) FILTER image != null && current != null && (image.ownerKey == @actorKey || sourceMember != null) RETURN current`, { scopeKey: relation.scopeKey, sourceCollectionKey, imageKey: relation.imageKey, actorKey: relation.addedByKey }); if (!source) throw new GalleryReferenceError('Source collection does not contain an accessible image'); const destination = await bound.addImageToCollection(relation); if (sourceCollectionKey !== relation.collectionKey) { await transaction.query('FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.collectionKey == @sourceCollectionKey && relation.imageKey == @imageKey REMOVE relation IN collectionImages', { scopeKey: relation.scopeKey, sourceCollectionKey, imageKey: relation.imageKey }); await transaction.query('FOR collection IN collections FILTER collection._key == @sourceCollectionKey && collection.scopeKey == @scopeKey && collection.coverImageKey == @imageKey UPDATE collection WITH { coverImageKey: null, updatedAt: @now } IN collections OPTIONS { keepNull: false }', { scopeKey: relation.scopeKey, sourceCollectionKey, imageKey: relation.imageKey, now: relation.createdAt }); } return destination; }); },
    leaveCollection(scopeKey, collectionKey, actorKey) { return runTransaction(async (transaction) => Boolean(await one(transaction, `${activeActor} LET member = FIRST(FOR candidate IN collectionMembers FILTER candidate.scopeKey == @scopeKey && candidate.collectionKey == @collectionKey && candidate.memberKey == @actorKey LIMIT 1 RETURN candidate) LET otherOwners = member == null ? 0 : LENGTH(FOR candidate IN collectionMembers FILTER candidate.scopeKey == @scopeKey && candidate.collectionKey == @collectionKey && candidate.role == "owner" && candidate.memberKey != @actorKey LIMIT 1 RETURN 1) FILTER member != null && (member.role != "owner" || otherOwners > 0) REMOVE member IN collectionMembers RETURN true`, { scopeKey, collectionKey, actorKey }))); },
    createCollectionInvite(invite, replay) { return runTransaction(async (transaction) => { const valid = collectionInviteSchema.parse(invite); const value = await one(transaction, `LET collection = DOCUMENT(collections, @collectionKey) ${activeActor} LET owner = FIRST(FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @collectionKey && member.memberKey == @invitedByKey && member.role == "owner" LIMIT 1 RETURN member) FILTER collection != null && collection.scopeKey == @scopeKey && collection.deletedAt == null && owner != null UPSERT { _key: @inviteKey } INSERT MERGE(@invite, @replay) UPDATE {} IN collectionInvites RETURN NEW`, { scopeKey: valid.scopeKey, collectionKey: valid.collectionKey, invitedByKey: valid.invitedByKey, actorKey: valid.invitedByKey, inviteKey: valid.key, invite: toArangoDoc(valid), replay }); if (!value) throw new GalleryReferenceError('Collection ownership required'); const raw = withArangoKey(value as Record<string, unknown>) as Record<string, unknown>; return { invite: collectionInviteSchema.parse(raw), requestHash: String(raw.requestHash), responseCiphertext: String(raw.responseCiphertext) }; }); },
    async getAcceptedCollectionInviteMembership(tokenHash, recipientKey) { const value = await one(database, 'LET recipientMembership = DOCUMENT(userOrganizations, @recipientKey) LET recipient = recipientMembership == null ? null : DOCUMENT(users, recipientMembership.userId) FOR invite IN collectionInvites FILTER invite.tokenHash == @tokenHash && invite.acceptedAt != null && invite.revokedAt == null FILTER invite.inviteeKey == @recipientKey || (invite.email != null && recipient != null && invite.email == LOWER(recipient.email)) LET member = FIRST(FOR candidate IN collectionMembers FILTER candidate.scopeKey == invite.scopeKey && candidate.collectionKey == invite.collectionKey && candidate.memberKey == @recipientKey LIMIT 1 RETURN candidate) FILTER member != null LIMIT 1 RETURN member', { tokenHash, recipientKey }); return value ? parse(collectionMemberSchema, value) : null; },
    acceptCollectionInvite({ tokenHash, recipientKey, now, memberKey }) { return runTransaction(async (transaction) => { const inviteValue = await one(transaction, 'LET recipientMembership = DOCUMENT(userOrganizations, @recipientKey) LET recipient = recipientMembership == null ? null : DOCUMENT(users, recipientMembership.userId) FOR invite IN collectionInvites FILTER invite.tokenHash == @tokenHash FILTER invite.inviteeKey == @recipientKey || (invite.email != null && recipient != null && invite.email == LOWER(recipient.email)) FILTER invite.acceptedAt == null && invite.revokedAt == null && invite.expiresAt > @now LET collection = DOCUMENT(collections, invite.collectionKey) LET scope = DOCUMENT(scopes, invite.scopeKey) LET inviter = FIRST(FOR owner IN collectionMembers FILTER owner.scopeKey == invite.scopeKey && owner.collectionKey == invite.collectionKey && owner.memberKey == invite.invitedByKey && owner.role == "owner" LIMIT 1 RETURN owner) FILTER collection != null && collection.scopeKey == invite.scopeKey && collection.deletedAt == null && inviter != null FILTER recipientMembership != null && recipientMembership.status == "active" && scope != null && scope.deletedAt == null && recipientMembership.organizationId == scope.organizationKey LIMIT 1 RETURN invite', { tokenHash, recipientKey, now }); if (!inviteValue) return null; const invite = parse(collectionInviteSchema, inviteValue); const member = collectionMemberSchema.parse({ key: memberKey, scopeKey: invite.scopeKey, collectionKey: invite.collectionKey, memberKey: recipientKey, createdAt: now }); const saved = await one(transaction, 'UPSERT { scopeKey: @scopeKey, collectionKey: @collectionKey, memberKey: @memberKey } INSERT @member UPDATE {} IN collectionMembers RETURN NEW', { scopeKey: member.scopeKey, collectionKey: member.collectionKey, memberKey: member.memberKey, member: toArangoDoc(member) }); await transaction.query('UPDATE @inviteKey WITH { acceptedAt: @now, updatedAt: @now } IN collectionInvites', { inviteKey: invite.key, now }); return parse(collectionMemberSchema, saved); }); },
    async createTagAssignment(assignment, actorKey) { const valid = tagAssignmentSchema.parse(assignment); const targetCollection = valid.sourceType === 'document' ? 'documents' : valid.sourceType === 'image' ? 'images' : 'collections'; const value = await one(database, `LET tag = DOCUMENT(tags, @tagKey) LET target = DOCUMENT(${targetCollection}, @sourceKey) LET scope = DOCUMENT(scopes, @scopeKey) LET membership = DOCUMENT(userOrganizations, @actorKey) LET active = scope != null && membership != null && membership.status == "active" && membership.organizationId == scope.organizationKey LET elevated = active && membership.orgRole IN ["owner", "admin"] LET scoped = LENGTH(FOR member IN scopeMembers FILTER member.scopeKey == @scopeKey && member.userOrganizationKey == @actorKey && member.status == "active" LIMIT 1 RETURN 1) > 0 LET gallery = @sourceType == "collection" ? LENGTH(FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @sourceKey && member.memberKey == @actorKey LIMIT 1 RETURN 1) > 0 : @sourceType == "image" ? LENGTH(FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == @sourceKey FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == relation.collectionKey && member.memberKey == @actorKey LIMIT 1 RETURN 1) > 0 : false FILTER tag != null && tag.scopeKey == @scopeKey && tag.deletedAt == null && target != null && target.scopeKey == @scopeKey && target.deletedAt == null FILTER active && (gallery || scoped || elevated) UPSERT { scopeKey: @scopeKey, tagKey: @tagKey, sourceType: @sourceType, sourceKey: @sourceKey } INSERT @assignment UPDATE { source: @source } IN tagAssignments RETURN NEW`, { scopeKey: valid.scopeKey, tagKey: valid.tagKey, sourceType: valid.sourceType, sourceKey: valid.sourceKey, source: valid.source, actorKey, assignment: toArangoDoc(valid) }); return value ? parse(tagAssignmentSchema, value) : null; },
    async setCollectionCoverImage(scopeKey, collectionKey, imageKey, ownerKey, now) { const value = await one(database, `LET image = DOCUMENT(images, @imageKey) ${activeActor} LET relation = FIRST(FOR link IN collectionImages FILTER link.scopeKey == @scopeKey && link.collectionKey == @collectionKey && link.imageKey == @imageKey LIMIT 1 RETURN link) FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @collectionKey && member.memberKey == @ownerKey && member.role == "owner" FOR collection IN collections FILTER collection._key == @collectionKey && collection.scopeKey == @scopeKey && collection.deletedAt == null FILTER image != null && image.scopeKey == @scopeKey && image.deletedAt == null && relation != null LIMIT 1 UPDATE collection WITH { coverImageKey: @imageKey, updatedAt: @now } IN collections RETURN NEW`, { scopeKey, collectionKey, imageKey, ownerKey, actorKey: ownerKey, now }); return value ? parse(collectionSchema, value) : null; },
    async createGlobalShare(share, ownerKey, replay) { const valid = shareSchema.parse(share); if (valid.sourceType === 'document') return null; const targetCollection = valid.sourceType === 'image' ? 'images' : 'collections'; const value = await one(database, `LET target = DOCUMENT(${targetCollection}, @sourceKey) ${activeActor} LET owned = @sourceType == "collection" ? LENGTH(FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == @sourceKey && member.memberKey == @ownerKey && member.role == "owner" LIMIT 1 RETURN 1) > 0 : target.ownerKey == @ownerKey || LENGTH(FOR relation IN collectionImages FILTER relation.scopeKey == @scopeKey && relation.imageKey == @sourceKey LET collection = DOCUMENT(collections, relation.collectionKey) FILTER collection != null && collection.deletedAt == null FOR member IN collectionMembers FILTER member.scopeKey == @scopeKey && member.collectionKey == relation.collectionKey && member.memberKey == @ownerKey && member.role == "owner" LIMIT 1 RETURN 1) > 0 FILTER target != null && target.scopeKey == @scopeKey && target.deletedAt == null && owned UPSERT { _key: @shareKey } INSERT MERGE(@share, @replay) UPDATE {} IN shares RETURN NEW`, { scopeKey: valid.scopeKey, sourceType: valid.sourceType, sourceKey: valid.sourceKey, ownerKey, actorKey: ownerKey, shareKey: valid.key, share: toArangoDoc(valid), replay }); if (!value) return null; const raw = withArangoKey(value as Record<string, unknown>) as Record<string, unknown>; return { share: shareSchema.parse(raw), requestHash: String(raw.requestHash), responseCiphertext: String(raw.responseCiphertext) }; },
    async getActiveGlobalShareByTokenHash(tokenHash, at) { const value = await one(database, 'FOR share IN shares FILTER share.sourceType IN ["image", "collection"] && share.tokenHash == @tokenHash && share.deletedAt == null FILTER share.revokedAt == null && (share.expiresAt == null || share.expiresAt > @at) LET scope = DOCUMENT(scopes, share.scopeKey) LET source = share.sourceType == "image" ? DOCUMENT(images, share.sourceKey) : DOCUMENT(collections, share.sourceKey) FILTER scope != null && scope.deletedAt == null && source != null && source.scopeKey == share.scopeKey && source.deletedAt == null LIMIT 1 RETURN share', { tokenHash, at }); return value ? parse(shareSchema, value) : null; },
    async getTag(scopeKey, tagKey) { const value = await one(database, 'FOR tag IN tags FILTER tag._key == @tagKey && tag.scopeKey == @scopeKey && tag.deletedAt == null LIMIT 1 RETURN tag', { scopeKey, tagKey }); return value ? parse(tagSchema, value) : null; },
  };
}

export class GalleryReferenceError extends Error { constructor(message: string) { super(message); this.name = 'GalleryReferenceError'; } }
let defaultRepository: GalleryRepository | undefined;
export function getDefaultGalleryRepository(): GalleryRepository { return defaultRepository ??= createGalleryRepository(); }
