import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const workspace = readFileSync(join(import.meta.dir, "../components/capability/AscendWorkspace.tsx"), "utf8");
const bridge = readFileSync(join(import.meta.dir, "event-bridge.tsx"), "utf8");
const playback = readFileSync(join(import.meta.dir, "book-playback.tsx"), "utf8");
const layout = readFileSync(join(import.meta.dir, "../app/_layout.tsx"), "utf8");

test("uses the standard shell and exact phone book geometry", () => {
  expect(workspace).toMatch(/<WorkspaceAppSwitcher\s+active="ascend"/);
  expect(workspace).toContain('<WorkspaceAppSwitcher active="ascend" trigger="back" />');
  expect(workspace).toContain('{bookPageOpen ? selectedBook?.title ?? "Audio book" : "Ascend"}');
  expect(workspace).toContain('accessibilityLabel="Create in Ascend"');
  expect(workspace).toMatch(/accessibilityLabel="Create in Ascend"[\s\S]*?size="xs"[\s\S]*?variant="icon"/);
  expect(workspace).toContain('localHeader: {\n    minHeight: 48,');
  expect(workspace).toContain('fontFamily: fonts.medium,\n    fontSize: 24,');
  expect(workspace).toContain('paddingTop: spacing.xs,\n    paddingBottom: spacing.md,');
  expect(workspace).toContain("const COLUMNS = 3");
  expect(workspace).toContain("const GRID_GAP = 8");
  expect(workspace).toContain("height: (cardWidth * 16) / 9");
  expect(workspace).toMatch(/accessibilityLabel=\{book\.title\}[\s\S]*?shape="rounded"/);
  expect(workspace).not.toContain("<AscendIcon");
  expect(workspace).not.toContain("styles.coverTitle");
  const bookGrid = workspace.slice(workspace.indexOf("{filteredBooks.map"), workspace.indexOf("{!overviewQuery.isPending"));
  const bookCard = bookGrid.slice(bookGrid.indexOf(": <Button"));
  expect(bookCard).not.toContain("styles.cardStatus");
  expect(bookCard).not.toContain('accessibilityRole="progressbar"');
  expect(bookCard).not.toContain("generationProgressPercent");
  expect(workspace).toContain("Array.from({ length: COLUMNS }");
  expect(workspace).toContain("contentMode=\"raw\"");
  expect(workspace).toContain("<CoreComposer");
});

test("uses a titleless centered text-only Ascend create menu", () => {
  expect(workspace).toContain('sheet === "actions"\n      ? ""');
  expect(workspace).toContain('hideHeading={sheet === "actions" || sheet === "filter" || sheet === "bookActions" || sheet === "bulkActions"}');
  const actions = workspace.slice(workspace.indexOf('{sheet === "actions" ? ('), workspace.indexOf('{sheet === "filter" ? ('));
  expect(actions).toContain('style={styles.sheetAction}');
  expect(actions).toContain('variant="secondary"');
  expect(actions).toContain('Create audio book');
  expect(actions).toContain('Create custom audio book');
  expect(actions).not.toContain('icon=');
  expect(actions).not.toContain('<AscendIcon');
  expect(workspace).toContain('sheetAction: { justifyContent: "center" }');
});

test("matches Archive root search, history, favorite, empty, and focus behavior", () => {
  expect(workspace).toContain('placeholder="Search..."');
  expect(workspace).toContain('iconOnly');
  expect(workspace).toContain('backgroundColor: palette.page');
  expect(workspace).toContain('<SearchHistorySheet');
  expect(workspace).toContain('checked={showOnlyFavorites}');
  expect(workspace).toContain('"No audio books yet."');
  expect(workspace).toContain('accessibilityLabel="Create audio book"');
  expect(workspace).not.toContain("KeyboardAvoidingView");
  expect(workspace).toContain('setRootSearchFocusable(false)');
  expect(workspace).toContain('queryFn: ({ signal }) => searchBooks(searchTerm, signal, Boolean(searchTerm), selectedTagKeys)');
  expect(workspace).toContain('const BOOK_SEARCH_DEBOUNCE_MS = 300');
  expect(workspace).toContain('accessibilityLabel={searchActive ? "Searching audio books" : "Loading audio books"}');
  expect(workspace).not.toContain('`${book.title} ${book.subtitle} ${book.description}`');
  expect(workspace).toContain('style={[styles.state, searchActive && styles.searchEmptyState]}');
  expect(workspace).toContain('searchEmptyState: { flexGrow: 1 }');
});

test("shares the session tag filter across the primary book list", () => {
  expect(workspace).toContain("const tagContextKey = tagFilterContextKey(contentContext)");
  expect(workspace).toContain("state.selectedTagsByContext[tagContextKey] ?? EMPTY_SELECTED_TAGS");
  expect(workspace).toContain("selectedTags.map(({ key }) => key).sort()");
  expect(workspace).toContain('<TagFilterLane context={contentContext} />');
  expect(workspace).toContain('variant="secondary">Tags</Button>');
  expect(workspace).toContain('<TagFilterSheet context={contentContext} onClose={() => setTagFilterOpen(false)} open={tagFilterOpen} />');
  expect(workspace).toContain("ascendQueryKeys.search(context, searchTerm, selectedTagKeys)");
  expect(workspace).toContain("Boolean(normalizedQuery || selectedTagKeys.length)");
});

test("keeps context selection explicit and generation asynchronous", () => {
  expect(workspace).toContain("archiveDocumentKeys: []");
  expect(workspace).toContain('currentKnowledge: ""');
  expect(workspace).toContain("closeCreationSheets();");
  const submitStart = workspace.indexOf("function submitDraft");
  expect(workspace.indexOf("closeCreationSheets();", submitStart)).toBeLessThan(workspace.indexOf("createMutation.mutate", submitStart));
  expect(workspace).toContain('chapterCount: 10');
  expect(workspace).not.toContain('chapterImages');
  expect(workspace).not.toContain('accessibilityLabel="Generate chapter images"');
  expect(workspace).not.toContain('>Chapter images</Text>');
  expect(workspace).not.toContain("const CHAPTER_OPTIONS =");
  expect(workspace).not.toContain("Audio book depth");
  expect(workspace).not.toContain('lengthMinutes');
  expect(workspace).toContain("const MAX_CONTEXT_DOCUMENTS = 10");
  expect(workspace).toContain("archiveOnly context={contentContext}");
  expect(workspace).toContain("maxSelection={MAX_CONTEXT_DOCUMENTS}");
  expect(workspace).toContain('onSelectionLimitReached={(limit) => showToast({ title: `You can select up to ${limit} items.`');
  expect(workspace).not.toContain("Archive sources");
  expect(workspace).not.toContain("listContentFolderTree");
  for (const status of ["queued", "researching", "planning", "writing", "narrating", "finalizing"]) expect(workspace).toContain(`\"${status}\"`);
});

test("holds chapter cards behind a complete three-card generation skeleton", () => {
  expect(workspace).not.toContain('setAutoOpenBookKey(book.key)');
  expect(workspace).toContain('key: `pending-${requestKey}`');
  expect(workspace).toContain('book.key.startsWith("pending-") || ["queued", "researching", "planning"].includes(book.status)');
  expect(workspace).not.toContain('ACTIVE_STATUSES.includes(book.status) && !book.coverUrl');
  expect(workspace).not.toContain("orderedReadyChapters");
  expect(workspace).toContain('const orderedChapters =');
  expect(workspace).toContain('{chapter.description}</Text>');
  expect(workspace).toContain('onPress={() => openChapterSummary(chapter.key)}');
  expect(workspace).not.toContain('accessibilityLabel="Search chapters"');
  expect(workspace).toContain('const detailBusy = Boolean(detail && (extensionPendingForDetail || !detailReady');
  expect(workspace).toContain('detailBusy ? Array.from({ length: 3 }');
  expect(workspace).toContain('Preparing audio book chapter ${index + 1}');
  expect(workspace).not.toContain('showNextChapterSkeleton');
  expect(workspace).not.toContain('revealedChapterCount');
  expect(workspace).not.toContain('sheet === "detail"');
  expect(playback).toContain('.filter((chapter) => chapter.content && chapter.audioUrl)');
});

test("uses sequential brief sheets with fresh self-improvement suggestions", () => {
  for (const state of ["createTopicOpen", "createTopicCustomOpen", "createGoalOpen", "createGoalCustomOpen", "createDetailsOpen"]) expect(workspace).toContain(state);
  expect(workspace).toContain("suggestBookTopics(excludeTopics)");
  expect(workspace).toContain("topicSuggestionsMutation.mutate(topicSuggestions)");
  expect(workspace).toContain("Array.from({ length: 3 }");
  expect(workspace).toContain('!topicSuggestionsMutation.isPending && topicSuggestions.length ? <Button onPress={() => { setCreateTopicOpen(false); setCreateTopicCustomOpen(true); }}');
  expect(workspace).toContain('<Text numberOfLines={1} style={styles.suggestionText}>{topic}</Text>');
  expect(workspace).toContain('<Text numberOfLines={1} style={styles.suggestionText}>{goal}</Text>');
  expect(workspace).toContain('<Text style={styles.inputLabel}>Topic</Text>');
  expect(workspace).toContain('<Text style={styles.inputLabel}>Goal</Text>');
  expect(workspace).not.toContain('onOpenActions={() => openBriefEditorActions("currentKnowledge")}');
  expect(workspace).not.toContain("What you already know");
  expect(workspace).not.toContain('accessibilityLabel="Book language"');
  expect(workspace).not.toContain('<Text style={styles.formLabel}>Writing tone</Text>');
  expect(workspace).toContain('accessibilityLabel="Custom audio book content"');
  expect(workspace).toContain('description="Write or paste the content and direction for your audio book."');
  expect(workspace).toContain('title="Create custom audio book"');
  expect(workspace).toContain('additionalInstructions: customBrief');
  expect(workspace).toContain('inputLabel: { marginLeft: 2, color: palette.silver300, fontFamily: fonts.medium, fontSize: 12, letterSpacing: 0.4 }');
  expect(workspace).toContain('customTextArea: { paddingTop: 12, lineHeight: 22 }');
  expect(workspace.match(/<AiTextEditor accessibilityLabel=/g)).toHaveLength(3);
  expect(workspace).not.toContain("customEditorStep");
  expect(workspace).toContain('onOpenActions={() => openBriefEditorActions("topic")}');
  expect(workspace).toContain('onOpenActions={() => openBriefEditorActions("goal")}');
  expect(workspace).toContain('onOpenActions={() => openBriefEditorActions("additionalInstructions")}');
  expect(workspace).toContain('title="AI actions"');
  expect(workspace).toContain('variant="secondary">Enhance</BottomSheetItem>');
  expect(workspace).toContain('variant="secondary">Translate</BottomSheetItem>');
  expect(workspace).toContain('title="Translate text"');
  expect(workspace).toContain('enhanceAppTextForContext(capturedContext, text)');
  expect(workspace).toContain('translateAppTextForContext(capturedContext, text, language)');
  expect(workspace).toContain('suggestionLoadingPill: { width: "100%", height: 40, borderRadius: 999 }');
  expect(workspace).toContain('open={createTopicOpen}');
  expect(workspace).toContain('open={createTopicCustomOpen}');
  expect(workspace).toContain('open={createGoalOpen}');
  expect(workspace).toContain('open={createGoalCustomOpen}');
  expect(workspace).toContain('open={createDetailsOpen}');
  expect(workspace).not.toContain("Show different ideas");
  expect(workspace).not.toContain("What do you want to improve?");
  expect(workspace).toContain("suggestBookGoals(topic, excludeGoals)");
  expect(workspace).toContain("goalSuggestionsMutation.mutate({ topic: draft.topic, excludeGoals: goalSuggestions })");
  expect(workspace).not.toContain("Show different goals");
  expect(workspace).not.toContain("What should this book help you achieve?");
  expect(workspace).toContain('footer={<><Button disabled={goalSuggestionsMutation.isPending} onPress={loadNewGoals} size="md" variant="primary">New goals</Button>');
  expect(workspace).toContain('!goalSuggestionsMutation.isPending && goalSuggestions.length ? <Button onPress={() => { setCreateGoalOpen(false); setCreateGoalCustomOpen(true); }}');
  expect(workspace).toContain('shape="pill" size="md" style={styles.suggestionPill}');
  expect(workspace).toContain("setCreateGoalOpen(true);");
  expect(workspace).toContain("setCreateDetailsOpen(true);");
  const openGoalStep = workspace.slice(workspace.indexOf("function openGoalStep"), workspace.indexOf("function loadNewGoals"));
  const completeNormalGoal = workspace.slice(workspace.indexOf("function completeNormalGoal"), workspace.indexOf("function submitDraft"));
  expect(openGoalStep).toContain("setCreateTopicOpen(false)");
  expect(openGoalStep).toContain("setCreateTopicCustomOpen(false)");
  expect(completeNormalGoal).toContain("submitDraft(nextDraft)");
  expect(completeNormalGoal).not.toContain("setCreateDetailsOpen(true)");
  expect(workspace).toContain('onPress={() => completeNormalGoal(goal)}');
  expect(workspace).toContain('onPress={() => completeNormalGoal(draft.goal.trim())}');
  expect(workspace).not.toContain("transitionCreationSheet");
  expect(workspace).toContain('fontSize: 12,\n    letterSpacing: 0.4,');
  expect(workspace).not.toContain('<Tabs accessibilityLabel="Audio book depth"');
  expect(workspace).toContain('detailTabs: { flexDirection: "row", gap: 4, padding: 3, borderWidth: 1, backgroundColor: palette.panel }');
  expect(workspace).not.toContain('const LANGUAGES =');
  expect(workspace).not.toContain('onPress={() => setDraft((current) => ({ ...current, language }))}');
  expect(workspace).toContain('const DEFAULT_NARRATOR = { key: "clear" as const, name: "Clear" }');
  expect(workspace).toContain('narratorVoiceKey: DEFAULT_NARRATOR.key');
  expect(workspace).toContain('narrationPace: 1');
  expect(workspace).not.toContain('<Text style={styles.formLabel}>Narrator</Text>');
  expect(workspace).not.toContain('<Text style={styles.formLabel}>Narration pace</Text>');
  expect(workspace).toContain('onPress={() => setCreateDetailsOpen(false)} size="md" variant="secondary">Close</Button>');
  expect(workspace).not.toContain("styles.footerButton");
  for (const label of ["TOPIC", "GOAL", "BOOK DEPTH", "LANGUAGE", "WRITING TONE", "NARRATOR", "NARRATION PACE", "ARCHIVE SOURCES", "ADDITIONAL INSTRUCTIONS"]) expect(workspace).not.toContain(`>${label}<`);
});

test("matches Signal attachment presentation for Archive context", () => {
  expect(workspace).toContain('<Text style={styles.contextChipText}>Context</Text>');
  expect(workspace).toContain('<Text style={styles.contextChipText}>Remove all</Text>');
  expect(workspace).toContain('style={styles.contextGrid}');
  expect(workspace).toContain('const contextCardSize = Math.floor(((contextGridWidth || width - 40) - 18) / 4)');
  expect(workspace).toContain('selection={contextSelection} title="Context"');
  expect(workspace).toContain('selection.filter(({ type }) => type === "document").map(({ key }) => key)');
  expect(workspace).toContain('onClose={() => setContextPickerOpen(false)}');
});

test("provides detail, chapter summaries, playback infrastructure, and lifecycle controls", () => {
  expect(workspace).toContain('detail.book.coverUrl ? <Cover book={detail.book} /> : <Skeleton accessibilityLabel="Creating audio book cover"');
  expect(workspace).toContain('<Skeleton style={styles.detailHeroSkeleton} />');
  expect(workspace).toContain('<Text style={styles.chapterHeading}>Chapters</Text>');
  expect(workspace).toContain('<LoadingText text={chapterLoadingText} />');
  expect(workspace).toContain('detail?.book.isExtending ? "Extending audio book..." : "Creating audio book..."');
  expect(workspace).not.toContain("detailHeroShade");
  expect(workspace).not.toContain("styles.detailTitle");
  expect(workspace).not.toContain("styles.detailMeta");
  expect(workspace).not.toContain("% complete</Text>");
  expect(workspace).not.toContain('playback.playbackBookKey === detail.book.key');
  expect(workspace).toContain('<Text style={styles.detailDescription}>{detail.book.description || "A description is unavailable for this audio book."}</Text>');
  expect(workspace).not.toContain('CURRENT CHAPTER');
  expect(workspace).not.toContain('styles.detailDuration');
  expect(workspace).toContain('accessibilityLabel={`About ${detail.book.title}`}');
  expect(workspace).toContain('onPress={() => open("bookSummary")}');
  expect(workspace).toContain('detailHero: { width: "100%", minHeight: (144 * 16) / 9, flexDirection: "row"');
  expect(workspace).toContain('width: 144,\n    height: (144 * 16) / 9,\n    flexShrink: 0,');
  expect(workspace).toContain("width: chapterWidth, height: 132");
  expect(workspace).toContain('sheet === "reader" ? <View style={styles.summarySheetContent}><Reader chapter={readerChapter} />');
  expect(workspace).toContain('description={sheet === "reader" ? readerChapter?.title : sheet === "chapterRead" ? readingChapter?.title : sheet === "bookSummary" ? detail?.book.title : undefined}');
  expect(workspace).toContain('height={sheet === "reader" || sheet === "chapterRead" || sheet === "bookSummary" ? "full" : undefined}');
  expect(workspace).toContain('sheet === "bookSummary" ? detail?.book.title : undefined');
  expect(workspace).toContain('sheet === "bookSummary"\n            ? "Audio book"');
  expect(workspace).toContain('footer={sheetFooter}');
  expect(workspace).toContain('detail?.book.description || "A description is unavailable for this audio book."');
  expect(workspace).not.toContain('hideCloseButton={sheet === "reader"}');
  expect(workspace).toContain('? "Audio book chapter"');
  expect(workspace).toContain('<Button disabled={!readerChapter?.content} onPress={() => openChapterReading(readerChapter?.key)}');
  expect(workspace).toContain('<Button disabled={!bookReadingChapter} onPress={() => openChapterReading(bookReadingChapter?.key)}');
  expect(workspace).toContain('{sheet === "chapterRead" ? <ChapterReading chapter={readingChapter} /> : null}');
  expect(workspace).toContain('accessibilityLabel="Previous chapter"');
  expect(workspace).toContain('accessibilityLabel="Next chapter"');
  expect(workspace).toContain('(index + offset + readableChapters.length) % readableChapters.length');
  expect(workspace).toContain('.replace(/\\\\n/g, "\\n")');
  expect(workspace).not.toContain('accessibilityLabel="Chapter position"');
  expect(workspace).not.toContain('sheet === "sleep"');
  expect(playback).toContain("audio.didJustFinish");
  expect(playback).toContain("setActiveForLockScreen");
  expect(playback).toContain("refreshUrl");
  expect(workspace).toContain("const bookPlaybackIsland = bookPageOpen && detailReady && detail && islandChapter && !playbackIslandDismissed");
  expect(workspace).toContain("const extensionPendingForDetail = extensionMutation.isPending && extensionMutation.variables?.bookKey === detail?.book.key");
  expect(workspace).toContain('detail?.book.status === "ready" && !detail.book.isExtending && !extensionPendingForDetail');
  expect(workspace).toContain('extensionPendingForDetail || detail?.book.isExtending ? "Extending audio book..."');
  expect(workspace).toContain("accessory={bookPlaybackIsland}");
  expect(workspace).toContain('accessibilityLabel="Audio book progress"');
  expect(workspace).toContain('accessibilityLabel={islandPlaying ? "Pause listening" : "Play audio"}');
  expect(workspace).toContain("playback.playBookChapter(detail.book.key, islandChapter.key, true)");
  expect(workspace).toContain("playableChapters.find(({ key }) => key === detail?.book.currentChapterKey)");
  expect(workspace).toContain("audioTimelinePosition(bookTimeline, islandChapterIndex");
  expect(workspace).toContain("resolveAudioTimelinePosition(bookTimeline, value)");
  expect(workspace).toContain("playback.playBookChapter(detail.book.key, destinationChapter.key, islandPlaying, destination.seconds)");
  expect(workspace).toContain('pageTransitionOrigin={sheet === "reader" || sheet === "chapterRead" || sheet === "bookSummary" ? "bottom" : "edge"}');
  expect(playback).toContain("if (progressSeconds <= persistedSeconds) return");
  expect(playback).toContain("intent: { progressSeconds, isCompleted: chapter.isCompleted }");
  expect(playback).toContain("const player = useAudioPlayer(null");
  expect(playback.match(/useAudioPlayer\(/g)).toHaveLength(1);
  expect(layout).toContain("<BookPlaybackProvider>");
  expect(layout).not.toContain("<BookMiniPlayer />");
  expect(playback).toContain("beginReplacement(id, request, audio.isLoaded)");
  expect(playback).toContain("const request = ++playbackRequest.current");
  expect(playback).toContain("request !== playbackRequest.current");
  const unmountCleanup = playback.slice(playback.indexOf("useEffect(() => () => {\n    playbackRequest.current += 1"), playback.indexOf("\n\n  const value"));
  expect(unmountCleanup).not.toContain("player.pause()");
  expect(unmountCleanup).not.toContain("player.clearLockScreenControls()");
  expect(workspace).toContain('pageKey={sheet === "chapterRead" ? `${sheet}:${readingChapterKey ?? "none"}` : sheet}');
  expect(workspace).toContain("if (!next) { setSheet(undefined); setReaderChapterKey(undefined); setReadingChapterKey(undefined); }");
  expect(workspace).not.toContain("Retry generation");
  expect(workspace).not.toContain("Cancel generation");
  expect(workspace).toContain("Delete audio book");
  expect(workspace).not.toContain('accessibilityLabel="Back to audio book creation"');
  expect(bridge).toContain('event.event === "book.changed"');
  expect(bridge).toContain("createCoalescedRefresh(");
  expect(bridge).toContain('queryClient.invalidateQueries({ queryKey: ascendQueryKeys.all(compassContext), refetchType: "active" })');
  expect(bridge).toContain("invalidateBooks()");
});

test("centers book titles and keeps chapter status text unboxed", () => {
  expect(workspace).toContain('backgroundColor: "rgba(0,0,0,0.62)"');
  expect(workspace).toContain('textAlign: "center"');
  expect(workspace).toContain('overflow: "hidden",\n    flexDirection: "column",\n    alignItems: "stretch",\n    justifyContent: "flex-end"');
  expect(workspace).not.toContain("chapterHeadingPill");
  expect(workspace).toContain('style={[styles.cardCopy, styles.chapterCardCopy]}');
  expect(workspace).toContain('style={[styles.cardTitle, styles.chapterCardTitle]}');
  expect(workspace).toContain('chapterCardCopy: { width: "100%", maxWidth: "100%", alignSelf: "stretch", alignItems: "stretch", marginTop: 0, marginBottom: 0, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, borderRadius: 0, backgroundColor: "transparent" }');
  expect(workspace).toContain('chapterCardTitle: { textAlign: "left" }');
  expect(workspace).toContain('chapterHeadingRow: { width: "100%", minHeight: 28, justifyContent: "center" }');
  const cardFrame = workspace.slice(workspace.indexOf("bookCardFrame:"), workspace.indexOf("bookCard:", workspace.indexOf("bookCardFrame:")));
  expect(cardFrame).not.toContain("borderWidth");
  expect(cardFrame).not.toContain("borderColor");
});

test("delegates custom topic and goal sheet focus to shared BottomSheet", () => {
  expect(workspace).not.toContain("setTimeout(() => customTopicInputRef.current?.focus(), 300)");
  expect(workspace).not.toContain("setTimeout(() => customGoalInputRef.current?.focus(), 300)");
  expect(workspace).toContain("focusKey={sheet}");
  expect(workspace).toContain("ref={customTopicInputRef}");
  expect(workspace).toContain("ref={customGoalInputRef}");
});

test("optimistically extends ready audio books by three chapters", () => {
  expect(workspace).toContain('selectedBook.status === "ready" ? <BottomSheetItem');
  expect(workspace).toContain('>Extend</BottomSheetItem>');
  expect(workspace).toContain('sheet === "extend"');
  expect(workspace).toContain('? "Extend audio book?"');
  expect(workspace).toContain('<Button disabled={extensionMutation.isPending} onPress={generateExtension} size="md" variant="primary">Extend</Button>');
  expect(workspace).toContain('previewBookExtension(bookKey, 3)');
  expect(workspace).toContain('extendBook(bookKey, 3, titles, requestKey)');
  expect(workspace).not.toContain('EXTENSION_CHAPTER_OPTIONS');
  expect(workspace).not.toContain('Extension chapter count');
  expect(workspace).not.toContain('extensionPreviewReady');
  expect(workspace).toContain('patchCachedBookMetadata(queryClient, context, book)');
  expect(workspace).toContain('const optimisticBook: Book = { ...previousBook, status: "queued", isExtending: true, chapterCount: previousBook.chapterCount + 3, generationProgressPercent: 0 }');
  expect(workspace).toContain('patchCachedBookMetadata(queryClient, context, optimisticBook)');
  expect(workspace).toContain('book === mutationContext.optimisticBook ? mutationContext.previousBook : book');
  expect(workspace).toContain('requestKey: randomUUID()');
  expect(workspace).not.toContain('ascendQueryKeys.extension');
});

test("optimistically removes a single deleted audio book without a loading button", () => {
  const lifecycle = workspace.slice(workspace.indexOf("const lifecycleMutation"), workspace.indexOf("const assistantMutation"));
  const deleteSheet = workspace.slice(workspace.indexOf('{sheet === "delete"'), workspace.indexOf('{sheet === "extend"'));
  expect(lifecycle.indexOf("removeCachedBook(queryClient, context, book.key)")).toBeLessThan(lifecycle.indexOf("await deleteBook(book.key, requestKey)"));
  expect(lifecycle).toContain("if (mutationContext?.deletedBook) addCachedBook");
  expect(deleteSheet).not.toContain("loading=");
  expect(deleteSheet).not.toContain("lifecycleMutation.isPending");
});

test("matches Archive bulk actions and uses cover-backed progress surfaces", () => {
  expect(workspace).toContain('import { ResourceTagsSheet } from "@/components/ResourceTagsSheet";');
  expect(workspace).toContain('accessibilityLabel="Selected audio book toolbar"');
  expect(workspace).toContain('accessibilityLabel="Clear selection"');
  expect(workspace).toContain('accessibilityLabel="Selected audio book actions"');
  expect(workspace).toContain('onLongPress={() => handleBookLongPress(book.key)}');
  expect(workspace).toContain('selected && styles.selectedItem');
  expect(workspace).toContain('selectedItem: { borderWidth: 2, borderColor: palette.silver50 }');
  expect(workspace).not.toContain('shadowOpacity: 0.62');
  expect(workspace).toContain('styles.selectionBadge');
  expect(workspace).toContain('sheet === "bulkActions"');
  expect(workspace).toContain('setBookFavorite(book.key, isFavorite)');
  expect(workspace).toContain('allSelectedFavorite ? "Unfavorite" : "Favorite"');
  expect(workspace).toContain('selectedBookKeys.map((key) => ({ type: "book" as const, key }))');
  expect(workspace).toContain('<ResourceTagsSheet context={contentContext} onClose={() => setResourceTagsOpen(false)} open={resourceTagsOpen} targets={resourceTagTargets} />');
  const bulkTags = workspace.slice(workspace.indexOf("function openSelectedBookTags"), workspace.indexOf("function closeCreationSheets"));
  expect(bulkTags).toContain("setSheetOpen(false)");
  expect(bulkTags).toContain("setSheet(undefined)");
  expect(bulkTags).toContain("requestAnimationFrame(() => setResourceTagsOpen(true))");
  expect(bulkTags).not.toContain("setSelectedBookKeys([])");
  const bulkActions = workspace.slice(workspace.indexOf('{sheet === "bulkActions"'), workspace.indexOf('{sheet === "bulkDelete"'));
  expect(bulkActions).toContain('<Button disabled={bulkLoading} onPress={openSelectedBookTags} size="md" variant="secondary">Tags</Button>');
  expect(bulkActions.indexOf('>Tags</Button>')).toBeLessThan(bulkActions.indexOf('>Delete</Button>'));
  expect(workspace).toContain('sheet === "bulkDelete"');
  expect(workspace).toContain('styles.compactSheetActions');
  expect(workspace).toContain('favorites = selectedBooks.filter(({ isFavorite }) => isFavorite)');
  expect(workspace).toContain('bulkMutationLocked.current = true');
  expect(workspace).toContain('error.code === "BOOK_FAVORITE"');
  expect(workspace).toContain('if (selectedBook.isFavorite)');
  expect(workspace).toContain('detail?.book.currentChapterKey');
  expect(workspace).not.toContain('style={styles.detailHeroShade}');
  expect(workspace).toContain('chapterSummaryPanel');
  expect(workspace).not.toContain('style={styles.readerBackdrop}');
  expect(workspace).not.toContain('chapter.isCompleted ? "Completed"');
  expect(workspace).not.toContain("styles.cardStatus");
});

test("favorites books optimistically without waiting to close the sheet", () => {
  const favorite = workspace.slice(workspace.indexOf("function updateBooksFavorite"), workspace.indexOf("function deleteSelectedBooks"));
  expect(favorite.indexOf("patchCachedBookMetadata(queryClient, context, { ...book, isFavorite })")).toBeLessThan(favorite.indexOf("Promise.allSettled"));
  expect(favorite.indexOf("setSheetOpen(false)")).toBeLessThan(favorite.indexOf("Promise.allSettled"));
  expect(favorite).not.toContain("setBulkLoading(true)");
  expect(favorite).not.toContain("setSheet(undefined)");
  expect(favorite).toContain("patchCachedBookMetadata(queryClient, context, previous)");
});
