import { expect, test } from "bun:test";
import { readFileSync } from "node:fs";
import { join } from "node:path";

const workspace = readFileSync(join(import.meta.dir, "../components/capability/AscendWorkspace.tsx"), "utf8");
const bridge = readFileSync(join(import.meta.dir, "event-bridge.tsx"), "utf8");
const playback = readFileSync(join(import.meta.dir, "book-playback.tsx"), "utf8");
const layout = readFileSync(join(import.meta.dir, "../app/_layout.tsx"), "utf8");

test("uses the standard shell and exact phone book geometry", () => {
  expect(workspace).toMatch(/<WorkspaceAppSwitcher\s+active="ascend"/);
  expect(workspace).toContain('<WorkspaceAppSwitcher active="ascend" trigger="back" />');
  expect(workspace).toContain('{bookPageOpen ? selectedBook?.title ?? "Audio book" : "Ascend"}');
  expect(workspace).toContain('accessibilityLabel="Create in Ascend"');
  expect(workspace).toMatch(/accessibilityLabel="Create in Ascend"[\s\S]*?size="xs"[\s\S]*?variant="icon"/);
  expect(workspace).toContain('localHeader: {\n    minHeight: 48,');
  expect(workspace).toContain('fontFamily: fonts.medium,\n    fontSize: 24,');
  expect(workspace).toContain('paddingTop: spacing.xs,\n    paddingBottom: spacing.md,');
  expect(workspace).toContain("const COLUMNS = 3");
  expect(workspace).toContain("const GRID_GAP = 8");
  expect(workspace).toContain("height: (cardWidth * 16) / 9");
  expect(workspace).toMatch(/accessibilityLabel=\{book\.title\}[\s\S]*?shape="rounded"/);
  expect(workspace).not.toContain("<AscendIcon");
  expect(workspace).not.toContain("styles.coverTitle");
  const bookGrid = workspace.slice(workspace.indexOf("{filteredBooks.map"), workspace.indexOf("{!overviewQuery.isPending"));
  const bookCard = bookGrid.slice(bookGrid.indexOf(": <Button"));
  expect(bookCard).not.toContain("styles.cardStatus");
  expect(bookCard).not.toContain('accessibilityRole="progressbar"');
  expect(bookCard).not.toContain("generationProgressPercent");
  expect(workspace).toContain("Array.from({ length: COLUMNS }");
  expect(workspace).toContain("contentMode=\"raw\"");
  expect(workspace).toContain("<CoreComposer");
});

test("uses a titleless centered text-only Ascend create menu", () => {
  expect(workspace).toContain('sheet === "actions"\n      ? ""');
  expect(workspace).toContain('hideHeading={sheet === "actions" || sheet === "filter" || sheet === "bookActions" || sheet === "bulkActions"}');
  const actions = workspace.slice(workspace.indexOf('{sheet === "actions" ? ('), workspace.indexOf('{sheet === "filter" ? ('));
  expect(actions).toContain('style={styles.sheetAction}');
  expect(actions).toContain('variant="secondary"');
  expect(actions).toContain('Create audio book');
  expect(actions).not.toContain('icon=');
  expect(actions).not.toContain('<AscendIcon');
  expect(workspace).toContain('sheetAction: { justifyContent: "center" }');
});

test("matches Archive root search, history, favorite, empty, and focus behavior", () => {
  expect(workspace).toContain('placeholder="Search..."');
  expect(workspace).toContain('iconOnly');
  expect(workspace).toContain('backgroundColor: palette.page');
  expect(workspace).toContain('<SearchHistorySheet');
  expect(workspace).toContain('checked={showOnlyFavorites}');
  expect(workspace).toContain('"No audio books yet."');
  expect(workspace).toContain('accessibilityLabel="Create audio book"');
  expect(workspace).toContain('behavior={aiInputFocused ? "height" : undefined}');
  expect(workspace).toContain('setRootSearchFocusable(false)');
});

test("keeps context selection explicit and generation asynchronous", () => {
  expect(workspace).toContain("archiveDocumentKeys: []");
  expect(workspace).toContain('currentKnowledge: ""');
  expect(workspace).toContain("closeCreationSheets();");
  expect(workspace.indexOf("closeCreationSheets();", workspace.indexOf("function submit()"))).toBeLessThan(workspace.indexOf("createMutation.mutate"));
  expect(workspace).toContain('chapterCount: 10');
  expect(workspace).toContain('chapterImages: true');
  expect(workspace).toContain('{ count: 10, label: "Short" }');
  expect(workspace).toContain('{ count: 25, label: "Standard" }');
  expect(workspace).toContain('{ count: 50, label: "Deep" }');
  expect(workspace).not.toContain('lengthMinutes');
  expect(workspace).toContain("const MAX_CONTEXT_DOCUMENTS = 50");
  expect(workspace).toContain("archiveOnly context={contentContext}");
  expect(workspace).toContain("maxSelection={MAX_CONTEXT_DOCUMENTS}");
  expect(workspace).not.toContain("Archive sources");
  expect(workspace).not.toContain("listContentFolderTree");
  for (const status of ["queued", "researching", "planning", "writing", "narrating", "finalizing"]) expect(workspace).toContain(`\"${status}\"`);
  expect(workspace).toContain('book.status === "failed" || book.status === "cancelled"');
});

test("reveals generated books and chapter summaries progressively", () => {
  expect(workspace).not.toContain('setAutoOpenBookKey(book.key)');
  expect(workspace).toContain('key: `pending-${requestKey}`');
  expect(workspace).toContain('if (book.key.startsWith("pending-")) return <Skeleton');
  expect(workspace).not.toContain('ACTIVE_STATUSES.includes(book.status) && !book.coverUrl');
  expect(workspace).not.toContain("orderedReadyChapters");
  expect(workspace).toContain('const orderedChapters =');
  expect(workspace).toContain('{chapter.description}</Text>');
  expect(workspace).toContain('onPress={() => openChapterSummary(chapter.key)}');
  expect(workspace).not.toContain('accessibilityLabel="Search chapters"');
  expect(workspace).toContain('const showNextChapterSkeleton');
  expect(workspace).toContain('Preparing chapter ${visibleChapterCount + 1}');
  expect(workspace).toContain('Math.min(current + 1, orderedChapters.length)');
  expect(workspace).not.toContain('sheet === "detail"');
  expect(playback).toContain('.filter((chapter) => chapter.content && chapter.audioUrl)');
});

test("uses persistent stacked brief sheets with fresh self-improvement suggestions", () => {
  for (const state of ["createTopicOpen", "createTopicCustomOpen", "createGoalOpen", "createGoalCustomOpen", "createDetailsOpen"]) expect(workspace).toContain(state);
  expect(workspace).toContain("suggestBookTopics(excludeTopics)");
  expect(workspace).toContain("topicSuggestionsMutation.mutate(topicSuggestions)");
  expect(workspace).toContain("Array.from({ length: 3 }");
  expect(workspace).toContain('!topicSuggestionsMutation.isPending && topicSuggestions.length ? <Button onPress={() => setCreateTopicCustomOpen(true)}');
  expect(workspace).toContain('<Text numberOfLines={1} style={styles.suggestionText}>{topic}</Text>');
  expect(workspace).toContain('<Text numberOfLines={1} style={styles.suggestionText}>{goal}</Text>');
  expect(workspace).toContain('<Text style={styles.inputLabel}>Topic</Text>');
  expect(workspace).toContain('<Text style={styles.inputLabel}>Goal</Text>');
  expect(workspace).not.toContain('onOpenActions={() => openBriefEditorActions("currentKnowledge")}');
  expect(workspace).not.toContain("What you already know");
  expect(workspace).not.toContain('accessibilityLabel="Book language"');
  expect(workspace).not.toContain('<Text style={styles.formLabel}>Writing tone</Text>');
  expect(workspace).not.toContain('accessibilityLabel="Additional instructions"');
  expect(workspace).toContain('inputLabel: { marginLeft: 2, color: palette.silver300, fontFamily: fonts.medium, fontSize: 12, letterSpacing: 0.4 }');
  expect(workspace).toContain('customTextArea: { paddingTop: 12, lineHeight: 22 }');
  expect(workspace.match(/<AiTextEditor accessibilityLabel=/g)).toHaveLength(2);
  expect(workspace).not.toContain("customEditorStep");
  expect(workspace).toContain('onOpenActions={() => openBriefEditorActions("topic")}');
  expect(workspace).toContain('onOpenActions={() => openBriefEditorActions("goal")}');
  expect(workspace).toContain('title="AI actions"');
  expect(workspace).toContain('variant="secondary">Enhance</BottomSheetItem>');
  expect(workspace).toContain('variant="secondary">Translate</BottomSheetItem>');
  expect(workspace).toContain('title="Translate text"');
  expect(workspace).toContain('enhanceAppTextForContext(capturedContext, text)');
  expect(workspace).toContain('translateAppTextForContext(capturedContext, text, language)');
  expect(workspace).toContain('suggestionLoadingPill: { width: "100%", height: 40, borderRadius: 999 }');
  expect(workspace).toContain('open={createTopicOpen}');
  expect(workspace).toContain('open={createTopicCustomOpen}');
  expect(workspace).toContain('open={createGoalOpen}');
  expect(workspace).toContain('open={createGoalCustomOpen}');
  expect(workspace).toContain('open={createDetailsOpen}');
  expect(workspace).not.toContain("Show different ideas");
  expect(workspace).not.toContain("What do you want to improve?");
  expect(workspace).toContain("suggestBookGoals(topic, excludeGoals)");
  expect(workspace).toContain("goalSuggestionsMutation.mutate({ topic: draft.topic, excludeGoals: goalSuggestions })");
  expect(workspace).not.toContain("Show different goals");
  expect(workspace).not.toContain("What should this book help you achieve?");
  expect(workspace).toContain('footer={<><Button disabled={goalSuggestionsMutation.isPending} onPress={loadNewGoals} size="md" variant="primary">New goals</Button>');
  expect(workspace).toContain('!goalSuggestionsMutation.isPending && goalSuggestions.length ? <Button onPress={() => setCreateGoalCustomOpen(true)}');
  expect(workspace).toContain('shape="pill" size="md" style={styles.suggestionPill}');
  expect(workspace).toContain("setCreateGoalOpen(true);");
  expect(workspace).toContain("setCreateDetailsOpen(true);");
  const openGoalStep = workspace.slice(workspace.indexOf("function openGoalStep"), workspace.indexOf("function loadNewGoals"));
  const openDetailsStep = workspace.slice(workspace.indexOf("function openDetailsStep"), workspace.indexOf("function submit"));
  expect(openGoalStep).not.toContain("setCreateTopicOpen(false)");
  expect(openGoalStep).not.toContain("setCreateTopicCustomOpen(false)");
  expect(openDetailsStep).not.toContain("setCreateGoalOpen(false)");
  expect(openDetailsStep).not.toContain("setCreateGoalCustomOpen(false)");
  expect(workspace).not.toContain("transitionCreationSheet");
  expect(workspace).toContain('fontSize: 12,\n    letterSpacing: 0.4,');
  expect(workspace).toContain('<Tabs accessibilityLabel="Audio book depth" accessibilityRole="tablist" style={styles.detailTabs}>');
  expect(workspace).toContain('detailTabs: { flexDirection: "row", gap: 4, padding: 3, borderWidth: 1, backgroundColor: palette.panel }');
  expect(workspace).not.toContain('const LANGUAGES =');
  expect(workspace).not.toContain('onPress={() => setDraft((current) => ({ ...current, language }))}');
  expect(workspace).toContain('const DEFAULT_NARRATOR = { key: "clear" as const, name: "Clear" }');
  expect(workspace).toContain('narratorVoiceKey: DEFAULT_NARRATOR.key');
  expect(workspace).toContain('narrationPace: 1');
  expect(workspace).not.toContain('<Text style={styles.formLabel}>Narrator</Text>');
  expect(workspace).not.toContain('<Text style={styles.formLabel}>Narration pace</Text>');
  expect(workspace).toContain('onPress={() => setCreateDetailsOpen(false)} size="md" variant="secondary">Close</Button>');
  expect(workspace).not.toContain("styles.footerButton");
  for (const label of ["TOPIC", "GOAL", "BOOK DEPTH", "LANGUAGE", "WRITING TONE", "NARRATOR", "NARRATION PACE", "ARCHIVE SOURCES", "ADDITIONAL INSTRUCTIONS"]) expect(workspace).not.toContain(`>${label}<`);
});

test("matches Signal attachment presentation for Archive context", () => {
  expect(workspace).toContain('<Text style={styles.contextChipText}>Context</Text>');
  expect(workspace).toContain('<Text style={styles.contextChipText}>Remove all</Text>');
  expect(workspace).toContain('style={styles.contextGrid}');
  expect(workspace).toContain('const contextCardSize = Math.floor(((contextGridWidth || width - 40) - 18) / 4)');
  expect(workspace).toContain('selection={contextSelection} title="Context"');
  expect(workspace).toContain('selection.filter(({ type }) => type === "document").map(({ key }) => key)');
  expect(workspace).toContain('onClose={() => setContextPickerOpen(false)}');
});

test("provides detail, chapter summaries, playback infrastructure, and lifecycle controls", () => {
  expect(workspace).toContain('<View style={styles.detailCover}><Cover book={detail.book} /></View>');
  expect(workspace).not.toContain("detailHeroShade");
  expect(workspace).not.toContain("styles.detailTitle");
  expect(workspace).not.toContain("styles.detailMeta");
  expect(workspace).not.toContain("% complete</Text>");
  expect(workspace).not.toContain('playback.playbackBookKey === detail.book.key');
  expect(workspace).toContain('detailCurrentChapter: { marginTop: spacing.sm,');
  expect(workspace).toContain('accessibilityLabel={`About ${detail.book.title}`}');
  expect(workspace).toContain('onPress={() => open("bookSummary")}');
  expect(workspace).toContain('detailHero: { width: "100%", minHeight: (144 * 16) / 9, flexDirection: "row"');
  expect(workspace).toContain('width: 144,\n    height: (144 * 16) / 9,\n    flexShrink: 0,');
  expect(workspace).toContain("height: (chapterWidth * 16) / 9");
  expect(workspace).toContain('sheet === "reader" ? <View style={styles.summarySheetContent}><Reader chapter={readerChapter} />');
  expect(workspace).toContain('description={sheet === "reader" ? readerChapter?.title : sheet === "chapterRead" ? readingChapter?.title : sheet === "bookSummary" ? detail?.book.title : undefined}');
  expect(workspace).toContain('height={sheet === "reader" || sheet === "chapterRead" || sheet === "bookSummary" ? "full" : undefined}');
  expect(workspace).toContain('sheet === "bookSummary" ? detail?.book.title : undefined');
  expect(workspace).toContain('sheet === "bookSummary"\n            ? "Audio book"');
  expect(workspace).toContain('footer={sheetFooter}');
  expect(workspace).toContain('detail?.book.description || "A description is unavailable for this audio book."');
  expect(workspace).not.toContain('hideCloseButton={sheet === "reader"}');
  expect(workspace).toContain('? "Audio book chapter"');
  expect(workspace).toContain('<Button disabled={!readerChapter?.content} onPress={() => openChapterReading(readerChapter?.key)}');
  expect(workspace).toContain('<Button disabled={!bookReadingChapter} onPress={() => openChapterReading(bookReadingChapter?.key)}');
  expect(workspace).toContain('{sheet === "chapterRead" ? <ChapterReading chapter={readingChapter} /> : null}');
  expect(workspace).toContain('accessibilityLabel="Previous chapter"');
  expect(workspace).toContain('accessibilityLabel="Next chapter"');
  expect(workspace).toContain('(index + offset + readableChapters.length) % readableChapters.length');
  expect(workspace).toContain('.replace(/\\\\n/g, "\\n")');
  expect(workspace).not.toContain('accessibilityLabel="Chapter position"');
  expect(workspace).not.toContain('sheet === "sleep"');
  expect(playback).toContain("audio.didJustFinish");
  expect(playback).toContain("setActiveForLockScreen");
  expect(playback).toContain("refreshUrl");
  expect(workspace).toContain("const bookPlaybackIsland = bookPageOpen && detail && islandChapter && !playbackIslandDismissed");
  expect(workspace).toContain("accessory={bookPlaybackIsland}");
  expect(workspace).toContain('accessibilityLabel="Audio book progress"');
  expect(workspace).toContain('accessibilityLabel={islandPlaying ? "Pause listening" : "Play audio"}');
  expect(workspace).toContain("playback.playBookChapter(detail.book.key, islandChapter.key, true)");
  expect(workspace).toContain("playableChapters.find(({ key }) => key === detail?.book.currentChapterKey)");
  expect(workspace).toContain("audioTimelinePosition(bookTimeline, islandChapterIndex");
  expect(workspace).toContain("resolveAudioTimelinePosition(bookTimeline, value)");
  expect(workspace).toContain("playback.playBookChapter(detail.book.key, destinationChapter.key, islandPlaying, destination.seconds)");
  expect(workspace).toContain("formatBookDuration((bookDuration || detail.book.estimatedMinutes * 60) / 60)");
  expect(workspace).toContain('remainingMinutes === 1 ? "min" : "mins"');
  expect(workspace).not.toContain('numberOfLines={2} style={styles.detailCurrentChapter}');
  expect(playback).toContain("if (progressSeconds <= persistedSeconds) return");
  expect(playback).toContain("intent: { progressSeconds, isCompleted: chapter.isCompleted }");
  expect(playback).toContain("const player = useAudioPlayer(null");
  expect(playback.match(/useAudioPlayer\(/g)).toHaveLength(1);
  expect(layout).toContain("<BookPlaybackProvider>");
  expect(layout).not.toContain("<BookMiniPlayer />");
  expect(playback).toContain("beginReplacement(id, request, audio.isLoaded)");
  expect(playback).toContain("const request = ++playbackRequest.current");
  expect(playback).toContain("request !== playbackRequest.current");
  const unmountCleanup = playback.slice(playback.indexOf("useEffect(() => () => {\n    playbackRequest.current += 1"), playback.indexOf("\n\n  const value"));
  expect(unmountCleanup).not.toContain("player.pause()");
  expect(unmountCleanup).not.toContain("player.clearLockScreenControls()");
  expect(workspace).toContain('pageKey={sheet === "chapterRead" ? `${sheet}:${readingChapterKey ?? "none"}` : sheet}');
  expect(workspace).toContain("if (!next) { setSheet(undefined); setReaderChapterKey(undefined); setReadingChapterKey(undefined); }");
  expect(workspace).toContain("Retry generation");
  expect(workspace).toContain("Cancel generation");
  expect(workspace).toContain("Delete audio book");
  expect(workspace).not.toContain('accessibilityLabel="Back to audio book creation"');
  expect(bridge).toContain('event.event === "book.changed"');
  expect(bridge).toContain("invalidateBooks()");
});

test("extends ready audio books through an uncached preview sheet", () => {
  expect(workspace).toContain('selectedBook.status === "ready" ? <BottomSheetItem');
  expect(workspace).toContain('>Extend</BottomSheetItem>');
  expect(workspace).toContain('title="Extend audio book"');
  expect(workspace).toContain('height="full"');
  expect(workspace).toContain('const EXTENSION_CHAPTER_OPTIONS = [1, 3, 5] as const');
  expect(workspace).toContain('accessibilityLabel="Extension chapter count"');
  expect(workspace).toContain('size="md" style={styles.detailTab}');
  expect(workspace).toContain('Array.from({ length: extensionChapterCount }');
  expect(workspace).toContain('<ActionPill key={`${index}-${title}`}>');
  expect(workspace).toContain('{extensionPreviewReady ? "Generate" : "Preview"}');
  expect(workspace).toContain('extensionPreviewMutation.reset()');
  expect(workspace).toContain('setExtensionChapterCount(1)');
  expect(workspace).toContain('patchCachedBookMetadata(queryClient, context, book)');
  expect(workspace).toContain('requestKey: randomUUID()');
  expect(workspace).not.toContain('ascendQueryKeys.extension');
});

test("matches Archive bulk actions and uses cover-backed progress surfaces", () => {
  expect(workspace).toContain('accessibilityLabel="Selected audio book toolbar"');
  expect(workspace).toContain('accessibilityLabel="Clear selection"');
  expect(workspace).toContain('accessibilityLabel="Selected audio book actions"');
  expect(workspace).toContain('onLongPress={() => handleBookLongPress(book.key)}');
  expect(workspace).toContain('selected && styles.selectedItem');
  expect(workspace).toContain('styles.selectionBadge');
  expect(workspace).toContain('sheet === "bulkActions"');
  expect(workspace).toContain('setBookFavorite(book.key, isFavorite)');
  expect(workspace).toContain('allSelectedFavorite ? "Unfavorite" : "Favorite"');
  expect(workspace).toContain('sheet === "bulkDelete"');
  expect(workspace).toContain('styles.compactSheetActions');
  expect(workspace).toContain('favorites = selectedBooks.filter(({ isFavorite }) => isFavorite)');
  expect(workspace).toContain('bulkMutationLocked.current = true');
  expect(workspace).toContain('error.code === "BOOK_FAVORITE"');
  expect(workspace).toContain('if (selectedBook.isFavorite)');
  expect(workspace).toContain('detail.book.currentChapterKey');
  expect(workspace).not.toContain('style={styles.detailHeroShade}');
  expect(workspace).toContain('chapterSummaryPanel');
  expect(workspace).not.toContain('style={styles.readerBackdrop}');
  expect(workspace).not.toContain('chapter.isCompleted ? "Completed"');
  expect(workspace).not.toContain("styles.cardStatus");
});
