export const LANDING_EVENT_SLUGS = [
  "landing.page_viewed",
  "landing.product_entered",
  "landing.orchestrator_entered",
  "landing.capability_entered",
  "landing.rock_entered",
  "landing.cta_clicked",
  "landing.cave_opened",
  "landing.cave_closed",
  "landing.audio_played",
  "landing.ambient_audio_started",
  "landing.mission_voice_played",
  "landing.mission_voice_cancelled",
  "landing.biome_fragment_collected",
  "landing.crystal_collected",
  "landing.crystal_room_filled",
  "landing.fragment_discovered",
  "landing.fragment_claim_clicked",
  "landing.fragment_join_to_claim_clicked",
  "waitlist.form_started",
  "waitlist.submit_clicked",
  "waitlist.signup_submitted",
  "waitlist.email_verified",
  "auth.signin_opened",
  "auth.signin_email_sent",
  "auth.magic_link_authenticated",
  "auth.signin_authed_jump",
  "auth.member_gate_opened",
  "waitlist.verify_jump_started",
  "legal.opened",
  "fragments.collected",
] as const;

export type LandingEventSlug = (typeof LANDING_EVENT_SLUGS)[number];
