// Fictional, dated source material for a personal knowledge-base demo.
// Details repeat deliberately so Core can reconcile changes across files.
import { createHash } from 'node:crypto';

export const workshopStableKey = (value: string) => `c${createHash('sha256').update(`workshop-year-v1\0${value}`).digest('hex').slice(0, 24)}`;
export const WORKSHOP_SCOPE_NAME = 'The Workshop Year';
export const WORKSHOP_SCOPE_MARKER = 'Dev fixture: workshop-year-v1. Mara Vale opens a neighborhood workshop.';

// Keep each file type represented at the root and across several project areas.
// Stable positions make reruns move existing fixtures without regenerating media.
export const workshopFolders = [
  { name: 'Planning' },
  { name: 'The Space' },
  { name: 'Community' },
  { name: 'Decisions', parent: 'Planning' },
  { name: 'At Work', parent: 'The Space' },
  { name: 'Opening', parent: 'Community' },
] as const;

export function workshopLocation(kind: 'document' | 'image' | 'audio' | 'video', index: number): string | undefined {
  const stride = { document: 1, image: 2, audio: 3, video: 4 }[kind];
  const slot = index * stride % (workshopFolders.length + 1);
  return slot ? workshopFolders[slot - 1]!.name : undefined;
}

export const workshopDocuments = [
  { name: 'why-a-workshop.md', folder: '01 Starting Point', date: '2026-01-08', text: `# Why a workshop\nMara Vale wants a neighborhood room where people can mend, make, and learn without buying specialist equipment. She imagines open tables, inexpensive evening sessions, and a quiet shelf of instructions anyone can borrow. The idea began after Iman helped her fix a lamp at the library.\n\nThe first version is ambitious: open six days a week, install eight benches, and buy a laser cutter. Nothing in this note is an approved budget. Mara will revisit it after speaking to neighbors and seeing the Canal Street room.` },
  { name: 'room-first-visit.md', folder: '01 Starting Point', date: '2026-01-12', text: `# First visit: 18 Canal Street\nMara and Lee visited the empty ground-floor room on 12 January. It measures roughly 8 by 11 metres, has two front windows, a rear sink, one accessible street entrance, and a narrow alcove near the meter. The ceiling is high but the north corner is dim. Lee suggested putting noisy work near the sink, away from the entrance.\n\nMara initially preferred eight fixed benches. The landlord quoted 1,450 per month and offered a three-month trial. This is a visit note, not a signed lease.` },
  { name: 'inspiration-notes.md', folder: '01 Starting Point', date: '2026-01-18', text: `# Things worth keeping\nA library-like welcome desk, visible tool labels, repair rather than replacement, shelves that can move, and warm task lighting. Mara likes muted blue and unpainted birch, but wants the actual room to feel lived-in rather than like an architectural rendering.\n\nReference images should show real materials and people at work. The first poster can be simple; the plan should not depend on expensive branding.` },
  { name: 'project-timeline.md', folder: '01 Starting Point', date: '2026-01-21', text: `# Working timeline\nJanuary: listen and measure. February: cost the space, test two layouts, and ask the electrician to visit. March: choose a smaller first phase. April: prepare a trial repair evening. May: review attendance, access, and costs before expanding.\n\nThis is a working timeline. The launch date was initially pencilled in for 2 April; the April meeting moved the public opening to 16 May.` },
  { name: 'conversation-with-iman.docx', folder: '02 People and Needs', date: '2026-01-25', text: `# Conversation with Iman\nIman runs informal repair nights at the library. She says people arrive with one small object and stay when they feel welcome asking basic questions. Her priority is a large shared table rather than rows of individual workstations. Keep one low bench and a clear path to the sink.\n\nIman can lead the first trial session if the room is ready by late April. She asked Mara to avoid language that implies visitors need experience or their own tools.` },
  { name: 'conversation-with-lee.md', folder: '02 People and Needs', date: '2026-01-28', text: `# Conversation with Lee\nLee builds furniture and offered to help assemble modular benches. Eight permanent benches would block the north corner and make group events difficult. Lee proposed four wheeled benches and one communal table.\n\nLee warned that reclaimed shelves need anchoring and that the alcove cannot safely hold the laser cutter. Mara agreed to price the simpler arrangement before choosing a layout.` },
  { name: 'neighborhood-survey.pdf', folder: '02 People and Needs', date: '2026-02-02', text: `NEIGHBORHOOD SURVEY — 23 RESPONSES\n14 asked for simple household repairs. 9 wanted beginner sewing. 7 mentioned woodworking. Several respondents selected more than one topic.\nMost preferred Wednesday evenings or Saturday mornings. Three people asked for step-free access and seating at a lower height. These are informal responses collected by Mara; they are not a representative market study.` },
  { name: 'accessibility-notes.md', folder: '02 People and Needs', date: '2026-02-05', text: `# Accessibility walkthrough\nKeep the accessible entrance clear, leave at least 1.2 metres along the central route, and provide one adjustable-height work surface. The rear sink is reachable only if the tool cart moves from the doorway. Good contrast on shelf labels matters more than decorative lettering.\n\nLayout A fails the central-route check when all eight benches are installed. Layout B can meet it with four movable benches. Confirm final clearances on site rather than treating this note as certification.` },
  { name: 'potential-activities.md', folder: '02 People and Needs', date: '2026-02-08', text: `# Activities to try\nStart with a free bring-one-thing repair evening, a low-cost beginner sewing session, and a Saturday tool introduction. Iman would host repair; Lee would help with the tool introduction.\n\nWoodworking classes and a laser cutter are later possibilities, not commitments. The first month should measure what neighbors actually use rather than fill the calendar to justify the original plan.` },
  { name: 'room-measurements.txt', folder: '03 Space and Design', date: '2026-02-10', text: `18 CANAL STREET — ROUGH MEASUREMENTS\nMain room 8.1 m x 10.8 m. Front windows: two, each 1.9 m wide. Door clear width: approximately 0.94 m. North alcove: 1.6 m x 2.2 m. Rear sink wall: 2.7 m.\nNumbers were taken with a hand tape and need verification before furniture is built. See electrician-visit.md for outlet locations.` },
  { name: 'layout-option-a.md', folder: '03 Space and Design', date: '2026-02-12', text: `# Layout A: eight fixed benches\nTwo rows of four benches, shelving along the north wall, and a small welcome desk by the front windows. This was Mara's first sketch. It seats more people on paper but narrows the central route and offers almost no space for a communal table.\n\nStatus: superseded after Iman's conversation and the accessibility walkthrough. Do not use this as the final furniture order.` },
  { name: 'layout-option-b.md', folder: '03 Space and Design', date: '2026-02-18', text: `# Layout B: adaptable room\nFour movable birch benches, a shared table by the windows, a low-height station beside it, and anchored storage on the west wall. The central route stays open between the street door and the sink. No laser cutter in phase one.\n\nIman prefers this layout for repair evenings. Lee can build the benches from the revised materials list. Mara has not yet signed off on the lighting until the electrician visits.` },
  { name: 'lighting-notes.md', folder: '03 Space and Design', date: '2026-02-21', text: `# Lighting notes\nThe window table gets good daylight, while the north corner is gloomy after 4 pm. Aim for warm, even ambient lighting and adjustable task lamps at each bench. Avoid a dramatic dark corner in the actual workspace even if it looks attractive in a concept image.\n\nThe electrician must confirm circuit capacity before Mara orders additional fixtures.` },
  { name: 'materials-and-colors.md', folder: '03 Space and Design', date: '2026-02-24', text: `# Material palette\nBirch work surfaces, muted blue signage, off-white walls, and durable charcoal mats. Use repairable components and visible fasteners. Reclaimed timber is welcome for non-structural shelves if Lee confirms it is sound.\n\nThe poster should echo this palette but the room is a working workshop, not a showroom.` },
  { name: 'electrician-visit.md', folder: '03 Space and Design', date: '2026-03-03', text: `# Electrician visit\nThe north-wall outlets share an older circuit; adding a laser cutter would require an upgrade. Four task lamps and ordinary hand tools are feasible with modest work, estimated at 1,100. The rear sink socket needs a protective replacement.\n\nMara decided to exclude the laser cutter from the first phase. This visit explains the increase between the initial and revised budgets and the final choice of Layout B.` },
  { name: 'initial-budget.md', folder: '04 Money and Logistics', date: '2026-02-01', text: `# Initial budget — draft\nRent: 1,450 per month. Eight benches: 2,400. Laser cutter: 3,800. Lighting: 500. Storage: 700. Launch materials: 400. This draft omitted electrical work, accessible furniture, and a reserve for the trial period.\n\nMara marked this version INVALID after the 3 March electrician visit. Use revised-budget.md for the working figures.` },
  { name: 'revised-budget.md', folder: '04 Money and Logistics', date: '2026-03-07', text: `# Revised phase-one budget\nRent: 1,450 per month on a three-month trial. Four movable benches and shared table: 1,650. Electrical and sink socket: 1,100. Adjustable-height station: 620. Anchored storage: 510. Lighting: 380. Launch materials: 180. Contingency: 650.\n\nThe laser cutter has been removed. Up-front fit-out is 5,090 including contingency, excluding rent. Mara will review spending after the trial evening before buying more equipment.` },
  { name: 'equipment-list.md', folder: '04 Money and Logistics', date: '2026-03-09', text: `# First-phase equipment\nFour wheeled benches, one communal table, one adjustable-height station, six task lamps, labeled hand-tool drawers, a first-aid kit, and washable work mats. Borrow two sewing machines for the trial rather than buy them.\n\nDeferred: laser cutter, large dust extractor, and permanent rows of benches. The list follows Layout B and the revised budget.` },
  { name: 'supplier-quotes.pdf', folder: '04 Money and Logistics', date: '2026-03-11', text: `# Supplier notes\nLee's birch bench estimate is 1,650 including the shared table. A local supplier quoted 510 for anchored storage. The adjustable-height station is estimated at 620. These are planning figures, not purchase orders.\n\nMara should check availability before the May opening; the blue paint sample is only for signage, not every wall.` },
  { name: 'weekly-opening-plan.pdf', folder: '04 Money and Logistics', date: '2026-03-15', text: `# Trial opening hours\nWednesday 18:00–21:00 for guided repair, Saturday 10:00–14:00 for an open workshop. Keep Monday for maintenance and preparation. The January note proposed six days a week; that was not affordable with the revised budget.\n\nIman can cover the first two Wednesday sessions. The timetable is provisional until the 16 May public opening.` },
  { name: 'decision-log.md', folder: '05 Decisions and Launch', date: '2026-03-18', text: `# Decision log\n12 January: explore 18 Canal Street, no lease signed. 5 February: reject Layout A's narrow route. 3 March: electrician rules out phase-one laser cutter. 7 March: adopt revised budget and four movable benches. 18 March: Mara chooses Layout B, subject to final measurements.\n\nOpen question: whether the trial repair evening can take place in late April. See meeting-notes-april.md for the answer.` },
  { name: 'meeting-notes-march.md', folder: '05 Decisions and Launch', date: '2026-03-20', text: `# March meeting — Mara, Iman, Lee\nMara presented the smaller phase-one plan. Iman supports Layout B because it leaves room for people to work together. Lee will prototype one wheeled bench before building the other three.\n\nThe group agreed to print only a few trial invitations. The original 2 April opening date is unlikely; Mara will decide after the electrical work is scheduled.` },
  { name: 'meeting-notes-april.docx', folder: '05 Decisions and Launch', date: '2026-04-09', text: `# April meeting — change of dates\nElectrical work is booked for 20 April. The private bring-one-thing trial moves to 30 April. Public opening moves from the pencilled-in 2 April date to Saturday 16 May. Iman will help run the trial and Lee will check the bench brakes.\n\nMara approved Layout B and the revised budget. The final poster must show 16 May; the early poster draft has the old date.` },
  { name: 'workshop-guidelines.md', folder: '05 Decisions and Launch', date: '2026-04-11', text: `# Welcome and safety\nAsk before using an unfamiliar tool. Label any item brought for repair. Keep the central route clear and return tools to the marked drawers. Children should work with an accompanying adult. The room is for learning together, not for judging someone's skill.\n\nOffer the adjustable-height table without requiring anyone to explain why they need it.` },
  { name: 'first-event-plan.md', folder: '05 Decisions and Launch', date: '2026-04-14', text: `# Bring-one-thing trial — 30 April\nInvite twelve neighbors for a small repair evening before the public opening. Iman welcomes visitors, Lee checks tools, and Mara collects anonymous feedback. Set up the communal table near the front windows and keep the central path clear.\n\nThe trial is not the 16 May opening. Avoid promising repairs that need specialist electrical certification.` },
  { name: 'poster-copy.md', folder: '05 Decisions and Launch', date: '2026-04-17', text: `# Poster wording\nTHE WORKSHOP AT CANAL STREET — Bring your curiosity. Mend, make, and learn together. Public opening Saturday 16 May, 10:00–14:00, 18 Canal Street. No experience or tools needed. Step-free street entrance and a lower work surface available.\n\nAn earlier draft said 2 April and showed a laser cutter. Do not use that version.` },
  { name: 'opening-announcement.docx', folder: '05 Decisions and Launch', date: '2026-04-22', text: `# Opening announcement\nAfter months of listening, measuring, and changing the plan, Mara is opening a small neighborhood workshop at 18 Canal Street on Saturday 16 May. The room will start with four movable benches, one shared table, and a focus on accessible repair and beginner sessions.\n\nThanks to Iman for helping shape the sessions and Lee for building the benches. The first public hours will be Wednesday evenings and Saturday mornings.` },
  { name: 'six-month-vision.md', folder: '05 Decisions and Launch', date: '2026-04-25', text: `# Six-month vision\nIf the trial succeeds, document what visitors come to learn before adding equipment. Host regular repair evenings, invite guest makers, publish short instructions, and revisit the hours after three months. A laser cutter is an option only after electrical work and demand justify it.\n\nThe measure of success is whether neighbors return, not whether every shelf is full.` },
  { name: 'lessons-so-far.md', folder: '05 Decisions and Launch', date: '2026-05-01', text: `# What the 30 April trial taught us\nEleven of twelve invited neighbors attended. Most stayed around the shared table, and two visitors used the lower work surface. The movable benches made cleanup easier. The tool labels need larger print, and the sink area was crowded once.\n\nMara will move one tool cart before the 16 May opening. The trial supported the smaller, adaptable Layout B rather than the eight-bench original.` },
  { name: 'final-layout-rationale.md', folder: '03 Space and Design', date: '2026-05-03', text: `# Why Layout B won\nThe February accessibility review showed that eight fixed benches narrowed the route through the room. Iman wanted a communal table. Lee could build four movable benches for less, and the electrician's March visit removed the laser cutter from phase one.\n\nMara approved Layout B in April; the 30 April trial confirmed it works, with the tool cart moved away from the sink. Treat Layout A as an archived proposal, not the present room.` },
] as const;

const look = 'Candid documentary photograph, believable small neighborhood makerspace at 18 Canal Street, practical birch furniture, muted blue details, natural imperfect textures, no legible text, no logos, no staged corporate aesthetic.';
export const workshopImages = [
  { name: 'room-entrance', folder: 'Room Photos', prompt: `Street-level accessible entrance and two broad front windows of an empty neighborhood workshop in early winter. ${look}` },
  { name: 'room-wide-interior', folder: 'Room Photos', prompt: `Wide interior of the same 8 by 11 metre room, front windows, rear sink, slightly dim north corner, before renovation. ${look}` },
  { name: 'room-window-corner', folder: 'Room Photos', prompt: `Sunlight crossing the front-window corner intended for a communal table, room still largely empty. ${look}` },
  { name: 'room-storage-wall', folder: 'Room Photos', prompt: `West wall of the same empty workshop, exposed shelf brackets and room for anchored tool storage. ${look}` },
  { name: 'sketch-first-layout', folder: 'Layout Studies', prompt: 'Overhead photograph of a rough pencil floor-plan sketch with eight crowded fixed workbenches in two rows, no readable handwriting, notebook on a birch desk.' },
  { name: 'sketch-revised-layout', folder: 'Layout Studies', prompt: 'Overhead photograph of a revised pencil floor-plan sketch with four movable workbenches, shared window table, generous central aisle, no readable handwriting.' },
  { name: 'sketch-workbench', folder: 'Layout Studies', prompt: `Detail of a hand-drawn construction sketch beside a partly assembled wheeled birch workbench, workshop setting. ${look}` },
  { name: 'sketch-lighting', folder: 'Layout Studies', prompt: `Small warm adjustable task lamp on a movable birch bench, north corner now evenly lit. ${look}` },
  { name: 'material-birch', folder: 'Materials', prompt: `Close-up of unfinished birch offcuts and visible repairable fasteners on the shared workshop table. ${look}` },
  { name: 'material-palette', folder: 'Materials', prompt: `Muted blue paint swatch, off-white plaster sample, birch timber, charcoal work mat arranged as a modest materials board. ${look}` },
  { name: 'material-shelves', folder: 'Materials', prompt: `Simple anchored reclaimed-wood shelving on the west wall, practical labeled drawers without legible words. ${look}` },
  { name: 'material-tool-storage', folder: 'Materials', prompt: `Well-used hand tools in organized drawers and a mobile cart parked clear of the main accessible route. ${look}` },
  { name: 'community-noticeboard', folder: 'Community', prompt: `Neighborhood noticeboard outside the workshop with abstract pinned flyers, overcast spring morning, no readable text. ${look}` },
  { name: 'community-table', folder: 'Community', prompt: `Iman and several adults around the large shared table learning to mend a lamp, candid welcoming atmosphere. ${look}` },
  { name: 'community-repair', folder: 'Community', prompt: `Close-up of hands repairing a small household object at a lower-height accessible work surface. ${look}` },
  { name: 'community-evening', folder: 'Community', prompt: `Quiet Wednesday evening repair session, four movable workbenches, clear central route, warm task lighting. ${look}` },
  { name: 'poster-early-concept', folder: 'Launch Visuals', prompt: 'Photograph of an early minimal blue-and-birch community workshop poster pinned to a wall, abstract blocks instead of readable text, work in progress.' },
  { name: 'poster-illustrated-concept', folder: 'Launch Visuals', prompt: 'Second illustrated community workshop poster concept showing a shared worktable and simple hand tools, muted blue and warm birch, no readable text.' },
  { name: 'poster-photo-concept', folder: 'Launch Visuals', prompt: 'Third community workshop poster concept using a candid photograph of neighbors around a table, muted blue border, no readable text.' },
  { name: 'poster-final-concept', folder: 'Launch Visuals', prompt: 'Final restrained community workshop launch graphic: inviting room, movable birch benches, shared table, warm blue accents, no readable text or date.' },
] as const;

export const workshopAudio = [
  { name: 'voice-note-first-visit', source: 'room-first-visit.md', voice: 'eve', text: 'I just walked through the Canal Street room with Lee. The front windows are wonderful, but the north corner needs light. I was imagining eight benches. Lee thinks we should measure the central route before committing to that many.' },
  { name: 'voice-note-iman', source: 'conversation-with-iman.docx', voice: 'ara', text: 'Iman reminded me that people come to repair evenings with questions, not expertise. She wants one big shared table, a clear path through the room, and somewhere comfortable to sit and learn.' },
  { name: 'voice-note-electrician', source: 'electrician-visit.md', voice: 'eve', text: 'The electrician confirmed the north wall cannot support a laser cutter without a much bigger upgrade. It is disappointing, but it makes the decision easier. We can start smaller and build a welcoming room first.' },
  { name: 'voice-note-layout-choice', source: 'decision-log.md', voice: 'rex', text: 'Today I chose the adaptable layout. Four movable benches, the window table, and room for everyone to move around. The first eight-bench sketch was exciting, but it was not the room our neighbors needed.' },
  { name: 'voice-note-after-trial', source: 'lessons-so-far.md', voice: 'eve', text: 'Eleven neighbors came to the trial. They gathered around the shared table and the movable benches worked. We need bigger tool labels and more space near the sink, but this finally feels like a real place.' },
  { name: 'spoken-project-vision', source: 'why-a-workshop.md', voice: 'sal', text: 'The Workshop at Canal Street is a place to mend, make, and learn without needing expensive equipment or previous experience. It began with a repaired lamp and a simple question: what if neighbors could figure things out together?' },
  { name: 'spoken-layout-rationale', source: 'final-layout-rationale.md', voice: 'leo', text: 'We chose four movable benches instead of eight fixed ones. The change preserves a clear central route, makes space for a communal table, and lets the room adapt to different sessions. The smaller plan also fits the revised budget.' },
  { name: 'spoken-event-invitation', source: 'first-event-plan.md', voice: 'ara', text: 'Bring one small thing you would like help repairing to our trial evening on the thirtieth of April. Iman, Lee, and Mara will be there. You do not need tools or experience; curiosity is enough.' },
  { name: 'spoken-opening-announcement', source: 'opening-announcement.docx', voice: 'sal', text: 'Join us at eighteen Canal Street on Saturday the sixteenth of May. Our new neighborhood workshop opens with a shared table, accessible work space, and beginner-friendly repair sessions. Bring your curiosity.' },
  { name: 'spoken-six-month-vision', source: 'six-month-vision.md', voice: 'leo', text: 'Over the next six months, we will listen to what neighbors need, hold regular repair evenings, and share what we learn. We can add more equipment later. For now, success means people feel welcome and want to return.' },
] as const;

export const workshopVideos = [
  { name: 'room-walkthrough', image: 'room-wide-interior', prompt: 'Five-second steady documentary camera move through the small Canal Street workshop, front windows, clear central aisle, four movable birch benches, realistic light and geometry.' },
  { name: 'workbench-in-use', image: 'sketch-workbench', prompt: 'Five-second realistic close-up of hands carefully assembling and rolling a birch workbench in a modest neighborhood workshop; stable camera, natural motion.' },
  { name: 'evening-session', image: 'community-evening', prompt: 'Five-second candid evening repair session, warm adjustable task lamps, neighbors collaborating at a shared table, subtle believable motion.' },
  { name: 'launch-graphic-motion', image: 'poster-final-concept', prompt: 'Five-second gentle motion study of a restrained muted-blue illustrated workshop opening graphic, birch textures, no words or logos, elegant subtle movement.' },
  { name: 'opening-day', image: 'community-table', prompt: 'Five-second documentary opening-day glimpse of an inviting small neighborhood makerspace, people greeting one another around a shared table, natural motion.' },
] as const;
