#!/usr/bin/env bash
set -euo pipefail

cd "${DEPLOY_DIR:-$HOME/vorinthex}"
: "${IMAGE:?IMAGE must be set by the deploy pipeline}"
test -s .env || { echo "::error::.env is missing or empty"; exit 1; }
export IMAGE
export COMMIT_SHA="${COMMIT_SHA:-${IMAGE##*:}}"

require_env() {
  local key="$1"
  local value
  value="$(grep -E "^${key}=" .env | tail -n 1 | cut -d= -f2- || true)"
  if [ -z "$value" ]; then
    echo "::error::$key is missing or empty in .env"
    exit 1
  fi
  case "$value" in
    *://HOST:*|*://host:*|HOST|host)
      echo "::error::$key contains placeholder hostname '$value'"
      exit 1
      ;;
  esac
}

require_env REDIS_URL
require_env ARANGO_URL
require_env ARANGO_DATABASE
require_env ARANGO_USERNAME
require_env ARANGO_ROOT_PASSWORD

write_caddyfile() {
  local color="$1"
  cat > Caddyfile <<EOF
# Generated by deploy-app.sh; active app color: $color
api.vorinthex.com {
	reverse_proxy app-$color:3001 {
		health_uri /api/v1/health
		health_interval 10s
		health_timeout 5s
	}
}
EOF
}

healthy() {
  local color="$1"
  local container="vorinthex-app-$color-1"
  for i in $(seq 1 72); do
    local status
    status=$(docker inspect -f '{{.State.Health.Status}}' "$container" 2>/dev/null || echo starting)
    echo "health[$color] attempt $i: $status"
    [ "$status" = healthy ] && return 0
    sleep 5
  done
  docker logs --tail 80 "$container" || true
  return 1
}

ACTIVE="$(cat .active 2>/dev/null || echo none)"
if [ "$ACTIVE" = blue ]; then IDLE=green; else IDLE=blue; fi
echo "Active color: $ACTIVE -> deploying idle color: $IDLE ($IMAGE)"

if [ ! -f Caddyfile ]; then
  [ "$ACTIVE" = none ] && write_caddyfile "$IDLE" || write_caddyfile "$ACTIVE"
fi

docker pull "$IMAGE" >/dev/null
docker compose up -d --no-deps --remove-orphans caddy

if [ "$ACTIVE" = none ]; then
  write_caddyfile "$IDLE"
fi

docker compose up -d --no-deps --force-recreate --remove-orphans "app-$IDLE"
if ! healthy "$IDLE"; then
  echo "::error::app-$IDLE failed health check; Caddy not flipped"
  docker compose stop "app-$IDLE" || true
  exit 1
fi

write_caddyfile "$IDLE"
docker exec vorinthex-caddy-1 caddy reload --config /etc/caddy/Caddyfile --adapter caddyfile
if [ "$ACTIVE" != none ]; then
  docker compose stop "app-$ACTIVE" || true
fi
echo "$IDLE" > .active
docker image prune -f >/dev/null || true
echo "Vorinthex app now serving app-$IDLE ($IMAGE)"

